from test_cmdline_commands.contexts.commandline_context import CommandlineContext as _base
from textwrap import dedent as sample


class ParametersContext(_base):
    #
    #
    # PARAMETERS
    # =================================================================================================================]
    change_list = {
        'AgentPort'       : '5742',
        'LogDeletePeriod' : '55',
        'ReportsFolder'   : './reports_new',
        'SyslogTrace'     : '1',
        'TfaMailSubject'  : 'custom_test_subject',
    }

    #
    #
    # OUTPUT SAMPLES
    # =================================================================================================================]
    parameters_list = sample('''
        AWSusesHTTPS
        AWSSDKLoggingEnable
        AcceptOnlyEncryptedSessions
        AcceptOnlyMappedUsers
        ActionAfterErrorInParsing
        AdditionalEnvironmentPaths
        AgentHost
        AgentPort
        AllowUpdateMetadataBunchMode
        AlwaysResendPacketAfterParsing
        AlwaysResendPacketByQueue
        AntlrTokenPoolMaxWarmSize
        AntlrIntTrace
        AntlrLexTrace
        AntlrMaxConstantsInExpression
        AntlrTrace
        AppInterchangeThreadCount
        AppUserTrace
        AuditAWSRoleArn
        AuditAWSSecretID
        AuditActiveRotationID
        AuditArchiveFolderSizeLimit
        AuditAwsRegion
        AuditCleanerDeleteLimit
        AuditConnectionsLoadInterval
        AuditCustomConnectionString
        AuditDataMySQLUseLoad
        AuditDataPgSQLUseLoad
        AuditDataScheduleTimer
        AuditDatabaseHost
        AuditDatabaseName
        AuditDatabasePort
        AuditDatabaseProtocolType
        AuditDatabaseSchema
        AuditDatabaseSecondaryHosts
        AuditDatabaseType
        AuditDiscFreeSpaceLimit
        AuditExecutionRulesLoadInterval
        AuditFieldCryptEnabled
        AuditFieldCryptOptions
        AuditHighWaterMark
        AuditJournalQueueFillPercentWarning
        AuditJournalThreadMaxCycleGap
        AuditLastDbVersion
        AuditLastGmtOffset
        AuditLoadDataFolderSizeLimit
        AuditLoadFilesSizeLimit
        AuditLoadTrace
        AuditLogin
        AuditLoginType
        AuditLowWaterMark
        AuditMaskPassword
        AuditMaskPasswordValue
        AuditMaxColumnDataSize
        AuditMySQLInnoDBLockTimeout
        AuditObjects
        AuditOperationDataLoadInterval
        AuditOperationDatasetLoadInterval
        AuditOperationExecLoadInterval
        AuditOperationGroupsLoadInterval
        AuditOperationMetaLoadInterval
        AuditOperationRulesLoadInterval
        AuditOperationsLoadInterval
        AuditOtlLongSize
        AuditOtlStreamBufferSize
        AuditPartitionCountCreatedInAdvance
        AuditPartitionEnable
        AuditPartitionFirstEndDateTime
        AuditPartitionFutureRecreateTime
        AuditPartitionInterval
        AuditPartitionMode
        AuditPartitionShort
        AuditPartitionTrace
        AuditPassword
        AuditPasswordQuery
        AuditPortionSize
        AuditPutThreadQueueWait
        AuditRotationAgeThreshold
        AuditRotationEnabled
        AuditRotationMaxCount
        AuditRotationMode
        AuditRotationSizeThreshold
        AuditRotationTotalSize
        AuditRulesObjectDetailLoadInterval
        AuditRulesStatLoadInterval
        AuditSSL
        AuditSessionRulesLoadInterval
        AuditSessionsLoadInterval
        AuditSleepSeconds
        AuditSqliteCacheSize
        AuditSqliteJournalMode
        AuditSqliteSynchronous
        AuditStopTime
        AuditSubQueryOperationLoadInterval
        AuditThreads
        AuditThreadsPriority
        AuditThroughputStatLoadInterval
        AuditTrace
        AuditTrafficStatLoadInterval
        AuditTransactionsLoadInterval
        AuditTryRepairTimer
        AuroraErrorCode
        AuroraMySQLConnectorAllowedTLSVersions
        AuthenticatorTrace
        AuthorizationErrorsCheckPeriod
        AuthorizationErrorsEnable
        AuthorizationErrorsLimit
        AutoLockerTrace
        AwsProductCode
        BackendAuditConnectionCount
        BackendDynamicMemoryArenas
        BackendLogName
        BackendMainThreadMaxCycleGap
        BackendMainThreadTrace
        BackendSigsegvDetail
        BackendSigsegvLogName
        BackgroundAuditUpdaterDelayedStart
        BackgroundInterManagerUpdateDuration
        CEF_AuthErrReportRow
        CEF_DeviceProduct
        CEF_DeviceVendor
        CEF_DeviceVersion
        CEF_OperationReportHeader
        CEF_OperationReportRow
        CEF_SessionReportHeader
        CEF_Version
        CheckFirewallActivityPeriod
        CheckHackMsSQLRule
        CheckLicenseExpired
        CleanAuditBySessionID
        CollectCoreExitInfo
        ConfigPrefix
        CopyTextFormatDataChunkMaxSize
        CoreAdditionalCommandLineArg
        CoreDynamicMemoryArenas
        CoreLoadTimeout
        CoreMainThreadMaxCycleGap
        CoreObjectCounterTrace
        CyberArkApplicationID
        DAOBulkInsertSize
        DAOShortStatementTimeout
        DB2ErrorCode
        DB2PreparedStatementMaskingMethod
        DSARReportRowsLimit
        DSARTrace
        DataBufferSize
        DataDiscoveryS3FilePartToRead
        DatabaseUpdaterHighWaterMark
        DatabaseUpdaterLowWaterMark
        DatabaseUpdaterUsePutqWithTimeout
        Db2BackendLoginTimeout
        Db2KeyStashPath
        Db2KeyStoragePath
        Db2ParserTrace
        Db2UseXmlAggFunction
        DdlDataModelLearningTrace
        DelayForMetadataUpdating
        DictionaryBackupFolder
        DisableAudit
        DisableAuditCleanNotify
        DisableMetadataCache
        DisablePacketParsing
        DiscoveryMaxBatchRowsCount
        DistributeSessionsToThreads
        DnsSrvTrace
        DoubleRunGuard
        DsFunctionRunTimeout
        DsTableCheckDurationMs
        DumpServerURL
        DynamoParserTrace
        DynamoUserUpdateEnable
        DynamoUserUpdatePeriod
        EDConnectionTimeout
        EDServerDefaultHost
        EDServerDefaultPort
        ElasticSearchMaxMaskedSize
        ElasticSearchParserTrace
        EnableAWSMetrics
        EnableDataConverter
        EnableOracleNativeEncryption
        EnterpriseOID
        ErResolverTrace
        EventManagerFlushIntervalInSeconds
        ExceptionInAssertsFromRecognizer
        ExternalJSONMetadata
        FileBufferAutoCreateBucket
        FileBufferPartReadPerBlock
        FileBufferStoragePath
        FileBufferTrace
        FileBufferUseLocalStorage
        FilledMessageHandlerSetParsingError
        FirebirdHandlerTrace
        FirebirdParserTrace
        FirewallCoreGenerateInfoOnExit
        FirewallCoreLogName
        FirewallCoreSigsegvDetail
        FlushTimeout
        FlushTrace
        ForceAudit
        ForceFlushCoreLog
        FreezeDetectorTrace
        FunctionMasking
        GenerateCrashDump
        GenerateCrashDumpBackend
        GreenplumErrorCode
        GreenplumParserHandleCoreObject
        GreenplumParserRequireSessionMetadata
        GreenplumParserSSLMode
        GreenplumParserTestMode
        GreenplumProtocolReaderBufferWatermark
        HAClusterName
        HanaErrorCode
        HanaIsODataProxy
        HanaParserTrace
        HealthCheckerTrace
        HiveErrorCode
        HiveParserHandleCoreObject
        HiveParserReaderBufferWaterMark
        HiveParserTestMode
        HiveParserTrace
        HttpAuthenticationType
        HttpCurlDebug
        HttpCurlVerbose
        HttpProxyHost
        HttpProxyPassword
        HttpProxyPort
        HttpProxyType
        HttpProxyUser
        IACTrace
        InMemoryTraceEnable
        InMemoryTraceBufferLimit
        IntTestsTrace
        InterchangeTrace
        JniTrace
        JsonTrace
        KeepAliveInterval
        KillCoreOnExit
        LDAPTrace
        LM_DEBUG
        LM_TRACE
        LastPacketsDump
        LastPacketsDumpMaxSize
        LastPacketsTrace
        LdapAlwaysTrustServerCertificate
        LdapLoginCacheTimeout
        LdapMappingRequireClientSideSSL
        LdapNetworkTimeout
        LeaksTrace
        LibpqEnable
        LicenseTrace
        LoadOracleUsers
        LogDeletePeriod
        LogNumberTextWidth
        LogSwitchPeriod
        LogSwitchSize
        LogToStdout
        LogToSyslog
        LogTotalSizeBackend
        LogTotalSizeCore
        LoginCheckIPChanges
        LoginFailedAttemptsNumber
        LoginFailedAttemptsTimeoutSeconds
        LoginFailedPeriodOfMsgSendingSeconds
        LoginPasswordExpirationDays
        LogsDiscFreeSpaceLimit
        LogsFolder
        MailAlternativeHostname
        MailCurlDebug
        MailCurlVerbose
        MailCustomUserAgent
        MailEnableTCPNoDelay
        MailReplaceLForCRtoCRLF
        MailUseAlternativeHostname
        MailUseCustomUserAgent
        MailUseUserAgent
        MariaDBErrorCode
        MarkOracleSession
        MaxBackendMemory
        MaxBackendMemoryForTerminate
        MaxCoreMemory
        MaxCoreMemoryForTerminate
        MaxDeferredPacketsForParsing
        MaxEventsInSubscriberEmail
        MaxExecutionsAuditForOperationPerMinute
        MaxFirewallBackupCount
        MaxNotResendedPacketInterval
        MaxSaveRowsCount
        MaxUncommittedProxyRead
        MessageHandlerConnectionsDistributeByHost
        MessageHandlerMainQueueUseThreads
        MessageHandlerProxyThreads
        MessageHandlerQueueFillPercentWarning
        MessageHandlerSleepTime
        MessageHandlerSnifferThreads
        MessageHandlerThreadMaxCycleGap
        MessageHandlerThreadStackSize
        MessageHandlerThreadsPriority
        MessageHandlersGlobalQueueHighWaterMark
        MessageHandlersGlobalQueueLowWaterMark
        MessageHandlersLocalQueueHighWaterMark
        MessageHandlersLocalQueueLowWaterMark
        MetadataCacheFillStatementTrace
        MetadataCacheTrace
        MetadataCacheVerboseTrace
        MongoBsonSizeThreshold
        MongoParserTrace
        MsSqlCipher
        MsSqlDelayedPacketsLimit
        MsSqlMARSProxyEnable
        MsSqlMarsConnectionsReadByFrame
        MsSqlMetadataSeparateLoading
        MsSqlMinFrameNo
        MsSqlParserStateTrace
        MsSqlParserTrace
        MsSqlRedirectsDisable
        MsSqlSSLDisable
        MsSqlSSLVersion
        MsSqlSubTrace
        MsgHandlerProcessPacketTrace
        MsgHandlerSvcTrace
        MySQLAuthMappingMethodsResolver
        MySQLConnectorEnable
        MySQLConnectorEnableClearTextPlugin
        MySQLConnectorUseCompression
        MySQLDisableDCLHandling
        MySQLErrorCode
        MySQLMetadataPrefetchRows
        MySQLMetadataTransactionIsolationLevel
        MySQLParserTrace
        MySQLUseAuthGSSAPIMethodForMapping
        NetezzaBackendLoginTimeout
        NetezzaErrorCode
        NetezzaParserDataFlushPeriod
        NetezzaParserKerberosContinueAuthWhenError
        NetezzaParserPacketBufferInitSize
        NetezzaParserPacketBufferWatermark
        NetezzaParserSSLMode
        NetezzaParserSkipRequestWhenParsingImpossible
        NetezzaParserTrace
        OAuth2URLForJsonWebKeys
        OEMCodePage
        OnDictionaryBackupDoneCommand
        OnOldLogDeleteCommand
        OpenSSLCipherList
        OperationGroupCacheSize
        OperationGroupLenMax
        OperationGroupMergePeriod
        OracleEnablePreparsing
        OracleErrorCode
        OracleParserTrace
        OraclePreparedStatementMaskingMethod
        OracleUseDAFObjectsTable
        ParserAssertAction
        ParserDebugMode
        PcapBufferSize
        PcapConversationFilter
        PcapMaxOutOfOrderMonitor
        PcapMaxOutOfOrderSegmentCount
        PcapMaxSessionIdleTime
        PcapShowOnlyFileName
        PcapShowProgressBySize
        PcapTrace
        PcapUnprocessedSegmentTrace
        PostgreErrorCode
        PostgreHandlerTrace
        PostgreParserHandleCoreObject
        PostgreParserPrepareStmtBlockingFullBatch
        PostgreParserRequireSessionMetadata
        PostgreParserSSLMode
        PostgreParserTestMode
        PostgreParserTrace
        PostgreParserTransparentKerberosAuthentication
        PostgreProtocolReaderBufferWatermark
        PrintCoreObjectsOnReachingVirtualMemory
        PrintCoreObjectsTimer
        ProactiveProxyThreads
        ProactorThreadQueueHighWatermark
        ProactorThreadQueueLowWatermark
        ProcessManagerTrace
        ProtocolPacketBuilderBufferSize
        ProxyConnectingTimeout
        ProxyConnectionCloseTimeout
        ProxyConnectionUseTcpNoDelay
        ProxyEventHookTrace
        ProxyForceStopTime
        ProxyInterfaceHostTimeToLive
        ProxyListenBacklog
        ProxyMaxConnections
        ProxyNoSessionNoticeTime
        ProxyPacketResendWarningTime
        ProxyThreadsPriority
        ProxyTrace
        QueryCacheEnableForOracle
        QueryCacheIgnorePattern
        QueryCacheSize
        QueryHistoryLearningTrace
        RDSFreeSpaceLimitAlert
        RDSFreeSpaceLimitStop
        ReactiveProxyQueueHighWatermark
        ReactiveProxyQueueLowWatermark
        ReactiveProxyThreads
        ReactorTaskQueueFillPercentWarning
        ReactorThreadQueueHighWatermark
        ReactorThreadQueueLowWatermark
        ReadOracleNamedTypeFields
        RecognizerParserDetail
        RecognizerParserTrace
        RecognizerTreeTrace
        RedShiftBackendUsePostgreODBC
        RedShiftErrorCode
        RedirectOnPublic
        RedshiftParserHandleCoreObject
        RedshiftParserRequireSessionMetadata
        RedshiftParserSSLMode
        RedshiftParserTestMode
        RedshiftProtocolReaderBufferWatermark
        ReportColumnMaxSize
        ReportsFolder
        RequiredFreeSpaceForFirewallBackup
        RequiredFreeSpaceForUpdate
        ResetClientConnections
        ResetServerConnections
        ResolveRelationshipTypesInQHL
        RowCacheEnable
        RowCacheFetchCount
        RowCacheMaxRowCount
        RowCacheMaxSize
        RowCacheMinRowCount
        RowCacheRequestRowCount
        RuleBlockedMessage
        RulesTrace
        S3HandlerTrace
        S3MaskingPartialResend
        S3ParserTrace
        SMUXCodeTrace
        SMUXTimeout
        SMUXTrace
        SSLCtxOptions
        SSLParserTrace
        SSLResumeTimeout
        SSOTrace
        SaveDsOriginalTable
        SavePassword
        SendDumpPeriod
        SendDumpToServer
        SendSecurityMsgToAdmins
        SessionIdleDisconnectTime
        SessionIdleWakeTime
        SessionIdleWarningTime
        SetupWizardIsDone
        ShowEncryptionSettings
        ShowOldAuditEvents
        SingleThreadProcessing
        SkipExecuteParsingInProcedure
        SkipRoutineDdlQueryMasking
        SnmpAuditFreeSpaceOIDSuffix
        SnmpAuditQueueLengthOIDSuffix
        SnmpAverageExecutionsOIDSuffix
        SnmpAverageOperationsOIDSuffix
        SnmpAverageReadBytesOIDSuffix
        SnmpAverageValueOIDSuffix
        SnmpAverageWriteBytesOIDSuffix
        SnmpBackendMemoryOIDSuffix
        SnmpCoreMemoryOIDSuffix
        SnmpLogsFreeSpaceOIDSuffix
        SnmpMailerQueueLengthOIDSuffix
        SnmpMemoryObjectOIDSuffix
        SnmpObjectidOIDSuffix
        SnmpProxyQueueLengthOIDSuffix
        SnmpQueueLenOIDSuffix
        SnmpSnifferQueueLengthOIDSuffix
        SnowflakeParserTrace
        SnowflakeUseODBC
        SpamEventHidingPeriod
        SqlRecognizerQuietMode
        SqlRecognizerUsesRecursion
        SslCacheCheckInterval
        SslDBCacheTimeout
        SslMEMCacheTimeout
        StartDayOfWeek
        StaticMaskingOTLBufferRowsCount
        StaticMaskingOtlLongSize
        StaticMaskingParallelLoadThreadsCount
        StaticMaskingTrace
        StaticMaskingTraceWithData
        StaticMaskingTriesToCreateAll
        StatisticFlushPeriod
        StatisticRemoveFrequency
        StatisticRemoveLatency
        StrictCheckRpc
        StrictChildProcessCheck
        SubscriberAWSCloudWatchEventTemplate
        SubscriberAWSCloudWatchGeneralTemplate
        SubscriberCommonErrorBasedRuleTriggeredPlainTemplate
        SubscriberCommonRuleTriggeredPlainTemplate
        SubscriberCommonSessionRuleTriggeredPlainTemplate
        SubscriberExternalDebug
        SubscriberExternalErrorFilename
        SubscriberExternalInputFilename
        SubscriberExternalOutputFilename
        SubscriberJiraCurlDebug
        SubscriberJiraCurlVerbose
        SubscriberJiraCustomUserAgent
        SubscriberJiraEnableTCPNoDelay
        SubscriberJiraUseCustomUserAgent
        SubscriberJiraUseUserAgent
        SubscriberMaxMsgSqlSize
        SubscriberRedmineCurlDebug
        SubscriberRedmineCurlVerbose
        SubscriberRedmineCustomUserAgent
        SubscriberRedmineEnableTCPNoDelay
        SubscriberRedmineUseCustomUserAgent
        SubscriberRedmineUseUserAgent
        SubscriberSMTPAlternativeHostname
        SubscriberSMTPCurlDebug
        SubscriberSMTPCurlVerbose
        SubscriberSMTPCustomUserAgent
        SubscriberSMTPEnableTCPNoDelay
        SubscriberSMTPReplaceLForCRtoCRLF
        SubscriberSMTPUseAlternativeHostname
        SubscriberSMTPUseCustomUserAgent
        SubscriberSMTPUseUserAgent
        SubscriberSNMPEventTemplate
        SubscriberSNMPGeneralTemplate
        SubscriberServiceNowCurlDebug
        SubscriberServiceNowCurlVerbose
        SubscriberServiceNowCustomUserAgent
        SubscriberServiceNowEnableTCPNoDelay
        SubscriberServiceNowUseCustomUserAgent
        SubscriberServiceNowUseUserAgent
        SubscriberSlackDirectCurlDebug
        SubscriberSlackDirectCurlVerbose
        SubscriberSlackDirectCustomUserAgent
        SubscriberSlackDirectEnableTCPNoDelay
        SubscriberSlackDirectUseCustomUserAgent
        SubscriberSlackDirectUseUserAgent
        SubscriberSlackTokenCurlDebug
        SubscriberSlackTokenCurlVerbose
        SubscriberSlackTokenCustomUserAgent
        SubscriberSlackTokenEnableTCPNoDelay
        SubscriberSlackTokenUseCustomUserAgent
        SubscriberSlackTokenUseUserAgent
        SubscriberZendeskCurlDebug
        SubscriberZendeskCurlVerbose
        SubscriberZendeskCustomUserAgent
        SubscriberZendeskEnableTCPNoDelay
        SubscriberZendeskUseCustomUserAgent
        SubscriberZendeskUseUserAgent
        SybaseErrorCode
        SybaseErrorProcName
        SyslogProtocolType
        SyslogRemoteHost
        SyslogRemotePort
        SyslogTrace
        SystemBackupDictionaryEnable
        SystemBackupDictionaryTimeInterval
        SystemBackupDictionaryTrace
        SystemCharset
        TFATrace
        TaskGuardianCancelTimeout
        TaskManagerThreadMaxCycleGap
        TaskManagerTrace
        TaskSchedulerTrace
        TaskStopTime
        TbuildMaxSessions
        TbuildNoRestoreIfError
        TbuildPreferUpdateOperatorForAppend
        TbuildSaveArtefacts
        TempPath
        TemporaryCachedFileLiveTime
        TemporaryProxyDefaultPort
        TemporaryProxyHost
        TeradataDebugSniffer
        TeradataErrorCode
        TeradataParserTrace
        TfaIntervalBetweenMailRequest
        TfaLinksValidationTimeout
        TfaMailContentTemplate
        TfaMailSubject
        TfaValidatedLinksTimeout
        ThriftParserTrace
        Timeout
        TrafficBufferPoolVolume
        TrafficBuilderTrace
        TrailAuditTrace
        TrailDBNumberOfLines
        TrailDBSkipEventsFromDS
        TrailDbPerformViaREST
        TrailDbSessionTimeout
        TrapAuditErrorOIDSuffix
        TrapAuthenticationOIDSuffix
        TrapBackendEventsOIDSuffix
        TrapConfigurationChangesOIDSuffix
        TrapCoreEventOIDSuffix
        TrapErrorOIDSuffix
        TrapInfoOIDSuffix
        TrapMetadataChangesOIDSuffix
        TrapRuleTriggerOIDSuffix
        TrapWarningOIDSuffix
        UIType
        UpdateBlockedUsersPeriod
        UpdateConfigTrace
        UpdateLimitsPeriod
        UpdateMetadataCacheByQueries
        UpdateMetadataCommitPeriod
        UpdateMetadataCompletelyInTransaction
        UpdateMetadataLoadSystemObjects
        UpdateMetadataNotifyWorkers
        UpdateMetadataSleepAfterCommit
        UseCurrentSessionAndDatabaseName
        UseKerberosMappingUsingNativeAuthentication
        UseMetadataFunctionDDL
        UseMetadataViewDDL
        UsePerSessionMetadata
        UseProactiveProxy
        UseSimpleQueriesToAuditClean
        UserMappingCaseInsensitive
        UserMappingType
        ValidateEncryptionFunctions
        VerticaErrorCode
        VerticaHandlerTrace
        VerticaParserHandleCoreObject
        VerticaParserTestMode
        VerticaParserTrace
        VerticaProtocolReaderBufferWatermark
        WebLoadBalancerEnabled
        WebSessionTimeout
        WebThreadCount
        WorkersUpdatePeriod
        WriteLogDateTime
        pnFirewallCoreSigsegvLogName
    ''')
    parameters_list_sign = '\n%s\n' % '\n'.join([str + '=' for str in parameters_list.splitlines()[1:]])

    #
    #
    # REGEXPS
    # =================================================================================================================]
    re_parameter_name  = r'[\w]*='
    re_parameter_value = r'(?<==)[\w(-|\s)]*$'

    #
    #
    # CMDLINE FUNCTIONS
    # =================================================================================================================]
    show_parameters  = 'showParameters'
    change_parameter = 'changeParameter -name %s -value %s'

    #
    #
    # MESSAGES
    # =================================================================================================================]
    msg_tip_for_dev     = '\n' \
                          '\nProbably some new parameters were added. Please add new parameters to the test list.' \
                          '\nGo to "IntegrationTests/test_cmdline_commands/contexts/parameters_context.py" ' \
                          '\nand add new parameters to "parameters_list".' \
                          '\n'
