import { CliCommand } from './types.js';
import { enhanceParameterDescription } from '../description_helpers.js';

export const dbUserCommands: CliCommand[] = [
  {
    toolName: 'db_user_add',
    description: 'Adds a new database user definition to DataSunrise. This user should exist in the actual database.',
    baseCommand: 'addDbUser',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Name of the database user as it exists in the database.'), required: true, cliName: '-name' },
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the DataSunrise instance this user belongs to, or "any".'), required: false, cliName: '-instance' },
      { name: 'dbType', type: 'string', description: enhanceParameterDescription('string', '(aurora mysql | aurora postgresql | db2 | greenplum | hive | mariadb | mysql | mssql | netezza | oracle | postgresql | redshift | teradata | sap hana | s3 | vertica | mongodb | dynamodb | impala | cassandra | neo4j | sybase | snowflake | <any>)'), required: false, cliName: '-dbType' },
    ],
    category: 'Database User',
  },
  {
    toolName: 'db_user_group_add',
    description: 'Adds a new group for database users. Members should be existing DB users defined in DataSunrise.',
    baseCommand: 'addDbUserGr',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for the new group of database users.'), required: true, cliName: '-name' },
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Associated instance name or "any".'), required: false, cliName: '-instance' },
      { name: 'dbType', type: 'string', description: enhanceParameterDescription('string', '(aurora mysql | aurora postgresql | db2 | greenplum | hive | mariadb | mysql | mssql | netezza | oracle | postgresql | redshift | teradata | sap hana | s3 | vertica | mongodb | dynamodb | impala | cassandra | neo4j | sybase | snowflake | <any>)'), required: false, cliName: '-dbType' },
      { name: 'addMembers', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated list of existing DB user names to add as members.', 'LIST'), required: false, cliName: '-addMembers' },
    ],
    category: 'Database User',
  },
  {
    toolName: 'db_user_mapping_add',
    description: 'Adds an Active Directory User/Group to Database User mapping for a specific instance. (CLI Guide 20.4)',
    baseCommand: 'addDbUserMapping',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the DataSunrise instance for this mapping.'), required: true, cliName: '-instance' },
      { name: 'adLogin', type: 'string', description: enhanceParameterDescription('string', 'Active Directory login name. Either this or adGroup is required.'), required: false, cliName: '-adLogin' },
      { name: 'adGroup', type: 'string', description: enhanceParameterDescription('string', 'Active Directory group name. Either this or adLogin is required.'), required: false, cliName: '-adGroup' },
      { name: 'dbLogin', type: 'string', description: enhanceParameterDescription('string', 'Database login name to map to.'), required: true, cliName: '-dbLogin' },
      { name: 'dbPassword', type: 'string', description: enhanceParameterDescription('string', 'Password of the database user (for hash generation/verification).'), required: true, cliName: '-dbPassword' },
      { name: 'ldapServer', type: 'string', description: enhanceParameterDescription('string', 'Name of a pre-configured LDAP Server in DataSunrise. Uses default if omitted.'), required: false, cliName: '-ldapServer' },
      { name: 'hashType', type: 'string', description: enhanceParameterDescription('string', 'HashType (MD5 | SHA-256 | SHA-512 | crypt | SHA-1).', 'ENUM'), required: false, cliName: '-hashType' },
      { name: 'adminLogin', type: 'string', description: enhanceParameterDescription('string', 'User login to access the database where the salt for the user is stored (only for SHA-***).'), required: false, cliName: '-adminLogin' },
      { name: 'adminPassword', type: 'string', description: enhanceParameterDescription('string', 'User password to access the database where salt for the user is stored (only for SHA-***).'), required: false, cliName: '-adminPassword' },
      { name: 'sysDba', type: 'boolean', description: enhanceParameterDescription('boolean', 'For Oracle SHA512: connect as SYSDBA to retrieve salt.', undefined, false), required: false, cliName: '-sysDba' },
    ],
    category: 'Database User',
  },
  {
    toolName: 'ldap_server_add',
    description: 'Adds a new LDAP server configuration to DataSunrise. (CLI Guide 20.2)',
    baseCommand: 'addLdapServer',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical name for the LDAP server configuration.'), required: true, cliName: '-name' },
      { name: 'host', type: 'string', description: enhanceParameterDescription('string', 'LDAP server host.', 'HOSTNAME_OR_IP'), required: true, cliName: '-host' },
      { name: 'port', type: 'string', description: enhanceParameterDescription('string', 'LDAP server port number.', 'PORT'), required: true, cliName: '-port' },
      { name: 'baseDn', type: 'string', description: enhanceParameterDescription('string', 'Base Distinguished Name (DN) for LDAP searches.'), required: true, cliName: '-baseDn' },
      { name: 'default', type: 'string', description: enhanceParameterDescription('string', 'Use the current LDAP server as a default one (true | false).'), required: false, cliName: '-default' },
      { name: 'awsSmID', type: 'string', description: enhanceParameterDescription('string', 'AWS Secrets Manager ID.'), required: false, cliName: '-awsSmID' },
      { name: 'azureKeyVault', type: 'string', description: enhanceParameterDescription('string', 'MS Azure Key Vault.'), required: false, cliName: '-azureKeyVault' },
      { name: 'azureSecretName', type: 'string', description: enhanceParameterDescription('string', 'MS Azure Secret Name.'), required: false, cliName: '-azureSecretName' },
      { name: 'cyberArkFolder', type: 'string', description: enhanceParameterDescription('string', 'CyberArk folder.'), required: false, cliName: '-cyberArkFolder' },
      { name: 'cyberArkObject', type: 'string', description: enhanceParameterDescription('string', 'CyberArk object.'), required: false, cliName: '-cyberArkObject' },
      { name: 'cyberArkSafe', type: 'string', description: enhanceParameterDescription('string', 'CyberArk safe.'), required: false, cliName: '-cyberArkSafe' },
      { name: 'domain', type: 'string', description: enhanceParameterDescription('string', 'LDAP server domain.'), required: false, cliName: '-domain' },
      { name: 'groupAttr', type: 'string', description: enhanceParameterDescription('string', 'Group attribute.'), required: false, cliName: '-groupAttr' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'LDAP login.'), required: false, cliName: '-login' },
      { name: 'loginAttr', type: 'string', description: enhanceParameterDescription('string', 'Login Attribute.'), required: false, cliName: '-loginAttr' },
      { name: 'loginCustomFormat', type: 'string', description: enhanceParameterDescription('string', 'Login Custom Format.'), required: false, cliName: '-loginCustomFormat' },
      { name: 'loginType', type: 'string', description: enhanceParameterDescription('string', 'Login Type (Custom | Microsoft Active Directory | Open LDAP | Directory Server | Apache Directory Studio).', 'ENUM'), required: false, cliName: '-loginType' },
      { name: 'mailAttr', type: 'string', description: enhanceParameterDescription('string', 'Email Attribute.'), required: false, cliName: '-mailAttr' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'LDAP password.'), required: false, cliName: '-password' },
      { name: 'roleARN', type: 'string', description: enhanceParameterDescription('string', 'Role ARN.'), required: false, cliName: '-roleARN' },
      { name: 'savePassword', type: 'string', description: enhanceParameterDescription('string', 'Password storage type: ds | ca | awssm | azurekv.', 'ENUM'), required: false, cliName: '-savePassword' },
      { name: 'ssl', type: 'string', description: enhanceParameterDescription('string', 'Use SSL for connection (true | false).'), required: false, cliName: '-ssl' },
      { name: 'userFilter', type: 'string', description: enhanceParameterDescription('string', 'User filter.'), required: false, cliName: '-userFilter' },
      { name: 'caseSensitive', type: 'string', description: enhanceParameterDescription('string', 'LDAP server is case sensitive to usernames (true | false).'), required: false, cliName: '-caseSensitive' },
    ],
    category: 'Database User',
  },
  {
    toolName: 'db_user_update',
    description: "Updates an existing database user's name or properties. (CLI Guide 9.7)",
    baseCommand: 'updateDbUser',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the database user.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'New name for the database user.'), required: false, cliName: '-newName' },
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance name: <instance name> | any.'), required: false, cliName: '-instance' },
      { name: 'dbType', type: 'string', description: enhanceParameterDescription('string', '(aurora mysql | aurora postgresql | db2 | greenplum | hive | mariadb | mysql | mssql | netezza | oracle | postgresql | redshift | teradata | sap hana | s3 | vertica | mongodb | dynamodb | impala | cassandra | neo4j | sybase | snowflake | <any>)'), required: false, cliName: '-dbType' },
    ],
    category: 'Database User',
  },
  {
    toolName: 'db_user_group_update',
    description: "Updates an existing database user group's name or members. (CLI Guide 9.8)",
    baseCommand: 'updateDbUserGr',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the database user group.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'New name for the group.'), required: false, cliName: '-newName' },
      { name: 'addMembers', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated list of DB user names to add.', 'LIST'), required: false, cliName: '-addMembers' },
      { name: 'removeMembers', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated list of DB user names to remove.', 'LIST'), required: false, cliName: '-removeMembers' },
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance name: <instance name> | any.'), required: false, cliName: '-instance' },
      { name: 'dbType', type: 'string', description: enhanceParameterDescription('string', '(aurora mysql | aurora postgresql | db2 | greenplum | hive | mariadb | mysql | mssql | netezza | oracle | postgresql | redshift | teradata | sap hana | s3 | vertica | mongodb | dynamodb | impala | cassandra | neo4j | sybase | snowflake | <any>)'), required: false, cliName: '-dbType' },
    ],
    category: 'Database User',
  },
  {
    toolName: 'ldap_server_update',
    description: "Updates an existing LDAP server's configuration. (CLI Guide 20.3)",
    baseCommand: 'updateLdapServer',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the LDAP server.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'New name for the LDAP server.'), required: false, cliName: '-newName' },
      { name: 'host', type: 'string', description: enhanceParameterDescription('string', 'LDAP server host.', 'HOSTNAME_OR_IP'), required: false, cliName: '-host' },
      { name: 'port', type: 'string', description: enhanceParameterDescription('string', 'LDAP server port number.', 'PORT'), required: false, cliName: '-port' },
      { name: 'baseDn', type: 'string', description: enhanceParameterDescription('string', 'Database DN.'), required: false, cliName: '-baseDn' },
      { name: 'default', type: 'string', description: enhanceParameterDescription('string', 'Use the current LDAP server as a default one (true | false).'), required: false, cliName: '-default' },
      { name: 'awsSmID', type: 'string', description: enhanceParameterDescription('string', 'AWS Secrets Manager ID.'), required: false, cliName: '-awsSmID' },
      { name: 'azureKeyVault', type: 'string', description: enhanceParameterDescription('string', 'MS Azure Key Vault.'), required: false, cliName: '-azureKeyVault' },
      { name: 'azureSecretName', type: 'string', description: enhanceParameterDescription('string', 'MS Azure Secret Name.'), required: false, cliName: '-azureSecretName' },
      { name: 'cyberArkFolder', type: 'string', description: enhanceParameterDescription('string', 'CyberArk folder.'), required: false, cliName: '-cyberArkFolder' },
      { name: 'cyberArkObject', type: 'string', description: enhanceParameterDescription('string', 'CyberArk object.'), required: false, cliName: '-cyberArkObject' },
      { name: 'cyberArkSafe', type: 'string', description: enhanceParameterDescription('string', 'CyberArk safe.'), required: false, cliName: '-cyberArkSafe' },
      { name: 'domain', type: 'string', description: enhanceParameterDescription('string', 'LDAP server domain.'), required: false, cliName: '-domain' },
      { name: 'groupAttr', type: 'string', description: enhanceParameterDescription('string', 'Group attribute.'), required: false, cliName: '-groupAttr' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'LDAP login.'), required: false, cliName: '-login' },
      { name: 'loginAttr', type: 'string', description: enhanceParameterDescription('string', 'Login Attribute.'), required: false, cliName: '-loginAttr' },
      { name: 'loginCustomFormat', type: 'string', description: enhanceParameterDescription('string', 'Login Custom Format.'), required: false, cliName: '-loginCustomFormat' },
      { name: 'loginType', type: 'string', description: enhanceParameterDescription('string', 'Login Type (Custom | Microsoft Active Directory | Open LDAP | Directory Server | Apache Directory Studio).', 'ENUM'), required: false, cliName: '-loginType' },
      { name: 'mailAttr', type: 'string', description: enhanceParameterDescription('string', 'Email Attribute.'), required: false, cliName: '-mailAttr' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'LDAP password.'), required: false, cliName: '-password' },
      { name: 'roleARN', type: 'string', description: enhanceParameterDescription('string', 'Role ARN.'), required: false, cliName: '-roleARN' },
      { name: 'savePassword', type: 'string', description: enhanceParameterDescription('string', 'Password storage type: ds | ca | awssm | azurekv.', 'ENUM'), required: false, cliName: '-savePassword' },
      { name: 'ssl', type: 'string', description: enhanceParameterDescription('string', 'Use SSL for connection (true | false).'), required: false, cliName: '-ssl' },
      { name: 'userFilter', type: 'string', description: enhanceParameterDescription('string', 'User filter.'), required: false, cliName: '-userFilter' },
    ],
    category: 'Database User',
  },
  { toolName: 'db_user_show_all', description: 'Displays all database users defined in DataSunrise.', baseCommand: 'showDbUsers', params: [], category: 'Database User' },
  {
    toolName: 'db_user_show_one', description: 'Shows detailed information for a specific database user.', baseCommand: 'showDbUser',
    params: [{ name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Name of the database user to display.'), required: true, cliName: '-name' }],
    category: 'Database User',
  },
  { toolName: 'db_user_group_show_all', description: 'Displays all database user groups.', baseCommand: 'showDbUserGroups', params: [], category: 'Database User' },
  {
    toolName: 'db_user_group_show_one', description: 'Shows detailed information for a specific database user group.', baseCommand: 'showDbUserGr',
    params: [{ name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Name of the database user group to display.'), required: true, cliName: '-name' }],
    category: 'Database User',
  },
  {
    toolName: 'db_user_mapping_show', description: 'Shows AD to DB user mappings for a specific instance.', baseCommand: 'showAdDbUserMapping',
    params: [{ name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance for which to show mappings.'), required: true, cliName: '-instance' }],
    category: 'Database User',
  },
  { toolName: 'ldap_server_show_all', description: 'Displays all configured LDAP servers.', baseCommand: 'showLdapServers', params: [], category: 'Database User' },
  {
    toolName: 'ldap_server_show_one', description: 'Shows detailed information for a specific LDAP server.', baseCommand: 'showLdapServer',
    params: [{ name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Name of the LDAP server to display.'), required: true, cliName: '-name' }],
    category: 'Database User',
  },
  {
    toolName: 'update_auth_mapping_config',
    description: 'Enable/disable mapping Active Directory users to Database users.',
    baseCommand: 'updateAuthMappingConfig',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance Name'), required: true, cliName: '-instance' },
      { name: 'enabled', type: 'string', description: enhanceParameterDescription('string', 'Enable/disable mapping: true/false'), required: false, cliName: '-enabled' },
      { name: 'mapType', type: 'string', description: enhanceParameterDescription('string', 'Mapping Type: config, file, db.', 'ENUM'), required: true, cliName: '-mapType' },
      { name: 'mapProtocol', type: 'string', description: enhanceParameterDescription('string', 'User mapping protocol type: Kerberos / LDAP', 'ENUM'), required: false, cliName: '-mapProtocol' },
      { name: 'accOnlyMapUsers', type: 'string', description: enhanceParameterDescription('string', 'Accept only mapped users: true/false'), required: false, cliName: '-accOnlyMapUsers' },
      { name: 'clientSideSSL', type: 'string', description: enhanceParameterDescription('string', 'Require client side SSL for LDAP mapping: true/false'), required: false, cliName: '-clientSideSSL' },
      { name: 'file', type: 'string', description: enhanceParameterDescription('string', 'File Name. Only for -mapType:file', 'FILE_PATH'), required: false, cliName: '-file' },
      { name: 'dbHost', type: 'string', description: enhanceParameterDescription('string', 'Database host. Only for -mapType:db', 'HOSTNAME_OR_IP'), required: false, cliName: '-dbHost' },
      { name: 'dbPort', type: 'string', description: enhanceParameterDescription('string', 'Database port. Only for -mapType:db', 'PORT'), required: false, cliName: '-dbPort' },
      { name: 'database', type: 'string', description: enhanceParameterDescription('string', 'Database name. Only for -mapType:db'), required: false, cliName: '-database' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'Database user login. Only for -mapType:db'), required: false, cliName: '-login' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'Database user password. Only for -mapType:db'), required: false, cliName: '-password' },
      { name: 'dbType', type: 'string', description: enhanceParameterDescription('string', '(greenplum | netezza | vertica | postgresql | redshift)', 'ENUM'), required: false, cliName: '-dbType' },
    ],
    category: 'Database User',
  },
  {
    toolName: 'db_user_mapping_disable', description: 'Disables AD to DB user mapping for an instance. (CLI Guide 20.10)', baseCommand: 'disableDbUserMapping',
    params: [{ name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance for which to disable mapping.'), required: true, cliName: '-instance' }],
    category: 'Database User',
  },
  {
    toolName: 'db_user_delete', description: 'Deletes a database user definition from DataSunrise.', baseCommand: 'delDbUser',
    params: [{ name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Name of the database user to delete.'), required: true, cliName: '-name' }],
    category: 'Database User',
  },
  {
    toolName: 'db_user_group_delete', description: 'Deletes a database user group.', baseCommand: 'delDbUserGr',
    params: [{ name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Name of the database user group to delete.'), required: true, cliName: '-name' }],
    category: 'Database User',
  },
  {
    toolName: 'db_user_mapping_delete', description: 'Deletes an AD to DB user mapping. (CLI Guide 20.8)', baseCommand: 'delDbUserMapping',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance from which to delete the mapping.'), required: true, cliName: '-instance' },
      { name: 'adLogin', type: 'string', description: enhanceParameterDescription('string', 'AD login of the mapping to delete.'), required: false, cliName: '-adLogin' }, // adLogin or adGroup is needed
      { name: 'adGroup', type: 'string', description: enhanceParameterDescription('string', 'Active Directory group of the mapping to delete.'), required: false, cliName: '-adGroup' },
      { name: 'ldapServer', type: 'string', description: enhanceParameterDescription('string', 'LDAP server name associated with the mapping.'), required: false, cliName: '-ldapServer' },
    ],
    category: 'Database User',
  },
  {
    toolName: 'ldap_server_delete', description: 'Deletes an LDAP server configuration.', baseCommand: 'delLdapServer',
    params: [{ name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Name of the LDAP server to delete.'), required: true, cliName: '-name' }],
    category: 'Database User',
  },
];
