import { CliCommand } from './types.js';
import { enhanceParameterDescription } from '../description_helpers.js';

export const instanceCommands: CliCommand[] = [
  {
    toolName: 'instance_add_plus',
    description: 'Adds a new database instance along with its network interface and an initial monitoring method (Proxy, Sniffer, or Log Trailing). This is a comprehensive setup command. (CLI Guide 4.2)',
    baseCommand: 'addInstancePlus',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical name of the Instance, for internal purposes only'), required: true, cliName: '-name' },
      { name: 'dbType', type: 'string', description: enhanceParameterDescription('string', '(athena | aurora mysql | aurora postgresql | bigquery | cassandra | db2 | dynamodb | elasticsearch | greenplum | hive | impala | informix | mariadb | mongodb | mssql | mysql | netezza | neo4j | oracle | postgresql | redshift | sap hana | s3 | sybase | snowflake | teradata | vertica)'), required: true, cliName: '-dbType' },
      { name: 'dbHost', type: 'string', description: enhanceParameterDescription('string', 'Database host', 'HOSTNAME'), required: true, cliName: '-dbHost' },
      { name: 'dbPort', type: 'string', description: enhanceParameterDescription('string', 'Database port', 'PORT'), required: true, cliName: '-dbPort' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'Database user login. Can be used as Access Key for AWS databases. Enter Service Account Email for BigQuery.'), required: true, cliName: '-login' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'Database user password. Can be used as Secret Key for AWS databases. Enter RSA Private Key for BigQuery.'), required: true, cliName: '-password' },
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance name for Oracle'), required: false, cliName: '-instance' },
      { name: 'database', type: 'string', description: enhanceParameterDescription('string', 'Database name for DB2, Greenplum, Hive, MSSQL, Netezza, PostgreSQL, Aurora PostgreSQL, Redshift, Teradata, MongoDB, SAP HANA, Vertica, Impala, Sybase. Project ID for BigQuery'), required: false, cliName: '-database' },
      { name: 'account', type: 'string', description: enhanceParameterDescription('string', 'Cloud account name for Snowflake'), required: false, cliName: '-account' },
      { name: 'awsRegion', type: 'string', description: enhanceParameterDescription('string', 'AWS Region for DynamoDB, Athena, Aurora PostgreSQL, Aurora MySQL, ElasticSearch, PostgreSQL, MySQL'), required: false, cliName: '-awsRegion' },
      { name: 'queryResultLocation', type: 'string', description: enhanceParameterDescription('string', 'Query result location for Amazon Athena', 'URI'), required: false, cliName: '-queryResultLocation' },
      { name: 'serverName', type: 'string', description: enhanceParameterDescription('string', 'Server name for Informix multi-session support'), required: false, cliName: '-serverName' },
      { name: 'protocolType', type: 'string', description: enhanceParameterDescription('string', 'Protocol type for MySQL-like databases, S3, Athena: Usual | HTTP | XProtocol | HTTP Proxy'), required: false, cliName: '-protocolType' },
      { name: 'metadataRetrievalMethod', type: 'string', description: enhanceParameterDescription('string', 'Metadata retrieval method: Regular/Via Stored Procedures'), required: false, cliName: '-metadataRetrievalMethod' },
      { name: 'savePassword', type: 'string', description: enhanceParameterDescription('string', 'Password storage type: no | ds | ca | awssm | azurekv'), required: false, cliName: '-savePassword', defaultValue: 'ds' },
      { name: 'mode', type: 'string', description: enhanceParameterDescription('string', 'Add Proxy, Sniffer, Trailing or Nothing: Proxy || Sniffer || Trailing || No'), required: true, cliName: '-mode' },
      { name: 'proxyHost', type: 'string', description: enhanceParameterDescription('string', 'Open proxy on the host', 'HOSTNAME_OR_IP'), required: false, defaultValue: '0.0.0.0', cliName: '-proxyHost' },
      { name: 'proxyPort', type: 'string', description: enhanceParameterDescription('string', 'Open proxy on the port', 'PORT'), required: false, defaultValue: '5432', cliName: '-proxyPort' },
      { name: 'snifferDevice', type: 'string', description: enhanceParameterDescription('string', 'Sniff the network interface. Only several first letters of the Interface are permitted'), required: false, cliName: '-snifferDevice' },
      { name: 'period', type: 'string', description: enhanceParameterDescription('string', 'Periodicity of request data (seconds)'), required: false, cliName: '-period' },
      { name: 'formatType', type: 'string', description: enhanceParameterDescription('string', 'Format type: Database | XML | CSV | JSON'), required: false, cliName: '-formatType' },
      { name: 'connectType', type: 'string', description: enhanceParameterDescription('string', 'Source of log files: AWS | SMB | Local Folder | Oracle Package | Azure | BigQuery'), required: false, cliName: '-connectType' },
      { name: 'sysDba', type: 'boolean', description: enhanceParameterDescription('boolean', 'Connect to Oracle as sysdba (Oracle specific, optional)'), required: false, cliName: '-sysDba' },
      { name: 'allowDuplicates', type: 'boolean', description: enhanceParameterDescription('boolean', 'Allow to add an instance with the same host and port you have previously added to the console'), required: false, cliName: '-allowDuplicates' },
      { name: 'enableAgent', type: 'string', description: enhanceParameterDescription('string', 'Enable agent (true | false)'), required: false, cliName: '-enableAgent' },
      { name: 'dsServer', type: 'string', description: enhanceParameterDescription('string', 'Server name where proxy is opened or sniffer is used'), required: false, cliName: '-dsServer' },
      { name: 'ssl', type: 'boolean', description: enhanceParameterDescription('boolean', 'Use SSL when connecting to the Database.'), required: false, cliName: '-ssl' },
      { name: 'keyGroupName', type: 'string', description: enhanceParameterDescription('string', 'Name of the group of Certificates for client'), required: false, cliName: '-keyGroupName' },
      { name: 'dbKeyGroupName', type: 'string', description: enhanceParameterDescription('string', 'Name of the group of Certificates for database'), required: false, cliName: '-dbKeyGroupName' },
      { name: 'acceptSslConnectionsOnly', type: 'string', description: enhanceParameterDescription('string', 'Accept only SSL connections (true | false)'), required: false, cliName: '-acceptSslConnectionsOnly' },
      { name: 'awsSmID', type: 'string', description: enhanceParameterDescription('string', 'AWS Secrets Manager ID'), required: false, cliName: '-awsSmID' },
      { name: 'azureKeyVault', type: 'string', description: enhanceParameterDescription('string', 'Azure Key Vault'), required: false, cliName: '-azureKeyVault' },
      { name: 'azureSecretName', type: 'string', description: enhanceParameterDescription('string', 'Azure Secret Name'), required: false, cliName: '-azureSecretName' },
      { name: 'connString', type: 'string', description: enhanceParameterDescription('string', 'Custom connection string for Aurora PostgreSQL, Cassandra, DB2, Greenplum, Hive, Impala, Informix, MongoDB, MSSQL, Netezza, Oracle, PostgreSQL, Sybase, Redshift, SAP HANA, Snowflake, Teradata, Vertica'), required: false, cliName: '-connString' },
      { name: 'cyberArkFolder', type: 'string', description: enhanceParameterDescription('string', 'CyberArk Folder'), required: false, cliName: '-cyberArkFolder' },
      { name: 'cyberArkObject', type: 'string', description: enhanceParameterDescription('string', 'CyberArk Object'), required: false, cliName: '-cyberArkObject' },
      { name: 'cyberArkSafe', type: 'string', description: enhanceParameterDescription('string', 'CyberArk Safe'), required: false, cliName: '-cyberArkSafe' },
      { name: 'ipVersion', type: 'string', description: enhanceParameterDescription('string', 'IP version ( IPv4 | IPv6 | Auto ). Auto is a default value.'), required: false, cliName: '-ipVersion' },
      { name: 'roleARN', type: 'string', description: enhanceParameterDescription('string', 'Role ARN'), required: false, cliName: '-roleARN' },
      { name: 'verifyCA', type: 'string', description: enhanceParameterDescription('string', 'Verify CA (true | false)'), required: false, cliName: '-verifyCA' },
      { name: 'tableRelations', type: 'string', description: enhanceParameterDescription('string', 'Search for table relations and include them in the default target database\'s relation (true | false)'), required: false, cliName: '-tableRelations' },
      { name: 'envAutoCreate', type: 'string', description: enhanceParameterDescription('string', 'Automatically Create Environment. Available for following databases: MariaDB, Aurora MySQL, Oracle, Aurora PostgreSQL, PostgreSQL, Redshift, Greenplum, MSSQL.'), required: false, cliName: '-envAutoCreate' },
      { name: 'envName', type: 'string', description: enhanceParameterDescription('string', 'Environment Name. Available for following databases: MariaDB, Aurora MySQL, BigQuery, Oracle, Aurora PostgreSQL, PostgreSQL, Redshift, Greenplum, MSSQL.'), required: false, cliName: '-envName' },
      { name: 'hostFQDN', type: 'string', description: enhanceParameterDescription('string', 'Kerberos Host FQDN for Hive, Impala'), required: false, cliName: '-hostFQDN' },
      { name: 'kerberosName', type: 'string', description: enhanceParameterDescription('string', 'Kerberos service name'), required: false, cliName: '-kerberosName' },
      { name: 'kerberosRealm', type: 'string', description: enhanceParameterDescription('string', 'Kerberos Realm for Hive, Impala'), required: false, cliName: '-kerberosRealm' },
      { name: 'loginType', type: 'string', description: enhanceParameterDescription('string', 'Login Type: Without Authentication | Regular | Active Directory | IAM Role'), required: false, cliName: '-loginType' },
      { name: 'queryGroups2FA', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated list of query groups, queries of which are used to access the database when configuring 2FA'), required: false, cliName: '-queryGroups2FA' },
      { name: 'sid', type: 'boolean', description: enhanceParameterDescription('boolean', 'Connect to SID instead of the Service Name. By default connection to the Service Name is performed (Oracle specific, optional)'), required: false, cliName: '-sid' },
      { name: 'smbHost', type: 'string', description: enhanceParameterDescription('string', 'SMB server hostname or IP address (for trail mode with SMB connection)'), required: false, cliName: '-smbHost' },
      { name: 'smbLogin', type: 'string', description: enhanceParameterDescription('string', 'SMB username for authentication (for trail mode with SMB connection)'), required: false, cliName: '-smbLogin' },
      { name: 'smbPath', type: 'string', description: enhanceParameterDescription('string', "SMB share path, must end with '/' (for trail mode with SMB connection)"), required: false, cliName: '-smbPath' },
      { name: 'smbPwd', type: 'string', description: enhanceParameterDescription('string', 'SMB password for authentication (for trail mode with SMB connection)'), required: false, cliName: '-smbPwd' },
    ],
    dependencies: {
      dbType: {
        oneOf: [
          { properties: { dbType: { enum: ['ORACLE'] } }, required: ['instance'] },
          { properties: { dbType: { enum: ['SNOWFLAKE'] } }, required: ['account'] },
          { properties: { dbType: { enum: ['ATHENA'] } }, required: ['awsRegion', 'queryResultLocation'] },
          { properties: { dbType: { enum: ['INFORMIX'] } }, required: ['serverName', 'database'] },
          { properties: { dbType: { enum: ['DYNAMODB'] } }, required: ['awsRegion', 'database'] },
          { properties: { dbType: { enum: ['ELASTICSEARCH'] } }, required: ['awsRegion'] },
          { properties: { dbType: { enum: ['AURORAMYSQL'] } }, required: ['awsRegion', 'database'] },
          { properties: { dbType: { enum: ['AURORAPOSTGRESQL'] } }, required: ['awsRegion', 'database'] },
          {
            properties: {
              dbType: { enum: [
                'POSTGRESQL', 'MYSQL', 'MSSQL', 'MONGODB', 'HIVE', 'TERADATA',
                'GREENPLUM', 'MARIADB', 'REDSHIFT', 'SYBASE', 'DB2',
                'NETEZZA', 'VERTICA', 'HANA', 'IMPALA'
              ]}
            },
            required: ['database']
          },
          { // Default/fallback for other dbTypes not explicitly requiring instance/database/account etc.
            properties: {
              dbType: {
                not: {
                  enum: [
                    'ORACLE', 'SNOWFLAKE', 'ATHENA', 'INFORMIX', 'DYNAMODB',
                    'ELASTICSEARCH', 'AURORAMYSQL', 'AURORAPOSTGRESQL',
                    'POSTGRESQL', 'MYSQL', 'MSSQL', 'MONGODB', 'HIVE', 'TERADATA',
                    'GREENPLUM', 'MARIADB', 'REDSHIFT', 'SYBASE', 'DB2',
                    'NETEZZA', 'VERTICA', 'HANA', 'IMPALA'
                  ]
                }
              }
            },
            required: []
          }
        ]
      },
      mode: {
        oneOf: [
          {
            properties: { mode: { enum: ['PROXY'] } },
            required: ['proxyHost', 'proxyPort']
          },
          {
            properties: { mode: { enum: ['SNIFFER'] } },
            required: ['snifferDevice']
          }
        ]
      }
    },
    category: 'Instance',
  },
  {
    toolName: 'instance_update_metadata',
    description: 'Updates the metadata for a specified database instance in DataSunrise.',
    baseCommand: 'updateMetadata',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance for which to update metadata.'), required: true, cliName: '-instance' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'Database login with permissions to read metadata.'), required: false, cliName: '-login' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'Password for the database login.'), required: false, cliName: '-password' },
      { name: 'interfaceHost', type: 'string', description: enhanceParameterDescription('string', 'Host of the Interface. Optional if only one Interface exists.'), required: false, cliName: '-interfaceHost' },
      { name: 'interfacePort', type: 'string', description: enhanceParameterDescription('string', 'Port of the Interface. Optional if only one Interface exists.'), required: false, cliName: '-interfacePort' },
    ],
    category: 'Instance',
  },
  {
    toolName: 'instance_interface_add',
    description: 'Adds a network interface configuration to an existing DataSunrise instance. (CLI Guide 5.1)',
    baseCommand: 'addInterface',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the Instance to which the Interface is added'), required: true, cliName: '-instance' },
      { name: 'newHost', type: 'string', description: enhanceParameterDescription('string', 'New host of the Interface', 'HOSTNAME_OR_IP'), required: true, cliName: '-newHost' },
      { name: 'newPort', type: 'string', description: enhanceParameterDescription('string', 'New port of the Interface', 'PORT'), required: true, cliName: '-newPort' },
      { name: 'ipVersion', type: 'string', description: enhanceParameterDescription('string', 'IP version ( IPv4 | IPv6 | Auto ). Auto is default value.'), required: false, cliName: '-ipVersion' },
      { name: 'ssl', type: 'string', description: enhanceParameterDescription('string', 'Use SSL when connecting to Oracle or DB2 or DynamoDB. ( No | SSL )'), required: false, cliName: '-ssl'},
      { name: 'keyGroupName', type: 'string', description: enhanceParameterDescription('string', "Name of the group of Certificates or 'No'"), required: false, cliName: '-keyGroupName' },
      { name: 'verifyCA', type: 'string', description: enhanceParameterDescription('string', 'Verify Certificate (true | false)'), required: false, cliName: '-verifyCA' },
    ],
    category: 'Instance',
  },
  {
    toolName: 'instance_proxy_add',
    description: 'Adds a proxy configuration to an existing interface of a DataSunrise instance. (CLI Guide 5.2)',
    baseCommand: 'addProxy',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance.'), required: true, cliName: '-instance' },
      { name: 'interfaceHost', type: 'string', description: enhanceParameterDescription('string', 'Host of the interface to add the proxy to.', 'HOSTNAME_OR_IP'), required: true, cliName: '-interfaceHost' },
      { name: 'interfacePort', type: 'string', description: enhanceParameterDescription('string', 'Port of the interface to add the proxy to.', 'PORT'), required: true, cliName: '-interfacePort' },
      { name: 'proxyHost', type: 'string', description: enhanceParameterDescription('string', 'Host/IP where the DataSunrise proxy will listen.', 'HOSTNAME_OR_IP'), required: true, cliName: '-proxyHost' },
      { name: 'proxyPort', type: 'string', description: enhanceParameterDescription('string', 'Port on which the DataSunrise proxy will listen.', 'PORT'), required: true, cliName: '-proxyPort' },
      { name: 'dsServer', type: 'string', description: enhanceParameterDescription('string', 'Logical name of the DataSunrise server for which the proxy will be created. Optional.'), required: false, cliName: '-dsServer'},
      { name: 'enable', type: 'string', description: enhanceParameterDescription('string', 'Enable/disable the Proxy (true | false).'), required: false, cliName: '-enable' },
      { name: 'keyGroupID', type: 'string', description: enhanceParameterDescription('string', "ID of the group of certificates or '-1' to reset already assigned group."), required: false, cliName: '-keyGroupID' },
      { name: 'keyGroupName', type: 'string', description: enhanceParameterDescription('string', "Name of the group of certificates or 'No' to reset already assigned group."), required: false, cliName: '-keyGroupName' },
      { name: 'sslOnly', type: 'string', description: enhanceParameterDescription('string', 'Accept only encrypted connections (true | false).'), required: false, cliName: '-sslOnly' },
    ],
    category: 'Instance',
  },
  // UPDATE commands
  {
    toolName: 'instance_update',
    description: "Updates an existing DataSunrise instance's properties (e.g., name, login). (CLI Guide 4.9)",
    baseCommand: 'updateInstance',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the instance to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'New logical name for the instance.'), required: false, cliName: '-newName' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'New database user for DataSunrise connection.'), required: false, cliName: '-login' },
      { name: 'database', type: 'string', description: enhanceParameterDescription('string', 'Name of a database to update an Instance for. For DB2, Greenplum, MySQL, PostgreSQL, Redshift, Teradata only. For DynamoDB, this option is used for Dynamo region.'), required: false, cliName: '-database' },
      { name: 'envAutoCreate', type: 'string', description: enhanceParameterDescription('string', 'Create DS Environment automatically (true | false).', undefined, 'false'), required: false, cliName: '-envAutoCreate' },
      { name: 'envName', type: 'string', description: enhanceParameterDescription('string', 'DS Environment Name.'), required: false, cliName: '-envName' },
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance name for Oracle database.'), required: false, cliName: '-instance' }, // Oracle specific instance name, not the logical -name
      { name: 'instanceType', type: 'string', description: enhanceParameterDescription('string', 'Instance type for Oracle database (sid | name).', 'ENUM', 'sid'), required: false, cliName: '-instanceType' },
      { name: 'sysDba', type: 'string', description: enhanceParameterDescription('string', 'Connect to Oracle database with SYSDBA privileges (true | false)', undefined, 'false'), required: false, cliName: '-sysDba' },
      { name: 'tableRelations', type: 'string', description: enhanceParameterDescription('string', 'Search for table relations and include them in the default target database relation (true | false).', undefined, 'false'), required: false, cliName: '-tableRelations' },
      { name: 'queryGroups2FA', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated list of query groups, queries of which are used to access the database when configuring 2FA.', 'LIST'), required: false, cliName: '-queryGroups2FA' },
      { name: 'queryResultLocation', type: 'string', description: enhanceParameterDescription('string', 'Query result location for Amazon Athena.', 'URI'), required: false, cliName: '-queryResultLocation' },
      { name: 'awsRegion', type: 'string', description: enhanceParameterDescription('string', 'AWS Region for DynamoDB, Amazon Athena, Amazon Elasticsearch, PostgreSQL, MySQL.'), required: false, cliName: '-awsRegion' },
      { name: 'metadataRetrievalMethod', type: 'string', description: enhanceParameterDescription('string', 'Metadata retrieval method: Regular | Via Stored Procedures (for Aurora MySQL, MariaDB, MySQL only).', 'ENUM'), required: false, cliName: '-metadataRetrievalMethod' },
      { name: 'protocolType', type: 'string', description: enhanceParameterDescription('string', 'Protocol type for MySQL-like databases: Usual | HTTP | XProtocol.', 'ENUM'), required: false, cliName: '-protocolType' },
      { name: 'acceptOnly2FAUsers', type: 'string', description: enhanceParameterDescription('string', 'Accept only users authenticated with 2FA (true | false)'), required: false, cliName: '-acceptOnly2FAUsers' },
      { name: 'account', type: 'string', description: enhanceParameterDescription('string', 'Cloud account name for Snowflake'), required: false, cliName: '-account' },
      { name: 'enableAgent', type: 'string', description: enhanceParameterDescription('string', 'Enable agent (true | false)'), required: false, cliName: '-enableAgent' },
      { name: 'hostFQDN', type: 'string', description: enhanceParameterDescription('string', 'Kerberos Host FQDN for Hive, Impala'), required: false, cliName: '-hostFQDN' },
      { name: 'kerberosName', type: 'string', description: enhanceParameterDescription('string', 'Kerberos Service Name'), required: false, cliName: '-kerberosName' },
      { name: 'kerberosRealm', type: 'string', description: enhanceParameterDescription('string', 'Kerberos Realm for Hive, Impala'), required: false, cliName: '-kerberosRealm' },
      { name: 'loginType', type: 'string', description: enhanceParameterDescription('string', 'Login Type: Without Authentication | Regular | Active Directory | IAM Role'), required: false, cliName: '-loginType' },
      { name: 'serverName', type: 'string', description: enhanceParameterDescription('string', 'Server name for Informix support'), required: false, cliName: '-serverName' },
    ],
    category: 'Instance',
  },
  {
    toolName: 'instance_update_credentials',
    description: "Updates the database credentials (login and password) stored for a DataSunrise instance. (CLI Guide 4.10)",
    baseCommand: 'updateInstanceCredentials',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance whose credentials to update.'), required: true, cliName: '-instance' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'New database login.'), required: true, cliName: '-login' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'New password for the login.'), required: true, cliName: '-password' },
    ],
    category: 'Instance',
  },
  {
    toolName: 'instance_interface_update',
    description: "Updates an existing network interface of a DataSunrise instance. (CLI Guide 5.1)",
    baseCommand: 'updateInterface',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance.'), required: true, cliName: '-instance' },
      { name: 'prevHost', type: 'string', description: enhanceParameterDescription('string', 'Current host of the interface to update.', 'HOSTNAME_OR_IP'), required: true, cliName: '-prevHost' },
      { name: 'prevPort', type: 'string', description: enhanceParameterDescription('string', 'Current port of the interface to update.', 'PORT'), required: true, cliName: '-prevPort' },
      { name: 'newHost', type: 'string', description: enhanceParameterDescription('string', 'New host for the interface.', 'HOSTNAME_OR_IP'), required: false, cliName: '-newHost' },
      { name: 'newPort', type: 'string', description: enhanceParameterDescription('string', 'New port for the interface.', 'PORT'), required: false, cliName: '-newPort' },
      { name: 'ipVersion', type: 'string', description: enhanceParameterDescription('string', 'IP version ( IPv4 | IPv6 | Auto ). Auto is default value.'), required: false, cliName: '-ipVersion' },
      { name: 'keyGroupName', type: 'string', description: enhanceParameterDescription('string', "Name of the group of Certificates or 'No'"), required: false, cliName: '-keyGroupName' },
      { name: 'ssl', type: 'string', description: enhanceParameterDescription('string', 'use SSL when connecting to Oracle or DB2 or DynamoDB. ( No | SSL )'), required: false, cliName: '-ssl' },
      { name: 'verifyCA', type: 'string', description: enhanceParameterDescription('string', 'Verify Certificate (true | false)'), required: false, cliName: '-verifyCA' },
    ],
    category: 'Instance',
  },
  {
    toolName: 'instance_proxy_update',
    description: "Updates an existing proxy configuration for an instance's interface. (CLI Guide 5.3)",
    baseCommand: 'updateProxy',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance.'), required: true, cliName: '-instance' },
      { name: 'interfaceHost', type: 'string', description: enhanceParameterDescription('string', 'Host of the interface.', 'HOSTNAME_OR_IP'), required: true, cliName: '-interfaceHost' },
      { name: 'interfacePort', type: 'string', description: enhanceParameterDescription('string', 'Port of the interface.', 'PORT'), required: true, cliName: '-interfacePort' },
      { name: 'prevProxyHost', type: 'string', description: enhanceParameterDescription('string', 'Current host of the proxy to update.', 'HOSTNAME_OR_IP'), required: true, cliName: '-prevProxyHost' },
      { name: 'prevProxyPort', type: 'string', description: enhanceParameterDescription('string', 'Current port of the proxy to update.', 'PORT'), required: true, cliName: '-prevProxyPort' },
      { name: 'proxyHost', type: 'string', description: enhanceParameterDescription('string', 'New host for the proxy.', 'HOSTNAME_OR_IP'), required: false, cliName: '-proxyHost' },
      { name: 'proxyPort', type: 'string', description: enhanceParameterDescription('string', 'New port for the proxy.', 'PORT'), required: false, cliName: '-proxyPort' },
      { name: 'enable', type: 'string', description: enhanceParameterDescription('string', 'Enable/disable the proxy (true | false).'), required: false, cliName: '-enable'},
      { name: 'dsServer', type: 'string', description: enhanceParameterDescription('string', 'Logical name of the DataSunrise server.'), required: false, cliName: '-dsServer'},
      { name: 'keyGroupID', type: 'string', description: enhanceParameterDescription('string', "ID of the group of certificates or '-1' to reset already assigned group."), required: false, cliName: '-keyGroupID' },
      { name: 'keyGroupName', type: 'string', description: enhanceParameterDescription('string', "Name of the group of certificates or 'No' to reset already assigned group."), required: false, cliName: '-keyGroupName' },
      { name: 'sslOnly', type: 'string', description: enhanceParameterDescription('string', 'Accept only encrypted connections (true | false).'), required: false, cliName: '-sslOnly' },
    ],
    category: 'Instance',
  },
  // SHOW commands
  { toolName: 'instance_show_all', description: 'Displays a list of all configured DataSunrise instances. (CLI Guide 4.5)', baseCommand: 'showInstances', params: [], category: 'Instance' },
  {
    toolName: 'instance_show_one', description: 'Shows detailed information for a specific DataSunrise instance. (CLI Guide 4.4)', baseCommand: 'showInstance',
    params: [{ name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance to display.'), required: true, cliName: '-name' }],
    category: 'Instance',
  },
  {
    toolName: 'instance_interface_show_all', description: 'Displays all interfaces for a given instance. If no instance is specified, interfaces for all instances are shown. (CLI Guide 5.13)', baseCommand: 'showInterfaces',
    params: [{ name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance whose interfaces to show.', undefined, undefined, 'If omitted, interfaces for ALL instances will be displayed.'), required: false, cliName: '-instance' }],
    category: 'Instance',
  },
  {
    toolName: 'instance_interface_show_one', description: 'Shows detailed information for a specific interface of an instance. (CLI Guide 5.1)', baseCommand: 'showInterface',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance.'), required: true, cliName: '-instance' },
      { name: 'host', type: 'string', description: enhanceParameterDescription('string', 'Host of the interface to display.', 'HOSTNAME_OR_IP'), required: true, cliName: '-host' },
      { name: 'port', type: 'string', description: enhanceParameterDescription('string', 'Port of the interface to display.', 'PORT'), required: true, cliName: '-port' },
    ],
    category: 'Instance',
  },
  {
    toolName: 'instance_proxy_show_all', description: 'Displays all proxies for a specific interface of an instance.', baseCommand: 'showProxies', // No direct section, inferred
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance.'), required: true, cliName: '-instance' },
      { name: 'interfaceHost', type: 'string', description: enhanceParameterDescription('string', 'Host of the interface whose proxies to show.', 'HOSTNAME_OR_IP'), required: true, cliName: '-interfaceHost' },
      { name: 'interfacePort', type: 'string', description: enhanceParameterDescription('string', 'Port of the interface whose proxies to show.', 'PORT'), required: true, cliName: '-interfacePort' },
    ],
    category: 'Instance',
  },
  {
    toolName: 'instance_proxy_show_one', description: 'Shows detailed information for a specific proxy. (CLI Guide 5.5)', baseCommand: 'showProxy',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance.'), required: true, cliName: '-instance' },
      { name: 'interfaceHost', type: 'string', description: enhanceParameterDescription('string', 'Host of the interface.', 'HOSTNAME_OR_IP'), required: true, cliName: '-interfaceHost' },
      { name: 'interfacePort', type: 'string', description: enhanceParameterDescription('string', 'Port of the interface.', 'PORT'), required: true, cliName: '-interfacePort' },
      { name: 'proxyHost', type: 'string', description: enhanceParameterDescription('string', 'Host of the proxy to display.', 'HOSTNAME_OR_IP'), required: true, cliName: '-proxyHost' },
      { name: 'proxyPort', type: 'string', description: enhanceParameterDescription('string', 'Port of the proxy to display.', 'PORT'), required: true, cliName: '-proxyPort' },
      { name: 'dsServer', type: 'string', description: enhanceParameterDescription('string', 'Server name where proxy is opened or sniffer is used.'), required: false, cliName: '-dsServer'},
    ],
    category: 'Instance',
  },
  // DELETE commands
  {
    toolName: 'instance_delete', description: 'Deletes a DataSunrise instance definition. (CLI Guide 4.7)', baseCommand: 'delInstance',
    params: [{ name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance to delete.'), required: true, cliName: '-name' }],
    category: 'Instance',
  },
  // --- Log Trail Commands ---
  {
    toolName: 'instance_add_log_trail',
    description: 'Add log trailing to Instance Interface',
    baseCommand: 'addLogTrail',
    category: 'Instance',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'logical name of the Instance'), required: true, cliName: '-instance' },
      { name: 'interfaceHost', type: 'string', description: enhanceParameterDescription('string', 'host of the Interface'), required: true, cliName: '-interfaceHost' },
      { name: 'interfacePort', type: 'string', description: enhanceParameterDescription('string', 'port of the Interface'), required: true, cliName: '-interfacePort' },
      { name: 'accessKey', type: 'string', description: enhanceParameterDescription('string', 'Access Key'), required: false, cliName: '-accessKey' },
      { name: 'awsSmID', type: 'string', description: enhanceParameterDescription('string', 'AWS secrets manager ID'), required: false, cliName: '-awsSmID' },
      { name: 'azureKeyVault', type: 'string', description: enhanceParameterDescription('string', 'Azure Key Vault'), required: false, cliName: '-azureKeyVault' },
      { name: 'azureSecretName', type: 'string', description: enhanceParameterDescription('string', 'Azure Secret Name'), required: false, cliName: '-azureSecretName' },
      { name: 'blobContainerName', type: 'string', description: enhanceParameterDescription('string', 'Blob container name for Azure Connection Type'), required: false, cliName: '-blobContainerName' },
      { name: 'clientId', type: 'string', description: enhanceParameterDescription('string', 'Client ID for Azure Azure Connection Type'), required: false, cliName: '-clientId' },
      { name: 'clientSecret', type: 'string', description: enhanceParameterDescription('string', 'Client secret for Azure Connection Type'), required: false, cliName: '-clientSecret' },
      { name: 'connectType', type: 'string', description: enhanceParameterDescription('string', 'Connect type: AWS | SMB | Local Folder | Oracle Package | Azure', 'ENUM'), required: false, cliName: '-connectType' },
      { name: 'cyberArkFolder', type: 'string', description: enhanceParameterDescription('string', 'CyberArk Folder'), required: false, cliName: '-cyberArkFolder' },
      { name: 'cyberArkObject', type: 'string', description: enhanceParameterDescription('string', 'CyberArk Object'), required: false, cliName: '-cyberArkObject' },
      { name: 'cyberArkSafe', type: 'string', description: enhanceParameterDescription('string', 'CyberArk Safe'), required: false, cliName: '-cyberArkSafe' },
      { name: 'dbIdentifier', type: 'string', description: enhanceParameterDescription('string', 'DB Identifier'), required: false, cliName: '-dbIdentifier' },
      { name: 'delLogs', type: 'string', description: enhanceParameterDescription('string', 'Delete processed logs (true | false)'), required: false, cliName: '-delLogs' },
      { name: 'dsServer', type: 'string', description: enhanceParameterDescription('string', 'Server name where proxy is opened or sniffer is used'), required: false, cliName: '-dsServer' },
      { name: 'enable', type: 'string', description: enhanceParameterDescription('string', 'enable/disable the Trailing (true | false)'), required: false, cliName: '-enable' },
      { name: 'formatType', type: 'string', description: enhanceParameterDescription('string', 'Format type: Database | XML | CSV | JSON | Gauss', 'ENUM'), required: false, cliName: '-formatType' },
      { name: 'localPath', type: 'string', description: enhanceParameterDescription('string', 'Local Path'), required: false, cliName: '-localPath' },
      { name: 'loginType', type: 'string', description: enhanceParameterDescription('string', 'Login Type: Without Authentication | Regular | Active Directory | IAM Role', 'ENUM'), required: false, cliName: '-loginType' },
      { name: 'oraclePackage', type: 'string', description: enhanceParameterDescription('string', 'Oracle Package'), required: false, cliName: '-oraclePackage' },
      { name: 'path', type: 'string', description: enhanceParameterDescription('string', "Log Path (for SMB: share path, must end with '/')"), required: false, cliName: '-path' },
      { name: 'period', type: 'string', description: enhanceParameterDescription('string', 'Periodicity of request data (seconds)'), required: false, cliName: '-period' },
      { name: 'region', type: 'string', description: enhanceParameterDescription('string', 'AWS Region'), required: false, cliName: '-region' },
      { name: 'roleARN', type: 'string', description: enhanceParameterDescription('string', 'Role ARN'), required: false, cliName: '-roleARN' },
      { name: 'savePassword', type: 'string', description: enhanceParameterDescription('string', 'Password storage type: ds | ca | awssm | azurekv', 'ENUM'), required: false, cliName: '-savePassword' },
      { name: 'secretKey', type: 'string', description: enhanceParameterDescription('string', 'Secret Key'), required: false, cliName: '-secretKey' },
      { name: 'smbHost', type: 'string', description: enhanceParameterDescription('string', 'SMB server hostname or IP address'), required: false, cliName: '-smbHost' },
      { name: 'smbLogin', type: 'string', description: enhanceParameterDescription('string', 'SMB username for authentication'), required: false, cliName: '-smbLogin' },
      { name: 'smbPwd', type: 'string', description: enhanceParameterDescription('string', 'SMB password for authentication'), required: false, cliName: '-smbPwd' },
      { name: 'storageAccountName', type: 'string', description: enhanceParameterDescription('string', 'Storage Account name for Azure Connection Type'), required: false, cliName: '-storageAccountName' },
      { name: 'storeLogsPeriod', type: 'string', description: enhanceParameterDescription('string', 'Time Period to Store Log Files (Days)'), required: false, cliName: '-storeLogsPeriod' },
      { name: 'tenantId', type: 'string', description: enhanceParameterDescription('string', 'Tenant ID for Azure Connection Type'), required: false, cliName: '-tenantId' },
      { name: 'testConnection', type: 'boolean', description: enhanceParameterDescription('boolean', 'Test connection before task creating. If test connection fault task will not be created.'), required: false, cliName: '-testConnection' },
    ]
  },
  {
    toolName: 'instance_show_log_trail',
    description: 'Displays an existing Trail DB Audit Logs entity. (CLI Guide 4.6)',
    baseCommand: 'showLogTrail',
    category: 'Instance',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Logical name of the Instance.'), required: true, cliName: '-instance' },
      { name: 'interfaceHost', type: 'string', description: enhanceParameterDescription('string', 'Interface host.'), required: true, cliName: '-interfaceHost' },
      { name: 'interfacePort', type: 'string', description: enhanceParameterDescription('string', 'Interface port number.'), required: true, cliName: '-interfacePort' },
      { name: 'dsServer', type: 'string', description: enhanceParameterDescription('string', 'DataSunrise server the proxy or sniffer is used on.'), required: false, cliName: '-dsServer' },
    ]
  },
  {
    toolName: 'instance_delete_log_trail',
    description: 'Deletes an existing Trail DB Audit Logs entity. (CLI Guide 4.8)',
    baseCommand: 'delLogTrail',
    category: 'Instance',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Logical name of the Instance.'), required: true, cliName: '-instance' },
      { name: 'interfaceHost', type: 'string', description: enhanceParameterDescription('string', 'Interface host.'), required: true, cliName: '-interfaceHost' },
      { name: 'interfacePort', type: 'string', description: enhanceParameterDescription('string', 'Interface port number.'), required: true, cliName: '-interfacePort' },
      { name: 'dsServer', type: 'string', description: enhanceParameterDescription('string', 'DataSunrise server the proxy or sniffer is used on.'), required: true, cliName: '-dsServer' },
    ]
  },
  {
    toolName: 'instance_update_log_trail',
    description: 'Edits an existing Trail DB Audit Logs entity. (CLI Guide 4.11)',
    baseCommand: 'updateLogTrail',
    category: 'Instance',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'logical name of the Instance'), required: true, cliName: '-instance' },
      { name: 'interfaceHost', type: 'string', description: enhanceParameterDescription('string', 'host of the Interface'), required: true, cliName: '-interfaceHost' },
      { name: 'interfacePort', type: 'string', description: enhanceParameterDescription('string', 'port of the Interface'), required: true, cliName: '-interfacePort' },
      { name: 'accessKey', type: 'string', description: enhanceParameterDescription('string', 'Access Key'), required: false, cliName: '-accessKey' },
      { name: 'awsSmID', type: 'string', description: enhanceParameterDescription('string', 'AWS secrets manager ID'), required: false, cliName: '-awsSmID' },
      { name: 'azureKeyVault', type: 'string', description: enhanceParameterDescription('string', 'Azure Key Vault'), required: false, cliName: '-azureKeyVault' },
      { name: 'azureSecretName', type: 'string', description: enhanceParameterDescription('string', 'Azure Secret Name'), required: false, cliName: '-azureSecretName' },
      { name: 'blobContainerName', type: 'string', description: enhanceParameterDescription('string', 'Blob container name for Azure Connection Type'), required: false, cliName: '-blobContainerName' },
      { name: 'clientId', type: 'string', description: enhanceParameterDescription('string', 'Client ID for Azure Azure Connection Type'), required: false, cliName: '-clientId' },
      { name: 'clientSecret', type: 'string', description: enhanceParameterDescription('string', 'Client secret for Azure Connection Type'), required: false, cliName: '-clientSecret' },
      { name: 'connectType', type: 'string', description: enhanceParameterDescription('string', 'Connect type: AWS | SMB | Local Folder | Oracle Package | Azure', 'ENUM'), required: false, cliName: '-connectType' },
      { name: 'cyberArkFolder', type: 'string', description: enhanceParameterDescription('string', 'CyberArk Folder'), required: false, cliName: '-cyberArkFolder' },
      { name: 'cyberArkObject', type: 'string', description: enhanceParameterDescription('string', 'CyberArk Object'), required: false, cliName: '-cyberArkObject' },
      { name: 'cyberArkSafe', type: 'string', description: enhanceParameterDescription('string', 'CyberArk Safe'), required: false, cliName: '-cyberArkSafe' },
      { name: 'dbIdentifier', type: 'string', description: enhanceParameterDescription('string', 'DB Identifier'), required: false, cliName: '-dbIdentifier' },
      { name: 'delLogs', type: 'string', description: enhanceParameterDescription('string', 'Delete processed logs: true | false'), required: false, cliName: '-delLogs' },
      { name: 'dsServer', type: 'string', description: enhanceParameterDescription('string', 'server name where proxy is opened or sniffer is used'), required: false, cliName: '-dsServer' },
      { name: 'enable', type: 'string', description: enhanceParameterDescription('string', 'enable/disable the Trailing: true | false'), required: false, cliName: '-enable' },
      { name: 'formatType', type: 'string', description: enhanceParameterDescription('string', 'Format type: Database | XML | CSV | JSON | Gauss', 'ENUM'), required: false, cliName: '-formatType' },
      { name: 'localPath', type: 'string', description: enhanceParameterDescription('string', 'Local Path'), required: false, cliName: '-localPath' },
      { name: 'loginType', type: 'string', description: enhanceParameterDescription('string', 'Login Type: Without Authentication | Regular | Active Directory | IAM Role', 'ENUM'), required: false, cliName: '-loginType' },
      { name: 'oraclePackage', type: 'string', description: enhanceParameterDescription('string', 'Oracle Package'), required: false, cliName: '-oraclePackage' },
      { name: 'path', type: 'string', description: enhanceParameterDescription('string', "Log Path (for SMB: share path, must end with '/')"), required: false, cliName: '-path' },
      { name: 'period', type: 'string', description: enhanceParameterDescription('string', 'Periodicity of request data (seconds)'), required: false, cliName: '-period' },
      { name: 'region', type: 'string', description: enhanceParameterDescription('string', 'AWS Region'), required: false, cliName: '-region' },
      { name: 'roleARN', type: 'string', description: enhanceParameterDescription('string', 'Role ARN'), required: false, cliName: '-roleARN' },
      { name: 'savePassword', type: 'string', description: enhanceParameterDescription('string', 'Password storage type: ds | ca | awssm | azurekv', 'ENUM'), required: false, cliName: '-savePassword' },
      { name: 'secretKey', type: 'string', description: enhanceParameterDescription('string', 'Secret Key'), required: false, cliName: '-secretKey' },
      { name: 'sessionToken', type: 'string', description: enhanceParameterDescription('string', 'Session token for multi-session support'), required: false, cliName: '-sessionToken' },
      { name: 'smbHost', type: 'string', description: enhanceParameterDescription('string', 'SMB server hostname or IP address'), required: false, cliName: '-smbHost' },
      { name: 'smbLogin', type: 'string', description: enhanceParameterDescription('string', 'SMB username for authentication'), required: false, cliName: '-smbLogin' },
      { name: 'smbPwd', type: 'string', description: enhanceParameterDescription('string', 'SMB password for authentication'), required: false, cliName: '-smbPwd' },
      { name: 'storageAccountName', type: 'string', description: enhanceParameterDescription('string', 'Storage Account name for Azure Connection Type'), required: false, cliName: '-storageAccountName' },
      { name: 'storeLogsPeriod', type: 'string', description: enhanceParameterDescription('string', 'Time Period to Store Log Files (Days)'), required: false, cliName: '-storeLogsPeriod' },
      { name: 'tenantId', type: 'string', description: enhanceParameterDescription('string', 'Tenant ID for Azure Connection Type'), required: false, cliName: '-tenantId' },
      { name: 'testConnection', type: 'boolean', description: enhanceParameterDescription('boolean', 'Test connection before task creating. If test connection fault task will not be created.'), required: false, cliName: '-testConnection' },
    ]
  },
  {
    toolName: 'instance_interface_delete', description: 'Deletes a network interface from an instance. (CLI Guide 5.1)', baseCommand: 'delInterface',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance.'), required: true, cliName: '-instance' },
      { name: 'host', type: 'string', description: enhanceParameterDescription('string', 'Host of the interface to delete.', 'HOSTNAME_OR_IP'), required: true, cliName: '-host' },
      { name: 'port', type: 'string', description: enhanceParameterDescription('string', 'Port of the interface to delete.', 'PORT'), required: true, cliName: '-port' },
    ],
    category: 'Instance',
  },
  {
    toolName: 'instance_proxy_delete', description: 'Deletes a proxy configuration from an interface. (CLI Guide 5.4)', baseCommand: 'delProxy',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the instance.'), required: true, cliName: '-instance' },
      { name: 'interfaceHost', type: 'string', description: enhanceParameterDescription('string', 'Host of the interface.', 'HOSTNAME_OR_IP'), required: true, cliName: '-interfaceHost' },
      { name: 'interfacePort', type: 'string', description: enhanceParameterDescription('string', 'Port of the interface.', 'PORT'), required: true, cliName: '-interfacePort' },
      { name: 'proxyHost', type: 'string', description: enhanceParameterDescription('string', 'Host of the proxy to delete.', 'HOSTNAME_OR_IP'), required: true, cliName: '-proxyHost' },
      { name: 'proxyPort', type: 'string', description: enhanceParameterDescription('string', 'Port of the proxy to delete.', 'PORT'), required: true, cliName: '-proxyPort' },
      { name: 'dsServer', type: 'string', description: enhanceParameterDescription('string', 'Server name where proxy is opened or sniffer is used.'), required: false, cliName: '-dsServer' },
    ],
    category: 'Instance',
  },
  // --- Sniffer Commands (Chapter 5) ---
  {
    toolName: 'instance_sniffer_add',
    description: 'Adds a new sniffer to the instance interface. (CLI Guide 5.7)',
    baseCommand: 'addSniffer',
    category: 'Instance',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'logical name of the Instance'), required: true, cliName: '-instance' },
      { name: 'interfaceHost', type: 'string', description: enhanceParameterDescription('string', 'host of the Interface'), required: true, cliName: '-interfaceHost' },
      { name: 'interfacePort', type: 'string', description: enhanceParameterDescription('string', 'port of the Interface'), required: true, cliName: '-interfacePort' },
      { name: 'device', type: 'string', description: enhanceParameterDescription('string', 'device to sniff traffic'), required: true, cliName: '-device' },
      { name: 'dsServer', type: 'string', description: enhanceParameterDescription('string', 'server name where proxy is opened or sniffer is used'), required: false, cliName: '-dsServer' },
      { name: 'enable', type: 'string', description: enhanceParameterDescription('string', 'enable/disable the Sniffer: true | false'), required: false, cliName: '-enable' },
      { name: 'keyGroupName', type: 'string', description: enhanceParameterDescription('string', "Name of the group of Certificates or 'No'"), required: false, cliName: '-keyGroupName' },
    ],
  },
  {
    toolName: 'instance_sniffer_show',
    description: 'Retrieves information about a sniffer. (CLI Guide 5.8)',
    baseCommand: 'showSniffer',
    category: 'Instance',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Logical name of the Instance.'), required: true, cliName: '-instance' },
      { name: 'interfaceHost', type: 'string', description: enhanceParameterDescription('string', 'Host name or an IP address of an existing instance interface.'), required: true, cliName: '-interfaceHost' },
      { name: 'interfacePort', type: 'string', description: enhanceParameterDescription('string', 'Port of an existing instance interface.'), required: true, cliName: '-interfacePort' },
      { name: 'device', type: 'string', description: enhanceParameterDescription('string', 'Device to sniff traffic.'), required: true, cliName: '-device' },
      { name: 'dsServer', type: 'string', description: enhanceParameterDescription('string', 'Logical name of the DataSunrise server.'), required: false, cliName: '-dsServer' },
    ],
  },
  {
    toolName: 'instance_sniffer_update',
    description: 'Updates a sniffer. (CLI Guide 5.9)',
    baseCommand: 'updateSniffer',
    category: 'Instance',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'logical name of the Instance'), required: true, cliName: '-instance' },
      { name: 'interfaceHost', type: 'string', description: enhanceParameterDescription('string', 'host of the Interface'), required: true, cliName: '-interfaceHost' },
      { name: 'interfacePort', type: 'string', description: enhanceParameterDescription('string', 'port of the Interface'), required: true, cliName: '-interfacePort' },
      { name: 'device', type: 'string', description: enhanceParameterDescription('string', 'device to sniff traffic'), required: true, cliName: '-device' },
      { name: 'dsServer', type: 'string', description: enhanceParameterDescription('string', 'server name where proxy is opened or sniffer is used'), required: false, cliName: '-dsServer' },
      { name: 'enable', type: 'string', description: enhanceParameterDescription('string', 'enable/disable the Sniffer: true | false'), required: false, cliName: '-enable' },
      { name: 'keyGroupName', type: 'string', description: enhanceParameterDescription('string', "Name of the group of Certificates or 'No'"), required: false, cliName: '-keyGroupName' },
    ],
  },
  {
    toolName: 'instance_sniffer_delete',
    description: 'Deletes a sniffer from instance interface. (CLI Guide 5.10)',
    baseCommand: 'delSniffer',
    category: 'Instance',
    params: [
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'logical name of the Instance'), required: true, cliName: '-instance' },
      { name: 'interfaceHost', type: 'string', description: enhanceParameterDescription('string', 'host of the Interface'), required: true, cliName: '-interfaceHost' },
      { name: 'interfacePort', type: 'string', description: enhanceParameterDescription('string', 'port of the Interface'), required: true, cliName: '-interfacePort' },
      { name: 'device', type: 'string', description: enhanceParameterDescription('string', 'device to sniff traffic'), required: true, cliName: '-device' },
      { name: 'dsServer', type: 'string', description: enhanceParameterDescription('string', 'server name where proxy is opened or sniffer is used'), required: false, cliName: '-dsServer' },
    ],
  },
];
