import { CliCommand } from './types.js';
import { enhanceParameterDescription } from '../description_helpers.js';

const commonReportParams: CliCommand['params'] = [
  { name: 'generateReport', type: 'string', description: enhanceParameterDescription('string', 'Generate a report (true | false).'), required: false, cliName: '-generateReport' },
  { name: 'reportFormat', type: 'string', description: enhanceParameterDescription('string', 'Report file format (csv | pdf | json).', 'ENUM'), required: false, cliName: '-reportFormat' },
  { name: 'compressType', type: 'string', description: enhanceParameterDescription('string', 'Report compress type (no | zip | gzip).', 'ENUM'), required: false, cliName: '-compressType' },
  { name: 'subscribers', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated SMTP subscriber names.', 'LIST'), required: false, cliName: '-subscribers' },
];

const commonPeriodicTaskParams: CliCommand['params'] = [
  { name: 'days', type: 'string', description: enhanceParameterDescription('string', 'Month Days (1...31 | last) for Startup Separated by [;].'), required: false, cliName: '-days' },
  { name: 'delResults', type: 'string', description: enhanceParameterDescription('string', 'Remove Old Results (true | false).'), required: false, cliName: '-delResults' },
  { name: 'dsServer', type: 'string', description: enhanceParameterDescription('string', 'DataSunrise <server name> | any.'), required: false, cliName: '-dsServer' },
  { name: 'freqAmount', type: 'string', description: enhanceParameterDescription('string', 'Frequency of performing the task.'), required: false, cliName: '-freqAmount' },
  { name: 'freqUnit', type: 'string', description: enhanceParameterDescription('string', 'Startup Frequency: Manual | Once | Minutely | Hourly | Daily | Weekly | Monthly.', 'ENUM'), required: false, cliName: '-freqUnit' },
  { name: 'keepAmount', type: 'string', description: enhanceParameterDescription('string', 'Number of results to keep.'), required: false, cliName: '-keepAmount' },
  { name: 'keepUnit', type: 'string', description: enhanceParameterDescription('string', 'Keep Results for: Hours | Days | Weeks | Months.', 'ENUM'), required: false, cliName: '-keepUnit' },
  { name: 'months', type: 'string', description: enhanceParameterDescription('string', 'Months for Startup Separated by semicolon [;] (jan;feb;mar;apr;may;jun;jul;aug;sep;oct;nov;dec).'), required: false, cliName: '-months' },
  { name: 'startDate', type: 'string', description: enhanceParameterDescription('string', 'Start Date: yyyy-MM-dd HH:mm:ss.', 'DATETIME'), required: false, cliName: '-startDate' },
  { name: 'weekDays', type: 'string', description: enhanceParameterDescription('string', 'Day of Week for Startup Separated by semicolon [;] (mo;tu;we;th;fr;sa;su).'), required: false, cliName: '-weekDays' },
];

const optionalPeriodicTaskParams = commonPeriodicTaskParams.map(p => ({ ...p, required: false }));

const periodicTaskTypes = 'Clean Audit || Backup Dictionary || Command Shell || User Behavior || Query History Table Relation Learning || Vulnerability Assessment || Update Metadata || Periodic Data Discovery || Health Check || Azure Remove Unused Servers || AWS Remove Unused Servers || DDL Table Relation Learning || Database User Synchronization || Kubernetes Remove Unused Servers || Transfer Audit to Elasticsearch || Test Bucket Accessibility || AWS S3 Crawler || Oracle: Update Users Properties';

export const periodicTaskCommands: CliCommand[] = [
  {
    toolName: 'periodic_task_add_clean_audit',
    description: 'Adds a periodic task for cleaning (archiving or deleting) audit data. (CLI Guide 21.1)',
    baseCommand: 'addPerCleanAudit',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this clean audit task.'), required: true, cliName: '-name' },
      ...commonPeriodicTaskParams,
      { name: 'cleanType', type: 'string', description: enhanceParameterDescription('string', 'How to clean the storage: Delete | Drop | KeepDays.', 'ENUM'), required: false, cliName: '-cleanType' },
      { name: 'keepDays', type: 'string', description: enhanceParameterDescription('string', 'Keep auditing data, days (used with cleanType KeepDays).'), required: false, cliName: '-keepDays' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_backup_dictionary',
    description: 'Adds a periodic task for backing up the DataSunrise system dictionary. (CLI Guide 21.7)',
    baseCommand: 'addPerBackupDictionary',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this backup dictionary task.'), required: true, cliName: '-name' },
      ...commonPeriodicTaskParams,
      { name: 'backupName', type: 'string', description: enhanceParameterDescription('string', 'Logical name of the backup.'), required: true, cliName: '-backupName' },
      { name: 'backupObjects', type: 'string', description: enhanceParameterDescription('string', 'Backup DataSunrise Objects (true | false).'), required: false, cliName: '-backupObjects' },
      { name: 'backupSettings', type: 'string', description: enhanceParameterDescription('string', 'Backup DataSunrise Settings (true | false).'), required: false, cliName: '-backupSettings' },
      { name: 'backupUsers', type: 'string', description: enhanceParameterDescription('string', 'Backup DataSunrise Users (true | false).'), required: false, cliName: '-backupUsers' },
      { name: 'command', type: 'string', description: enhanceParameterDescription('string', 'Execute external command after backing up.'), required: false, cliName: '-command' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_user_behavior',
    description: 'Adds a periodic task for user behavior analysis and learning. (CLI Guide 21.9)',
    baseCommand: 'addPerUserBehavior',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this user behavior task.'), required: true, cliName: '-name' },
      ...commonPeriodicTaskParams,
      { name: 'generateReport', type: 'string', description: enhanceParameterDescription('string', 'Generate a report (true | false).'), required: false, cliName: '-generateReport' },
      { name: 'reportFormat', type: 'string', description: enhanceParameterDescription('string', 'Report file format (csv | pdf | json).', 'ENUM'), required: false, cliName: '-reportFormat' },
      { name: 'compressType', type: 'string', description: enhanceParameterDescription('string', 'Report compress type (no | zip | gzip).', 'ENUM'), required: false, cliName: '-compressType' },
      { name: 'trStartDate', type: 'string', description: enhanceParameterDescription('string', 'Training Start Date. Date format: yyyy-MM-dd HH:mm:ss.', 'DATETIME'), required: true, cliName: '-trStartDate' },
      { name: 'trEndDate', type: 'string', description: enhanceParameterDescription('string', 'Training End Date. Date format: yyyy-MM-dd HH:mm:ss.', 'DATETIME'), required: true, cliName: '-trEndDate' },
      { name: 'number', type: 'string', description: enhanceParameterDescription('string', 'Number value for lastNDay, lastNWeek, lastNMonth (for repPerType).'), required: false, cliName: '-number' },
      { name: 'repPerType', type: 'string', description: enhanceParameterDescription('string', 'Reporting Period Type: lastNDay | lastNWeek | lastNMonth | currentMonth | currentWeek | currentDay | manual.', 'ENUM'), required: false, cliName: '-repPerType' },
      { name: 'pdfStyle', type: 'string', description: enhanceParameterDescription('string', 'PDF report style (form | table). Only applies when reportFormat is PDF.'), required: false, cliName: '-pdfStyle' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_ddl_table_relation_learning',
    description: 'Adds a periodic task for learning table relations from DDL (Data Definition Language) statements. (CLI Guide 21.14)',
    baseCommand: 'addDDLTabRelLearnPerTask',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this DDL table relation learning task.'), required: true, cliName: '-name' },
      ...commonPeriodicTaskParams,
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the database instance whose DDL will be analyzed.'), required: true, cliName: '-instance' },
      { name: 'tableRel', type: 'string', description: enhanceParameterDescription('string', 'Name of an existing Table Relation (Data Model) entity to store results.'), required: true, cliName: '-tableRel' },
      { name: 'analyzeProcAndFunc', type: 'string', description: enhanceParameterDescription('string', 'Analyze DDL of stored procedures and functions (true | false). Default: "false".'), required: false, cliName: '-analyzeProcAndFunc', defaultValue: true },
      { name: 'analyzeView', type: 'string', description: enhanceParameterDescription('string', 'Analyze DDL of views (true | false). Default: "false".'), required: false, cliName: '-analyzeView' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'DB username to read DDL (if not stored in instance config).'), required: false, cliName: '-login' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'Password for the DB username.'), required: false, cliName: '-password' },
      { name: 'sysDba', type: 'string', description: enhanceParameterDescription('string', 'For Oracle: Connect as SYSDBA (true | false). Default: "false".'), required: false, cliName: '-sysDba' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_vulnerability_assessment',
    description: 'Adds a periodic task for performing vulnerability assessments on database instances. (CLI Guide 21.11)',
    baseCommand: 'addPerVulnAssessment',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this vulnerability assessment task.'), required: true, cliName: '-name' },
      ...commonPeriodicTaskParams,
      { name: 'subscribers', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated SMTP subscriber names.', 'LIST'), required: false, cliName: '-subscribers' },
      { name: 'instances', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated DB Instances; Leave it blank if you want to add all existing Instances.', 'LIST'), required: false, cliName: '-instances' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_update_metadata',
    description: 'Adds a periodic task for updating metadata for a specified database instance. (CLI Guide 21.5)',
    baseCommand: 'addPerUpdateMetadata',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this update metadata task.'), required: true, cliName: '-name' },
      ...commonPeriodicTaskParams,
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the database instance for which to update metadata.'), required: true, cliName: '-instance' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_data_discovery',
    description: 'Adds a periodic task for performing data discovery on a database instance. (CLI Guide 18.10)',
    baseCommand: 'addPerDiscovery',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this data discovery task.'), required: true, cliName: '-name' },
      ...commonPeriodicTaskParams,
      ...commonReportParams,
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Name of the database instance to search across.'), required: true, cliName: '-instance' },
      { name: 'pdfStyle', type: 'string', description: enhanceParameterDescription('string', 'PDF report style (form | table). Only applies when reportFormat is PDF.'), required: false, cliName: '-pdfStyle' },
      { name: 'searchByInfoTypes', type: 'string', description: enhanceParameterDescription('string', 'Information Types separated by semicolon (;) by default.', 'LIST'), required: false, cliName: '-searchByInfoTypes' },
      { name: 'searchByStandards', type: 'string', description: enhanceParameterDescription('string', 'Security Standards separated by semicolon (;) by default. All Security Standards by default.', 'LIST'), required: false, cliName: '-searchByStandards', defaultValue: 'HIPAA;GDPR;PCI DSS;SOX;ISO27001;KVKK;CCPA;APPI;Privacy Act NZ;LGPD;Nevada privacy law;PIPEDA;Digital personal data protection bill;APPS' },
      { name: 'additionalMetrics', type: 'string', description: enhanceParameterDescription('string', 'Enable Additional Metrics (true | false).'), required: false, cliName: '-additionalMetrics' },
      { name: 'analysedRow', type: 'string', description: enhanceParameterDescription('string', 'Number of table rows to analyze.'), required: false, cliName: '-analysedRow' },
      { name: 'enableStatDataSpeed', type: 'string', description: enhanceParameterDescription('string', 'Enable statistics on data processing speed for an AWS S3 Instance (true | false).'), required: false, cliName: '-enableStatDataSpeed' },
      { name: 'enableStatOnAttr', type: 'string', description: enhanceParameterDescription('string', 'Enable statistics on attributes (true | false).'), required: false, cliName: '-enableStatOnAttr' },
      { name: 'excludedTables', type: 'string', description: enhanceParameterDescription('string', 'Excluded Discovery Schemas, Tables, Columns formatted like "db.schema.table.col;..."', 'LIST'), required: false, cliName: '-excludedTables' },
      { name: 'excludeS3Objects', type: 'string', description: enhanceParameterDescription('string', 'Path to the folder that should be excluded from search for AWS S3 instance. Paths are separated by ; by default.', 'LIST'), required: false, cliName: '-excludeS3Objects' },
      { name: 'externalCommand', type: 'string', description: enhanceParameterDescription('string', 'External command.'), required: false, cliName: '-externalCommand' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'Database user login.'), required: false, cliName: '-login' },
      { name: 'maxPerNull', type: 'string', description: enhanceParameterDescription('string', 'Max percentage of NULL.'), required: false, cliName: '-maxPerNull' },
      { name: 'minPerMatch', type: 'string', description: enhanceParameterDescription('string', 'Min percentage of match.'), required: false, cliName: '-minPerMatch' },
      { name: 'objGroup', type: 'string', description: enhanceParameterDescription('string', 'Save Search Results in an Object Group: (<IdName> | false).'), required: false, cliName: '-objGroup' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'Database user password.'), required: false, cliName: '-password' },
      { name: 'reportColumns', type: 'string', description: enhanceParameterDescription('string', 'Columns of the report separated by comma (,). Col1:Title1,Col2.', 'LIST'), required: false, cliName: '-reportColumns' },
      { name: 'searchDb', type: 'string', description: enhanceParameterDescription('string', 'Database to search across. Empty value if database is not specified.'), required: false, cliName: '-searchDb' },
      { name: 'searchS3Objects', type: 'string', description: enhanceParameterDescription('string', 'Path to the folder that should be searched across for AWS S3 instance. Paths are separated by ; by default.', 'LIST'), required: false, cliName: '-searchS3Objects' },
      { name: 'searchSchema', type: 'string', description: enhanceParameterDescription('string', 'Schema to search at. Empty value if schema is not specified.'), required: false, cliName: '-searchSchema' },
      { name: 'searchTable', type: 'string', description: enhanceParameterDescription('string', 'Table to search at. Empty value if table is not specified.'), required: false, cliName: '-searchTable' },
      { name: 'skipNull', type: 'string', description: enhanceParameterDescription('string', 'Skip NULL (true | false).'), required: false, cliName: '-skipNull' },
      { name: 'withoutCredentials', type: 'boolean', description: enhanceParameterDescription('boolean', 'Do not check database credentials.'), required: false, cliName: '-withoutCredentials' },
      { name: 'writeToSyslog', type: 'string', description: enhanceParameterDescription('string', 'Write messages to Syslog (true | false).'), required: false, cliName: '-writeToSyslog' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_health_check',
    description: 'Adds a periodic task for performing health checks on a database instance. (CLI Guide 21.3)',
    baseCommand: 'addPerHealthCheck',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this health check task.'), required: true, cliName: '-name' },
      ...commonPeriodicTaskParams,
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Database instance to perform a health check for.'), required: true, cliName: '-instance' },
      { name: 'lbAddress', type: 'string', description: enhanceParameterDescription('string', 'Load Balancer public address.'), required: false, cliName: '-lbAddress' },
      { name: 'lbPort', type: 'string', description: enhanceParameterDescription('string', 'Load Balancer port.', 'PORT'), required: false, cliName: '-lbPort' },
      { name: 'sendErrors', type: 'string', description: enhanceParameterDescription('string', 'Send errors to Events (true | false).'), required: false, cliName: '-sendErrors' },
      { name: 'testMethod', type: 'string', description: enhanceParameterDescription('string', 'Proxy testing method: ExecSys || WebCheck.', 'ENUM'), required: false, cliName: '-testMethod' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_query_history_table_relation_learning',
    description: 'Adds a periodic task for learning table relations from query history. (CLI Guide 21.13)',
    baseCommand: 'addQueryHisTabRelLearnPerTask',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this task.'), required: true, cliName: '-name' },
      ...commonPeriodicTaskParams,
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance name.'), required: true, cliName: '-instance' },
      { name: 'tableRel', type: 'string', description: enhanceParameterDescription('string', 'Table Relation name.'), required: true, cliName: '-tableRel' },
      { name: 'auditDataDmlFilters', type: 'string', description: enhanceParameterDescription('string', 'Columns that should be processed. Formatted as "db.schema.table.col;..."', 'LIST'), required: false, cliName: '-auditDataDmlFilters' },
      { name: 'auditSkipDmlFilters', type: 'string', description: enhanceParameterDescription('string', 'Columns that should be skipped. Formatted as "db.schema.table.col;..."', 'LIST'), required: false, cliName: '-auditSkipDmlFilters' },
      { name: 'includeObjectGroups', type: 'string', description: enhanceParameterDescription('string', 'Object groups that should be skipped. Comma-separated names.', 'LIST'), required: false, cliName: '-includeObjectGroups' },
      { name: 'excludeObjectGroups', type: 'string', description: enhanceParameterDescription('string', 'Object groups that should be processed. Comma-separated names of groups.', 'LIST'), required: false, cliName: '-excludeObjectGroups' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'Instance login.'), required: false, cliName: '-login' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'Instance password.'), required: false, cliName: '-password' },
      { name: 'sysDba', type: 'string', description: enhanceParameterDescription('string', 'Connect to Oracle instance with SYSDBA privileges.'), required: false, cliName: '-sysDba' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_azure_remove_unused_servers',
    description: 'Adds a periodic task for removal of unused MS Azure servers. (CLI Guide 21.16)',
    baseCommand: 'addPerAzureRemoveServ',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this task.'), required: true, cliName: '-name' },
      ...commonPeriodicTaskParams,
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_kubernetes_remove_unused_servers',
    description: 'Adds a periodic task for removal of unused Kubernetes servers. (CLI Guide 21.18)',
    baseCommand: 'addPerKuberRemoveServ',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this task.'), required: true, cliName: '-name' },
      ...commonPeriodicTaskParams,
      { name: 'namespace', type: 'string', description: enhanceParameterDescription('string', 'Namespace.'), required: true, cliName: '-namespace' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_db_user_synchronization',
    description: 'Adds a periodic task to download a list of database users from a target database. (CLI Guide 21.20)',
    baseCommand: 'addPerDbUserSync',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this task.'), required: true, cliName: '-name' },
      ...commonPeriodicTaskParams,
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance name to download a user list for.'), required: true, cliName: '-instance' },
      { name: 'distrByResp', type: 'string', description: enhanceParameterDescription('string', 'Distribute by responsibilities (true | false). Only for Oracle EBS Source of User Type.'), required: false, cliName: '-distrByResp' },
      { name: 'ldapSearchFilter', type: 'string', description: enhanceParameterDescription('string', 'Search Filter for LDAP.'), required: false, cliName: '-ldapSearchFilter' },
      { name: 'ldapServer', type: 'string', description: enhanceParameterDescription('string', 'LDAP server name.'), required: false, cliName: '-ldapServer' },
      { name: 'ldapUserNameAttr', type: 'string', description: enhanceParameterDescription('string', 'User Name attribute for LDAP.'), required: false, cliName: '-ldapUserNameAttr' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'DB Instance login.'), required: false, cliName: '-login' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'Instance password.'), required: false, cliName: '-password' },
      { name: 'responsibilities', type: 'string', description: enhanceParameterDescription('string', 'Database responsibilities. Comma-separated names of roles. Only for Oracle EBS Source.', 'LIST'), required: false, cliName: '-responsibilities' },
      { name: 'roles', type: 'string', description: enhanceParameterDescription('string', 'Database roles. Comma-separated names of roles. Only for MSSQL, MySQL, Oracle, PostgreSQL, Redshift.', 'LIST'), required: false, cliName: '-roles' },
      { name: 'sysDba', type: 'string', description: enhanceParameterDescription('string', 'Connect to Oracle instance with SYSDBA privileges (true | false).'), required: false, cliName: '-sysDba' },
      { name: 'userGroup', type: 'string', description: enhanceParameterDescription('string', 'User Group name.'), required: true, cliName: '-userGroup' },
      { name: 'userSource', type: 'string', description: enhanceParameterDescription('string', 'Source of Users: Database, LDAP, Oracle EBS, SAP ECC.', 'ENUM'), required: false, cliName: '-userSource' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_aws_remove_unused_servers',
    description: 'Adds a periodic task for removal of unused AWS servers. (CLI Guide N/A - inferred)',
    baseCommand: 'addPerAWSRemoveServ',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this task.'), required: true, cliName: '-name' },
      ...commonPeriodicTaskParams,
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_aws_s3_crawler',
    description: 'Adds an AWS S3 Crawler periodic task. (CLI Guide N/A - inferred)',
    baseCommand: 'addPerAwsS3Crawler',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this task.'), required: true, cliName: '-name' },
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Database Instance Name for AWS S3 Crawler Periodic Task.'), required: true, cliName: '-instance' },
      ...commonPeriodicTaskParams,
      { name: 'crawlValuesJson', type: 'string', description: enhanceParameterDescription('string', 'JSON file that contains Values to crawl.', 'FILE_PATH'), required: false, cliName: '-crawlValuesJson' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'Access Key.'), required: false, cliName: '-login' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'Secret Key.'), required: false, cliName: '-password' },
      { name: 'roleArnJson', type: 'string', description: enhanceParameterDescription('string', 'JSON file that contains Cross-Account-Role ARN settings.', 'FILE_PATH'), required: false, cliName: '-roleArnJson' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_transfer_audit_to_elasticsearch',
    description: 'Adds a Transfer Audit to Elasticsearch periodic task. (CLI Guide N/A - inferred)',
    baseCommand: 'addPerTransferAuditToElasticsearch',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this task.'), required: true, cliName: '-name' },
      ...commonPeriodicTaskParams,
      { name: 'beginDate', type: 'string', description: enhanceParameterDescription('string', 'Starting date to include in a report. Date format: yyyy-MM-dd HH:mm:ss.', 'DATETIME'), required: false, cliName: '-beginDate' },
      { name: 'endDate', type: 'string', description: enhanceParameterDescription('string', 'The ending date to report on. Date format: yyyy-MM-dd HH:mm:ss.', 'DATETIME'), required: false, cliName: '-endDate' },
      { name: 'numberOfEvents', type: 'string', description: enhanceParameterDescription('string', 'Quantity of transferable events per iteration.'), required: false, cliName: '-numberOfEvents' },
      { name: 'reportPeriod', type: 'string', description: enhanceParameterDescription('string', 'Reporting period: <currentDay | currentWeek | currentMonth | lastNDay | lastNWeek | lastNMonth | manual>.', 'ENUM'), required: false, cliName: '-reportPeriod' },
      { name: 'reportPeriodValue', type: 'string', description: enhanceParameterDescription('string', 'Reporting period value. It equal to 1 by default.'), required: false, cliName: '-reportPeriodValue' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_test_bucket_accessibility',
    description: 'Adds a periodic task for Test Bucket Accessibility. (CLI Guide 21.22)',
    baseCommand: 'addPerTestBucketAccess',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for this task.'), required: true, cliName: '-name' },
      ...commonPeriodicTaskParams,
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance Name for Test Bucket Accessibility.'), required: true, cliName: '-instance' },
      { name: 'crawlerTasks', type: 'string', description: enhanceParameterDescription('string', 'Crawler Tasks separated by comma.', 'LIST'), required: false, cliName: '-crawlerTasks' },
      { name: 'skipDuplicates', type: 'string', description: enhanceParameterDescription('string', 'Skip duplicate buckets (true | false).'), required: false, cliName: '-skipDuplicates' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_oracle_update_users_properties',
    description: "Add Periodic Task of type 'Oracle Update Users Properties'",
    baseCommand: 'addPerOracleUpdateUsersProperties',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
      { name: 'instances', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated list of Oracle Instance Names', 'LIST'), required: true, cliName: '-instances' },
      ...commonPeriodicTaskParams,
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_add_command_shell',
    description: 'Add Periodic Command Shell Task',
    baseCommand: 'addPerCommandShell',
    params: [
      { name: 'name', type: 'string', description: 'Logical Name', required: true, cliName: '-name' },
      { name: 'command', type: 'string', description: 'Shell command to execute', required: false, cliName: '-command' },
      { name: 'disableOutput', type: 'string', description: 'Disable command output (true|false)', required: false, cliName: '-disableOutput' },
      ...commonPeriodicTaskParams,
    ],
    category: 'Periodic Task',
  },
  // UPDATE commands
  {
    toolName: 'periodic_task_update_clean_audit',
    description: 'Updates an existing periodic clean audit task. (CLI Guide 21.2)',
    baseCommand: 'updatePerCleanAudit',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'New name for the task.'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
      { name: 'cleanType', type: 'string', description: enhanceParameterDescription('string', 'How to clean the storage: Delete | Drop | KeepDays.', 'ENUM'), required: false, cliName: '-cleanType' },
      { name: 'keepDays', type: 'string', description: enhanceParameterDescription('string', 'Keep auditing data, days (used with cleanType KeepDays).'), required: false, cliName: '-keepDays' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_backup_dictionary',
    description: 'Updates an existing Periodic Backup Dictionary task. (CLI Guide 21.8)',
    baseCommand: 'updatePerBackupDictionary',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'New name for the task.'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
      { name: 'backupName', type: 'string', description: enhanceParameterDescription('string', 'Logical name of the backup.'), required: false, cliName: '-backupName' },
      { name: 'backupObjects', type: 'string', description: enhanceParameterDescription('string', 'Backup DataSunrise Objects (true | false).'), required: false, cliName: '-backupObjects', defaultValue: true },
      { name: 'backupSettings', type: 'string', description: enhanceParameterDescription('string', 'Backup DataSunrise Settings (true | false).'), required: false, cliName: '-backupSettings', defaultValue: true },
      { name: 'backupUsers', type: 'string', description: enhanceParameterDescription('string', 'Backup DataSunrise Users (true | false).'), required: false, cliName: '-backupUsers', defaultValue: true },
      { name: 'command', type: 'string', description: enhanceParameterDescription('string', 'Execute external command after backing up.'), required: false, cliName: '-command' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_user_behavior',
    description: 'Updates an existing User Behavior Periodic task. (CLI Guide 21.10)',
    baseCommand: 'updatePerUserBehavior',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'New name for the task.'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
      { name: 'generateReport', type: 'string', description: enhanceParameterDescription('string', 'Generate a report (true | false).'), required: false, cliName: '-generateReport' },
      { name: 'reportFormat', type: 'string', description: enhanceParameterDescription('string', 'Report file format (csv | pdf | json).', 'ENUM'), required: false, cliName: '-reportFormat' },
      { name: 'compressType', type: 'string', description: enhanceParameterDescription('string', 'Report compress type (no | zip | gzip).', 'ENUM'), required: false, cliName: '-compressType' },
      { name: 'trStartDate', type: 'string', description: enhanceParameterDescription('string', 'Training Start Date. Date format: yyyy-MM-dd HH:mm:ss.', 'DATETIME'), required: false, cliName: '-trStartDate' },
      { name: 'trEndDate', type: 'string', description: enhanceParameterDescription('string', 'Training End Date. Date format: yyyy-MM-dd HH:mm:ss.', 'DATETIME'), required: false, cliName: '-trEndDate' },
      { name: 'number', type: 'string', description: enhanceParameterDescription('string', 'Number value for lastNDay, lastNWeek, lastNMonth (for repPerType).'), required: false, cliName: '-number' },
      { name: 'repPerType', type: 'string', description: enhanceParameterDescription('string', 'Reporting Period Type: lastNDay | lastNWeek | lastNMonth | currentMonth | currentWeek | currentDay | manual.', 'ENUM'), required: false, cliName: '-repPerType' },
      { name: 'pdfStyle', type: 'string', description: enhanceParameterDescription('string', 'PDF report style (form | table). Only applies when reportFormat is PDF.'), required: false, cliName: '-pdfStyle' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_ddl_table_relation_learning',
    description: 'Updates an existing DDL Table Relation Learning periodic task. (CLI Guide 21.15)',
    baseCommand: 'updateDDLTabRelLearnPerTask',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name of the Task'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance Name'), required: false, cliName: '-instance' },
      { name: 'tableRel', type: 'string', description: enhanceParameterDescription('string', 'Table Relation name'), required: false, cliName: '-tableRel' },
      { name: 'analyzeProcAndFunc', type: 'string', description: enhanceParameterDescription('string', 'Analyze Stored Procedures and Functions DDLs (true | false)'), required: false, cliName: '-analyzeProcAndFunc' },
      { name: 'analyzeView', type: 'string', description: enhanceParameterDescription('string', 'Analyze View DDLs (true | false)'), required: false, cliName: '-analyzeView' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'Instance login'), required: false, cliName: '-login' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'Instance password'), required: false, cliName: '-password' },
      { name: 'sysDba', type: 'string', description: enhanceParameterDescription('string', 'Connect to Oracle instance with SYSDBA privileges (true | false)'), required: false, cliName: '-sysDba' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_vulnerability_assessment',
    description: 'Updates a periodic task for Vulnerability Assessment. (CLI Guide 21.12)',
    baseCommand: 'updatePerVulnAssessment',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name of the Task'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
      { name: 'instances', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated DB instances. Leave it blank if you want to add all instances'), required: false, cliName: '-instances' },
      { name: 'subscribers', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated SMTP subscribers names. Leave it blank if you want to remove current subscribers'), required: false, cliName: '-subscribers' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_update_metadata',
    description: 'Updates an Update metadata periodic task. (CLI Guide 21.6)',
    baseCommand: 'updatePerUpdateMetadata',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name of the Task'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance Name for Update Metadata'), required: false, cliName: '-instance' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_data_discovery',
    description: 'Updates an existing Data Discovery periodic task. (CLI Guide 18.11)',
    baseCommand: 'updatePerDiscovery',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name of the Task'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
      ...commonReportParams.map(p => ({ ...p, required: false })),
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance Name for Data Discovery'), required: false, cliName: '-instance' },
      { name: 'pdfStyle', type: 'string', description: enhanceParameterDescription('string', 'PDF report style (form | table). Default is form. Only applies when reportFormat is PDF'), required: false, cliName: '-pdfStyle' },
      { name: 'searchByInfoTypes', type: 'string', description: enhanceParameterDescription('string', 'Information Types separated by ; by default', 'LIST'), required: false, cliName: '-searchByInfoTypes' },
      { name: 'searchByStandards', type: 'string', description: enhanceParameterDescription('string', 'Security Standards separated by ; by default', 'LIST'), required: false, cliName: '-searchByStandards' },
      { name: 'additionalMetrics', type: 'string', description: enhanceParameterDescription('string', 'Enable Additional Metrics (true | false)'), required: false, cliName: '-additionalMetrics' },
      { name: 'analysedRow', type: 'string', description: enhanceParameterDescription('string', 'Analysed Row Count'), required: false, cliName: '-analysedRow' },
      { name: 'enableStatDataSpeed', type: 'string', description: enhanceParameterDescription('string', 'Enable statistics on data processing speed for S3 instance (true | false)'), required: false, cliName: '-enableStatDataSpeed' },
      { name: 'enableStatOnAttr', type: 'string', description: enhanceParameterDescription('string', 'Enable statistics on attributes (true | false)'), required: false, cliName: '-enableStatOnAttr' },
      { name: 'excludedTables', type: 'string', description: enhanceParameterDescription('string', 'Excluded Discovery Schemas, Tables, Columns formatted like orcl.alex.customers.id;orcl.bob.orders.id. For Aurora MySQL, MariaDB, MySQL, Teradata format is alex.customers.id;bob.orders.id', 'LIST'), required: false, cliName: '-excludedTables' },
      { name: 'excludeS3Objects', type: 'string', description: enhanceParameterDescription('string', 'Path to the folder that should be excluded from the search for S3 instance. Note that it should start with "/". Paths separated by ; by default. Example: /bucket1/folder1/folder2/;/bucket2/', 'LIST'), required: false, cliName: '-excludeS3Objects' },
      { name: 'externalCommand', type: 'string', description: enhanceParameterDescription('string', 'External command'), required: false, cliName: '-externalCommand' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'database user login'), required: false, cliName: '-login' },
      { name: 'maxPerNull', type: 'string', description: enhanceParameterDescription('string', 'Max Percentage of NULL'), required: false, cliName: '-maxPerNull' },
      { name: 'minPerMatch', type: 'string', description: enhanceParameterDescription('string', 'Min Percentage of match'), required: false, cliName: '-minPerMatch' },
      { name: 'objGroup', type: 'string', description: enhanceParameterDescription('string', 'Save Search Results in an Object Group: (<IdName> | false)'), required: false, cliName: '-objGroup' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'database user password'), required: false, cliName: '-password' },
      { name: 'reportColumns', type: 'string', description: enhanceParameterDescription('string', "columns in report separated by ',' by default (see -blockSeparator). After ':' Name in Report can be specified. For example: Col1:ColInReport1,Col2,Col3:ColInReport3 (see 'nameSeparator' option).", 'LIST'), required: false, cliName: '-reportColumns' },
      { name: 'searchDb', type: 'string', description: enhanceParameterDescription('string', 'Database for search. Empty value if database is not specified.'), required: false, cliName: '-searchDb' },
      { name: 'searchS3Objects', type: 'string', description: enhanceParameterDescription('string', 'Path to the folder that should be searched for S3 instance. Note each path should start with "/". Paths separated by ; by default. Example: /bucket1/folder1/folder2/;/bucket2/ All buckets and their subfolders will be scanned if parameter is empty', 'LIST'), required: false, cliName: '-searchS3Objects' },
      { name: 'searchSchema', type: 'string', description: enhanceParameterDescription('string', 'Schema for search. Empty value if schema is not specified.'), required: false, cliName: '-searchSchema' },
      { name: 'searchTable', type: 'string', description: enhanceParameterDescription('string', 'Table for search. Empty value if table is not specified.'), required: false, cliName: '-searchTable' },
      { name: 'skipNull', type: 'string', description: enhanceParameterDescription('string', 'Skip Null (true | false)'), required: false, cliName: '-skipNull' },
      { name: 'withoutCredentials', type: 'boolean', description: enhanceParameterDescription('boolean', 'do not check database credentials'), required: false, cliName: '-withoutCredentials' },
      { name: 'writeToSyslog', type: 'string', description: enhanceParameterDescription('string', 'Write messages to syslog (true | false)'), required: false, cliName: '-writeToSyslog' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_health_check',
    description: 'Updates a periodic task for Health check. (CLI Guide 21.4)',
    baseCommand: 'updatePerHealthCheck',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name of the Task'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance Name of Health Check'), required: false, cliName: '-instance' },
      { name: 'lbAddress', type: 'string', description: enhanceParameterDescription('string', 'Load Balancer Public Address'), required: false, cliName: '-lbAddress' },
      { name: 'lbPort', type: 'string', description: enhanceParameterDescription('string', 'Load Balancer Port', 'PORT'), required: false, cliName: '-lbPort' },
      { name: 'sendErrors', type: 'string', description: enhanceParameterDescription('string', 'Send errors to Events (true | false)'), required: false, cliName: '-sendErrors' },
      { name: 'testMethod', type: 'string', description: enhanceParameterDescription('string', 'Proxy Testing Method: ExecSys || WebCheck', 'ENUM'), required: false, cliName: '-testMethod' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_azure_remove_unused_servers',
    description: 'Updates a periodic task for removal of unused MS Azure servers. (CLI Guide 21.17)',
    baseCommand: 'updatePerAzureRemoveServ',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name of the Task'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_kubernetes_remove_unused_servers',
    description: 'Updates an existing Kubernetes Remove Unused Servers task. (CLI Guide 21.19)',
    baseCommand: 'updatePerKuberRemoveServ',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name of the Task'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
      { name: 'namespace', type: 'string', description: enhanceParameterDescription('string', 'Namespace'), required: false, cliName: '-namespace' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_db_user_synchronization',
    description: 'Updates an existing periodic task to download a list of database users from a target database. (CLI Guide 21.21)',
    baseCommand: 'updatePerDbUserSync',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name of the Task'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance Name for Database User Synchronization'), required: false, cliName: '-instance' },
      { name: 'distrByResp', type: 'string', description: enhanceParameterDescription('string', 'Distribute by responsibilities. Only for Oracle EBS Source of Users Type (true | false)'), required: false, cliName: '-distrByResp' },
      { name: 'ldapSearchFilter', type: 'string', description: enhanceParameterDescription('string', 'Search Filter'), required: false, cliName: '-ldapSearchFilter' },
      { name: 'ldapServer', type: 'string', description: enhanceParameterDescription('string', 'LDAP Server'), required: false, cliName: '-ldapServer' },
      { name: 'ldapUserNameAttr', type: 'string', description: enhanceParameterDescription('string', 'User Name attribute'), required: false, cliName: '-ldapUserNameAttr' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'Instance login'), required: false, cliName: '-login' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'Instance password'), required: false, cliName: '-password' },
      { name: 'responsibilities', type: 'string', description: enhanceParameterDescription('string', 'Database responsibilities. Comma-separated names of roles. Only for Oracle EBS Source of Users Type', 'LIST'), required: false, cliName: '-responsibilities' },
      { name: 'roles', type: 'string', description: enhanceParameterDescription('string', 'Database roles. Comma-separated names of roles. Only for MSSQL, MySQL, Oracle, PostgreSQL, Redshift', 'LIST'), required: false, cliName: '-roles' },
      { name: 'sysDba', type: 'string', description: enhanceParameterDescription('string', 'Connect to Oracle instance with SYSDBA privileges (true | false)'), required: false, cliName: '-sysDba' },
      { name: 'userGroup', type: 'string', description: enhanceParameterDescription('string', 'User Group'), required: false, cliName: '-userGroup' },
      { name: 'userSource', type: 'string', description: enhanceParameterDescription('string', 'Source of Users: Database, LDAP, Oracle EBS, SAP ECC', 'ENUM'), required: false, cliName: '-userSource' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_aws_remove_unused_servers',
    description: 'Updates an existing AWS Remove Unused Servers periodic task. (CLI Guide N/A - inferred)',
    baseCommand: 'updatePerAWSRemoveServ',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name of the Task'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_aws_s3_crawler',
    description: 'Updates an AWS S3 Crawler periodic task. (CLI Guide N/A - inferred)',
    baseCommand: 'updatePerAwsS3Crawler',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name of the Task'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Database Instance Name for AWS S3 Crawler Periodic Task'), required: false, cliName: '-instance' },
      { name: 'crawlValuesJson', type: 'string', description: enhanceParameterDescription('string', 'JSON file that contains Values to crawl.', 'FILE_PATH'), required: false, cliName: '-crawlValuesJson' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'Access Key'), required: false, cliName: '-login' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'Secret Key'), required: false, cliName: '-password' },
      { name: 'roleArnJson', type: 'string', description: enhanceParameterDescription('string', 'JSON file that contains Cross-Account-Role ARN settings.', 'FILE_PATH'), required: false, cliName: '-roleArnJson' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_transfer_audit_to_elasticsearch',
    description: 'Updates a Transfer Audit to Elasticsearch periodic task. (CLI Guide N/A - inferred)',
    baseCommand: 'updatePerTransferAuditToElasticsearch',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name of the Task'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
      { name: 'beginDate', type: 'string', description: enhanceParameterDescription('string', 'Starting date to include in a report. Date format: yyyy-MM-dd HH:mm:ss', 'DATETIME'), required: false, cliName: '-beginDate' },
      { name: 'endDate', type: 'string', description: enhanceParameterDescription('string', 'The ending date to report on. Date format: yyyy-MM-dd HH:mm:ss', 'DATETIME'), required: false, cliName: '-endDate' },
      { name: 'numberOfEvents', type: 'string', description: enhanceParameterDescription('string', 'Quantity of transferable events per iteration'), required: false, cliName: '-numberOfEvents' },
      { name: 'reportPeriod', type: 'string', description: enhanceParameterDescription('string', 'Reporting period: <currentDay | currentWeek | currentMonth | lastNDay | lastNWeek | lastNMonth | manual>', 'ENUM'), required: false, cliName: '-reportPeriod' },
      { name: 'reportPeriodValue', type: 'string', description: enhanceParameterDescription('string', 'Reporting period value. Default value is 1'), required: false, cliName: '-reportPeriodValue' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_query_history_table_relation_learning',
    description: 'Updates an existing Query History Table Relation Learning periodic task. (CLI Guide N/A - inferred from add command and usage pattern)',
    baseCommand: 'updateQueryHisTabRelLearnPerTask',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name of the Task'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance Name'), required: false, cliName: '-instance' },
      { name: 'tableRel', type: 'string', description: enhanceParameterDescription('string', 'Table Relation name'), required: false, cliName: '-tableRel' },
      { name: 'auditDataDmlFilters', type: 'string', description: enhanceParameterDescription('string', 'Columns that should be processed. Columns formatted like orcl.alex.customers.id;orcl.bob.orders.id', 'LIST'), required: false, cliName: '-auditDataDmlFilters' },
      { name: 'auditSkipDmlFilters', type: 'string', description: enhanceParameterDescription('string', 'Columns that should be skipped. columns formatted like orcl.alex.customers.id;orcl.bob.orders.id', 'LIST'), required: false, cliName: '-auditSkipDmlFilters' },
      { name: 'excludeObjectGroups', type: 'string', description: enhanceParameterDescription('string', 'Object groups that should be processed. Comma-separated names of groups', 'LIST'), required: false, cliName: '-excludeObjectGroups' },
      { name: 'includeObjectGroups', type: 'string', description: enhanceParameterDescription('string', 'Object groups that should be skipped. Comma-separated names of groups', 'LIST'), required: false, cliName: '-includeObjectGroups' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'Instance login'), required: false, cliName: '-login' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'Instance password'), required: false, cliName: '-password' },
      { name: 'sysDba', type: 'string', description: enhanceParameterDescription('string', 'Connect to Oracle instance with SYSDBA privileges (true | false)'), required: false, cliName: '-sysDba' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_command_shell',
    description: 'Update Periodic Command Shell Task',
    baseCommand: 'updatePerCommandShell',
    params: [
      { name: 'name', type: 'string', description: 'Logical Name', required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: 'new logical name of the Task', required: false, cliName: '-newName' },
      { name: 'command', type: 'string', description: 'Shell command to execute', required: false, cliName: '-command' },
      { name: 'disableOutput', type: 'string', description: 'Disable command output (true|false)', required: false, cliName: '-disableOutput' },
      ...optionalPeriodicTaskParams,
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_oracle_update_users_properties',
    description: "Update Periodic Task of type 'Oracle Update Users Properties'",
    baseCommand: 'updatePerOracleUpdateUsersProperties',
    params: [
      { name: 'name', type: 'string', description: 'Logical Name', required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: 'new logical name of the Task', required: false, cliName: '-newName' },
      { name: 'instances', type: 'string', description: 'Comma-separated list of Oracle Instance Names', required: false, cliName: '-instances' },
      ...optionalPeriodicTaskParams,
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_update_test_bucket_accessibility',
    description: 'Updates a periodic task for Test Bucket Accessibility. (CLI Guide 21.23)',
    baseCommand: 'updatePerTestBucketAccess',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the task to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name of the Task'), required: false, cliName: '-newName' },
      ...optionalPeriodicTaskParams,
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance Name for Test Bucket Accessibility'), required: false, cliName: '-instance' },
      { name: 'crawlerTasks', type: 'string', description: enhanceParameterDescription('string', 'Crawler Tasks separated by comma.', 'LIST'), required: false, cliName: '-crawlerTasks' },
      { name: 'skipDuplicates', type: 'string', description: enhanceParameterDescription('string', 'skip duplicate buckets (true | false)'), required: false, cliName: '-skipDuplicates' },
    ],
    category: 'Periodic Task',
  },
  // SHOW command
  {
    toolName: 'periodic_task_show_one',
    description: 'Show Periodic Task',
    baseCommand: 'showPerTask',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Task Name'), required: true, cliName: '-name' },
      { name: 'taskType', type: 'string', description: enhanceParameterDescription('string', `Report Task Type: ${periodicTaskTypes}`, 'ENUM'), required: true, cliName: '-taskType' },
    ],
    category: 'Periodic Task',
  },
  // DELETE command
  {
    toolName: 'periodic_task_delete',
    description: 'Delete Periodic Task',
    baseCommand: 'delPerTask',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Task Name'), required: true, cliName: '-name' },
      { name: 'taskType', type: 'string', description: enhanceParameterDescription('string', `Report Task Type: ${periodicTaskTypes}`, 'ENUM'), required: true, cliName: '-taskType' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_cancel',
    description: 'Cancel Periodic Task or Report Generation',
    baseCommand: 'cancelTask',
    params: [
      { name: 'taskId', type: 'string', description: enhanceParameterDescription('string', 'TaskID to cancel'), required: true, cliName: '-taskId' },
    ],
    category: 'Periodic Task',
  },
  {
    toolName: 'periodic_task_execute',
    description: 'Execute Periodic Task or Report Generation Manually',
    baseCommand: 'executePeriodicTask',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Periodic task name or report generation task name'), required: true, cliName: '-name' },
      { name: 'continueTaskId', type: 'string', description: enhanceParameterDescription('string', 'Continue task ID'), required: false, cliName: '-continueTaskId' },
    ],
    category: 'Periodic Task',
  },
];
