import { CliCommand } from './types.js';
import { enhanceParameterDescription } from '../description_helpers.js';

const commonReportGenParams: CliCommand['params'] = [
  { name: 'startDate', type: 'string', description: enhanceParameterDescription('string', 'Start Date: yyyy-MM-dd HH:mm:ss'), required: false, cliName: '-startDate' },
  { name: 'compressType', type: 'string', description: enhanceParameterDescription('string', 'compress type (no | zip | gzip)', 'ENUM'), required: false, cliName: '-compressType' },
  { name: 'days', type: 'string', description: enhanceParameterDescription('string', 'Month Days (1...31 | last) for Startup Separated by [;]', 'LIST'), required: false, cliName: '-days' },
  { name: 'delResults', type: 'string', description: enhanceParameterDescription('string', 'Remove Old Results (true | false)'), required: false, cliName: '-delResults' },
  { name: 'dsServer', type: 'string', description: enhanceParameterDescription('string', 'DataSunrise <server name> | any'), required: false, cliName: '-dsServer' },
  { name: 'externalCommand', type: 'string', description: enhanceParameterDescription('string', 'External command'), required: false, cliName: '-externalCommand' },
  { name: 'freqAmount', type: 'string', description: enhanceParameterDescription('string', 'Frequency of performing the task'), required: false, cliName: '-freqAmount' },
  { name: 'freqUnit', type: 'string', description: enhanceParameterDescription('string', 'Startup Frequency: Manual | Once | Minutely | Hourly | Daily | Weekly | Monthly', 'ENUM'), required: false, cliName: '-freqUnit' },
  { name: 'generateReport', type: 'string', description: enhanceParameterDescription('string', 'Generate report. Default value is false.'), required: false, cliName: '-generateReport' },
  { name: 'keepAmount', type: 'string', description: enhanceParameterDescription('string', 'Number of results to keep'), required: false, cliName: '-keepAmount' },
  { name: 'keepUnit', type: 'string', description: enhanceParameterDescription('string', 'Keep Results for: Hours | Days | Weeks | Months', 'ENUM'), required: false, cliName: '-keepUnit' },
  { name: 'months', type: 'string', description: enhanceParameterDescription('string', 'Months for Startup Separated by [;] (jan;feb;mar;apr;may;jun;jul;aug;sep;oct;nov;dec)', 'LIST'), required: false, cliName: '-months' },
  { name: 'reportFormat', type: 'string', description: enhanceParameterDescription('string', 'report format (csv | pdf | json)', 'ENUM'), required: false, cliName: '-reportFormat' },
  { name: 'subscribers', type: 'string', description: enhanceParameterDescription('string', 'Subscribers separated by \'-blockSeparator\' option', 'LIST'), required: false, cliName: '-subscribers' },
  { name: 'weekDays', type: 'string', description: enhanceParameterDescription('string', 'Day of Week for Startup Separated by [;] (mo;tu;we;th;fr;sa;su)', 'LIST'), required: false, cliName: '-weekDays' },
  { name: 'writeToSyslog', type: 'string', description: enhanceParameterDescription('string', 'Write messages to syslog (true | false)'), required: false, cliName: '-writeToSyslog' },
  { name: 'pdfStyle', type: 'string', description: enhanceParameterDescription('string', 'PDF report style (form | table). Default is form. Only applies when reportFormat is PDF'), required: false, cliName: '-pdfStyle' },
  { name: 'blockSeparator', type: 'string', description: enhanceParameterDescription('string', 'block separator. Default is ,'), required: false, cliName: '-blockSeparator' },
  { name: 'nameSeparator', type: 'string', description: enhanceParameterDescription('string', 'name separator. Default is :'), required: false, cliName: '-nameSeparator' },
];

const reportGenFilteringParams: CliCommand['params'] = [
    { name: 'beginDate', type: 'string', description: enhanceParameterDescription('string', 'Starting date to include in a report. Date format: yyyy-MM-dd HH:mm:ss', 'DATETIME'), required: false, cliName: '-beginDate' },
    { name: 'dataFilter', type: 'string', description: enhanceParameterDescription('string', 'Data Filter'), required: false, cliName: '-dataFilter' },
    { name: 'endDate', type: 'string', description: enhanceParameterDescription('string', 'The ending date to report on. Date format: yyyy-MM-dd HH:mm:ss', 'DATETIME'), required: false, cliName: '-endDate' },
    { name: 'groupingPeriod', type: 'string', description: enhanceParameterDescription('string', 'Grouping Period, in minutes.'), required: false, cliName: '-groupingPeriod' },
    { name: 'instances', type: 'string', description: enhanceParameterDescription('string', 'List of Database Instances, separated by a block separator. Object Groups can be specified after an instance name, separated by a name separator. E.g., Inst1:ObjGr1,Inst2:ObjGr2.'), required: false, cliName: '-instances' },
    { name: 'queryLengthLimit', type: 'string', description: enhanceParameterDescription('string', 'Query length limit.'), required: false, cliName: '-queryLengthLimit' },
    { name: 'queryTypes', type: 'string', description: enhanceParameterDescription('string', 'Query Types separated by a block separator. Use \'showQueryTypes\' to see available types.'), required: false, cliName: '-queryTypes' },
    { name: 'reportColumns', type: 'string', description: enhanceParameterDescription('string', 'Columns to include in the report, separated by a block separator. Custom column names can be specified after a name separator. E.g., Col1:ColInReport1,Col2,Col3:ColInReport3.'), required: false, cliName: '-reportColumns' },
    { name: 'reportPeriod', type: 'string', description: enhanceParameterDescription('string', 'Reporting period (currentDay | currentWeek | currentMonth | lastNDay | lastNWeek | lastNMonth | manual).', 'ENUM'), required: false, cliName: '-reportPeriod' },
    { name: 'reportPeriodValue', type: 'string', description: enhanceParameterDescription('string', 'Value for the reporting period (e.g., number of days for lastNDay). Default is 1.'), required: false, cliName: '-reportPeriodValue' },
    { name: 'requestsPerGroupPeriod', type: 'string', description: enhanceParameterDescription('string', 'Condition for requests per grouping period (Any | Less Than | Equal | More Than).', 'ENUM'), required: false, cliName: '-requestsPerGroupPeriod' },
    { name: 'requestsPerGroupPeriodValue', type: 'string', description: enhanceParameterDescription('string', 'Value for requests per grouping period condition.'), required: false, cliName: '-requestsPerGroupPeriodValue' },
    { name: 'rules', type: 'string', description: enhanceParameterDescription('string', 'Report on events captured by specified Rules, separated by a block separator.'), required: false, cliName: '-rules' },
    { name: 'totalNumOfReturnedRows', type: 'string', description: enhanceParameterDescription('string', 'Condition for the total number of returned rows (Any | Less Than | Equal | More Than).', 'ENUM'), required: false, cliName: '-totalNumOfReturnedRows' },
    { name: 'totalNumOfReturnedRowsValue', type: 'string', description: enhanceParameterDescription('string', 'Value for the total number of returned rows condition.'), required: false, cliName: '-totalNumOfReturnedRowsValue' },
];

export const reportGenCommands: CliCommand[] = [
  {
    toolName: 'report_gen_add_audit',
    description: 'Adds a new Audit Report generation task. Configures how audit data is filtered, formatted, and scheduled for reporting. (CLI Guide 19.1)',
    baseCommand: 'addAuditReportGen',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
      ...commonReportGenParams,
      ...reportGenFilteringParams,
      { name: 'operationsWithError', type: 'string', description: enhanceParameterDescription('string', 'Include operations with error (true | false)'), required: false, cliName: '-operationsWithError' },
    ],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_add_masking',
    description: 'Adds a new Masking Report generation task. (CLI Guide 19.5)',
    baseCommand: 'addMaskingReportGen',
    params: [
        { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
        ...commonReportGenParams,
        ...reportGenFilteringParams,
    ],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_add_security',
    description: 'Adds a new Security Report generation task. (CLI Guide 19.3)',
    baseCommand: 'addSecurityReportGen',
    params: [
        { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
        ...commonReportGenParams,
        ...reportGenFilteringParams,
    ],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_add_operation_errors',
    description: 'Adds a new Operation Errors Report generation task. (CLI Guide 19.7)',
    baseCommand: 'addOperationErrorsReportGen',
    params: [
        { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
        ...commonReportGenParams,
        ...reportGenFilteringParams,
    ],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_add_session',
    description: 'Adds a new Session Report generation task (for all sessions). (CLI Guide 19.9)',
    baseCommand: 'addSessionReportGen',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
      ...commonReportGenParams,
      { name: 'beginDate', type: 'string', description: enhanceParameterDescription('string', 'Starting date to include in a report. Date format: yyyy-MM-dd HH:mm:ss', 'DATETIME'), required: false, cliName: '-beginDate' },
      { name: 'dataFilter', type: 'string', description: enhanceParameterDescription('string', 'Data Filter'), required: false, cliName: '-dataFilter' },
      { name: 'endDate', type: 'string', description: enhanceParameterDescription('string', 'The ending date to report on. Date format: yyyy-MM-dd HH:mm:ss', 'DATETIME'), required: false, cliName: '-endDate' },
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', '(<instance name> | any)'), required: false, cliName: '-instance' },
      { name: 'reportColumns', type: 'string', description: enhanceParameterDescription('string', "columns in report separated by ',' by default (see -blockSeparator). After ':' Name in Report can be specified. For example: Col1:ColInReport1,Col2,Col3:ColInReport3 (see 'nameSeparator' option).", 'LIST'), required: false, cliName: '-reportColumns' },
      { name: 'reportPeriod', type: 'string', description: enhanceParameterDescription('string', 'Reporting period: <currentDay | currentWeek | currentMonth | lastNDay | lastNWeek | lastNMonth | manual>', 'ENUM'), required: false, cliName: '-reportPeriod' },
      { name: 'reportPeriodValue', type: 'string', description: enhanceParameterDescription('string', 'Reporting period value. Default value is 1'), required: false, cliName: '-reportPeriodValue' },
      { name: 'rules', type: 'string', description: enhanceParameterDescription('string', "Report on events captured by specified Rules separated by ','"), required: false, cliName: '-rules' },
      { name: 'sessionReportType', type: 'string', description: enhanceParameterDescription('string', 'Session Report Type (All sessions | Error sessions | Auth error sessions only)', 'ENUM'), required: false, cliName: '-sessionReportType' },
    ],
    category: 'Report Generation',
  },
   {
    toolName: 'report_gen_add_direct_session',
    description: 'Add a Direct Session Report generation task. (CLI Guide 19.13)',
    baseCommand: 'addDirectSessionReportGen',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
      ...commonReportGenParams,
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', '(<instance name> | any)'), required: false, cliName: '-instance' },
    ],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_add_system_events',
    description: 'Adds a new System Events Report generation task. (CLI Guide 19.11)',
    baseCommand: 'addSystemEventsReportGen',
    params: [
        { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
        ...commonReportGenParams,
        { name: 'beginDate', type: 'string', description: enhanceParameterDescription('string', 'Starting date to include in a report. Date format: yyyy-MM-dd HH:mm:ss', 'DATETIME'), required: false, cliName: '-beginDate' },
        { name: 'endDate', type: 'string', description: enhanceParameterDescription('string', 'The ending date to report on. Date format: yyyy-MM-dd HH:mm:ss', 'DATETIME'), required: false, cliName: '-endDate' },
        { name: 'reportColumns', type: 'string', description: enhanceParameterDescription('string', 'columns in report separated by \',\' by default (see -blockSeparator). After \':\' Name in Report can be specified. For example: Col1:ColInReport1,Col2,Col3:ColInReport3 (see \'nameSeparator\' option).', 'LIST'), required: false, cliName: '-reportColumns' },
        { name: 'reportPeriod', type: 'string', description: enhanceParameterDescription('string', 'Reporting period: <currentDay | currentWeek | currentMonth | lastNDay | lastNWeek | lastNMonth | manual>', 'ENUM'), required: false, cliName: '-reportPeriod' },
        { name: 'reportPeriodValue', type: 'string', description: enhanceParameterDescription('string', 'Reporting period value. Default value is 1'), required: false, cliName: '-reportPeriodValue' },
    ],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_add_instance_status',
    description: 'Adds a new Instances Status report generation task. (CLI Guide 19.15)',
    baseCommand: 'addInstStatusReportGen',
    params: [
        { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
        ...commonReportGenParams,
    ],
    category: 'Report Generation',
  },
  // UPDATE commands
  {
    toolName: 'report_gen_update_audit',
    description: 'Updates an existing Audit Report generation task. (CLI Guide 19.2)',
    baseCommand: 'updateAuditReportGen',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name for the Report'), required: false, cliName: '-newName' },
      ...commonReportGenParams,
      ...reportGenFilteringParams,
      { name: 'operationsWithError', type: 'string', description: enhanceParameterDescription('string', 'Include operations with error (true | false)'), required: false, cliName: '-operationsWithError' },
    ],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_update_security',
    description: 'Updates an existing Security Report generation task. (CLI Guide 19.4)',
    baseCommand: 'updateSecurityReportGen',
    params: [
        { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
        { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name for the Report'), required: false, cliName: '-newName' },
        ...commonReportGenParams,
        ...reportGenFilteringParams,
    ],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_update_masking',
    description: 'Updates an existing Masking Report generation task. (CLI Guide 19.6)',
    baseCommand: 'updateMaskingReportGen',
    params: [
        { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
        { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name for the Report'), required: false, cliName: '-newName' },
        ...commonReportGenParams,
        ...reportGenFilteringParams,
    ],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_update_operation_errors',
    description: 'Updates an existing Operation Errors Report generation task. (CLI Guide 19.8)',
    baseCommand: 'updateOperationErrorsReportGen',
    params: [
        { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
        { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name for the Report'), required: false, cliName: '-newName' },
        ...commonReportGenParams,
        ...reportGenFilteringParams,
    ],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_update_session',
    description: 'Updates an existing Session Report generation task. (CLI Guide 19.10)',
    baseCommand: 'updateSessionReportGen',
    params: [
        { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
        { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name for the Report'), required: false, cliName: '-newName' },
        ...commonReportGenParams,
        ...reportGenFilteringParams,
        { name: 'instance', type: 'string', description: enhanceParameterDescription('string', '(<instance name> | any)'), required: false, cliName: '-instance' },
        { name: 'sessionReportType', type: 'string', description: enhanceParameterDescription('string', 'Session Report Type (All sessions | Error sessions | Auth error sessions only)', 'ENUM'), required: false, cliName: '-sessionReportType' },
    ],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_update_system_events',
    description: 'Updates an existing System Events report generation task. (CLI Guide 19.12)',
    baseCommand: 'updateSystemEventsReportGen',
    params: [
        { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
        { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name for the Report'), required: false, cliName: '-newName' },
        ...commonReportGenParams,
        { name: 'beginDate', type: 'string', description: enhanceParameterDescription('string', 'Starting date to include in a report. Date format: yyyy-MM-dd HH:mm:ss', 'DATETIME'), required: false, cliName: '-beginDate' },
        { name: 'endDate', type: 'string', description: enhanceParameterDescription('string', 'The ending date to report on. Date format: yyyy-MM-dd HH:mm:ss', 'DATETIME'), required: false, cliName: '-endDate' },
        { name: 'reportColumns', type: 'string', description: enhanceParameterDescription('string', 'columns in report separated by \',\' by default (see -blockSeparator). After \':\' Name in Report can be specified. For example: Col1:ColInReport1,Col2,Col3:ColInReport3 (see \'nameSeparator\' option).', 'LIST'), required: false, cliName: '-reportColumns' },
        { name: 'reportPeriod', type: 'string', description: enhanceParameterDescription('string', 'Reporting period: <currentDay | currentWeek | currentMonth | lastNDay | lastNWeek | lastNMonth | manual>', 'ENUM'), required: false, cliName: '-reportPeriod' },
        { name: 'reportPeriodValue', type: 'string', description: enhanceParameterDescription('string', 'Reporting period value. Default value is 1'), required: false, cliName: '-reportPeriodValue' },
    ],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_update_direct_session',
    description: 'Updates an existing Direct Session Report generation task. (CLI Guide 19.14)',
    baseCommand: 'updateDirectSessionReportGen',
    params: [
        { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
        { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name for the Report'), required: false, cliName: '-newName' },
        ...commonReportGenParams,
        { name: 'instance', type: 'string', description: enhanceParameterDescription('string', '(<instance name> | any)'), required: false, cliName: '-instance' },
    ],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_update_instance_status',
    description: 'Updates an existing Instances Status report generation task. (CLI Guide 19.16)',
    baseCommand: 'updateInstStatusReportGen',
    params: [
        { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
        { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name for the Report'), required: false, cliName: '-newName' },
        ...commonReportGenParams,
    ],
    category: 'Report Generation',
  },
  // SHOW commands
  {
    toolName: 'report_gen_show_all',
    description: 'Displays all configured report generation tasks.',
    baseCommand: 'showReportsGen',
    params: [],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_show_one',
    description: 'Shows detailed information for a specific report generation task.',
    baseCommand: 'showReportGen',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Name of the report generation task to display.'), required: true, cliName: '-name' },
    ],
    category: 'Report Generation',
  },
  // DELETE command
  {
    toolName: 'report_gen_delete',
    description: 'Deletes a specified report generation task.',
    baseCommand: 'delReportGen',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Name of the report generation task to delete.'), required: true, cliName: '-name' },
    ],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_add_trans_trail_export',
    description: 'Adds a new Transaction Trail Export Report generation task. (CLI Guide N/A - new command)',
    baseCommand: 'addTransTrailExportReportGen',
    params: [
        { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name.'), required: true, cliName: '-name' },
        ...commonReportGenParams,
        ...reportGenFilteringParams,
        { name: 'operationsWithError', type: 'string', description: enhanceParameterDescription('string', 'Include operations with error (true | false)'), required: false, cliName: '-operationsWithError' },
    ],
    category: 'Report Generation',
  },
  {
    toolName: 'report_gen_update_trans_trail_export',
    description: 'Updates an existing Transaction Trail Export Report generation task.',
    baseCommand: 'updateTransTrailExportReportGen',
    params: [
        { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Logical Name'), required: true, cliName: '-name' },
        { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'new logical name for the Report'), required: false, cliName: '-newName' },
        ...commonReportGenParams,
        ...reportGenFilteringParams,
        { name: 'operationsWithError', type: 'string', description: enhanceParameterDescription('string', 'Include operations with error (true | false)'), required: false, cliName: '-operationsWithError' },
    ],
    category: 'Report Generation',
  },
];
