import { CliCommand } from './types.js';
import { enhanceParameterDescription } from '../description_helpers.js';

// Helper for common rule parameters
const commonRuleParams: CliCommand['params'] = [
  { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for the rule. If not provided, the CLI will likely prompt or error.'), required: false, cliName: '-name' },
  { name: 'dbType', type: 'string', description: enhanceParameterDescription('string', 'Database type (aurora mysql | aurora postgresql | db2 | greenplum | hive | mariadb | mysql | mssql | netezza | oracle | postgresql | redshift | teradata | sap hana | s3 | vertica | mongodb | dynamodb | impala | cassandra | neo4j | sybase | snowflake). Omit this parameter for all (any) database types', 'ENUM'), required: false, cliName: '-dbType' },
  { name: 'enable', type: 'string', description: enhanceParameterDescription('string', 'Enable or disable the rule (true | false).'), required: false, cliName: '-enable' },
  { name: 'comment', type: 'string', description: enhanceParameterDescription('string', 'Descriptive comment for the rule.'), required: false, cliName: '-comment' },
  { name: 'schedule', type: 'string', description: enhanceParameterDescription('string', 'Name of a schedule to apply this rule, or "no".'), required: false, cliName: '-schedule' },
  { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Filter by database instance name or "any".'), required: false, cliName: '-instance' },
  { name: 'app', type: 'string', description: enhanceParameterDescription('string', 'Filter by client application name (can be regexp like "{regexp}name").'), required: false, cliName: '-app' },
  { name: 'addUsers', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated DB users to apply rule to.', 'LIST'), required: false, cliName: '-addUsers' },
  { name: 'addUserGroups', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated DB user groups.', 'LIST'), required: false, cliName: '-addUserGroups' },
  { name: 'addOsUsers', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated OS users.', 'LIST'), required: false, cliName: '-addOsUsers' },
  { name: 'addOsUserGroups', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated OS user groups.', 'LIST'), required: false, cliName: '-addOsUserGroups' },
  { name: 'addHosts', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated client hosts/IPs.', 'LIST'), required: false, cliName: '-addHosts' },
  { name: 'addHostGroups', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated client host groups.', 'LIST'), required: false, cliName: '-addHostGroups' },
  { name: 'checkNextRule', type: 'string', description: enhanceParameterDescription('string', 'Specify "true" or "false". If "false", rule processing stops if this rule matches. If "true", subsequent rules are evaluated.'), required: false, cliName: '-checkNextRule' },
  { name: 'addSubscribers', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated subscriber names for notification.', 'LIST'), required: false, cliName: '-addSubscribers' },
  { name: 'sysLogGr', type: 'string', description: enhanceParameterDescription('string', 'CEF Group name to send event data to for syslog/SIEM, or "no".'), required: false, cliName: '-sysLogGr' },
  { name: 'logInStorage', type: 'string', description: enhanceParameterDescription('string', 'Log the event in DataSunrise internal audit storage (true | false).'), required: false, cliName: '-logInStorage' },
];

const commonLearnRuleParams: CliCommand['params'] = commonRuleParams.filter(p => !['addSubscribers', 'sysLogGr', 'logInStorage'].includes(p.name));

const sqlFilteringParams: CliCommand['params'] = [
  { name: 'intercSqlSelect', type: 'string', description: enhanceParameterDescription('string', 'Intercept SELECT statements (true | false).'), required: false, cliName: '-intercSqlSelect' },
  { name: 'intercSqlSelectWJ', type: 'string', description: enhanceParameterDescription('string', 'Intercept SELECT in WHERE & JOIN statements (true | false).'), required: false, cliName: '-intercSqlSelectWJ' },
  { name: 'intercSqlSelectWithoutFrom', type: 'string', description: enhanceParameterDescription('string', 'Intercept SELECT without FROM statements (true | false).'), required: false, cliName: '-intercSqlSelectWithoutFrom' },
  { name: 'intercSqlInsert', type: 'string', description: enhanceParameterDescription('string', 'Intercept INSERT statements (true | false).'), required: false, cliName: '-intercSqlInsert' },
  { name: 'intercSqlUpdate', type: 'string', description: enhanceParameterDescription('string', 'Intercept UPDATE statements (true | false).'), required: false, cliName: '-intercSqlUpdate' },
  { name: 'intercSqlDelete', type: 'string', description: enhanceParameterDescription('string', 'Intercept DELETE statements (true | false).'), required: false, cliName: '-intercSqlDelete' },
  { name: 'intercFuncCall', type: 'string', description: enhanceParameterDescription('string', 'Intercept function calls (true | false).'), required: false, cliName: '-intercFuncCall' },
  { name: 'intercFunc', type: 'string', description: enhanceParameterDescription('string', 'Intercept queries targeted to certain functions.', 'LIST'), required: false, cliName: '-intercFunc' },
  { name: 'intercPack', type: 'string', description: enhanceParameterDescription('string', 'Intercept the whole package of DDL statements. Use empty quoted string to delete all the packages and functions.', 'LIST'), required: false, cliName: '-intercPack' },
  { name: 'intercTab', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated tables/columns to intercept (db.schema.table.col).', 'LIST'), required: false, cliName: '-intercTab' },
  { name: 'intercObjGr', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated Object Group names to intercept.', 'LIST'), required: false, cliName: '-intercObjGr' },
  { name: 'intercSqlGr', type: 'string', description: enhanceParameterDescription('string', 'Intercept statements from a certain SQL group.', 'LIST'), required: false, cliName: '-intercSqlGr' },
  { name: 'skipFunc', type: 'string', description: enhanceParameterDescription('string', 'Skip statements for functions.', 'LIST'), required: false, cliName: '-skipFunc' },
  { name: 'skipObjGr', type: 'string', description: enhanceParameterDescription('string', 'Skip statements for databases, schemas, tables, columns from the comma separated list of object groups ((groups) | false).', 'LIST'), required: false, cliName: '-skipObjGr' },
  { name: 'skipPack', type: 'string', description: enhanceParameterDescription('string', 'Skip statements for the whole package of functions.', 'LIST'), required: false, cliName: '-skipPack' },
  { name: 'skipSqlGr', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated SQL Query Group names to skip.', 'LIST'), required: false, cliName: '-skipSqlGr' },
  { name: 'skipTab', type: 'string', description: enhanceParameterDescription('string', 'Skip statements for databases, schemas, tables, columns formatted like "orcl.alex.customers.id;orcl.bob.orders.id".', 'LIST'), required: false, cliName: '-skipTab' },
];

const ddlFilteringParams: CliCommand['params'] = [
  { name: 'ddlSelectAll', type: 'string', description: enhanceParameterDescription('string', 'Intercept all DDL-statements (true | false). Only applicable if filterType is "ddl".'), required: false, cliName: '-ddlSelectAll' },
  { name: 'ddlTypes', type: 'string', description: enhanceParameterDescription('string', 'For DDL filter: Comma-separated DDL types (CREATE_TABLE). Only applicable if filterType is "ddl".', 'LIST'), required: false, cliName: '-ddlTypes' },
];

const injectFilteringParams: CliCommand['params'] = [
  { name: 'injWarnLevel', type: 'string', description: enhanceParameterDescription('string', 'For SQLi filter: Warning level. Number of penalties a query should achieve to be considered as suspicious.'), required: false, cliName: '-injWarnLevel' },
  { name: 'injErrLevel', type: 'string', description: enhanceParameterDescription('string', 'For SQLi filter: Error level. Number of penalties a query should achieve to be considered as SQL-injected.'), required: false, cliName: '-injErrLevel' },
  { name: 'injConcat', type: 'string', description: enhanceParameterDescription('string', 'Set a number of penalties for Concatenation of single Characters (many types of attacks).'), required: false, cliName: '-injConcat' },
  { name: 'injPenComm', type: 'string', description: enhanceParameterDescription('string', 'Set a number of penalties for comments in a query code.'), required: false, cliName: '-injPenComm' },
  { name: 'injPenConst', type: 'string', description: enhanceParameterDescription('string', 'Set a number of penalties for the expression which is always true.'), required: false, cliName: '-injPenConst' },
  { name: 'injPenDq', type: 'string', description: enhanceParameterDescription('string', 'Set a number of penalties for multiple SQL statements separated by semicolon.'), required: false, cliName: '-injPenDq' },
  { name: 'injPenKw', type: 'string', description: enhanceParameterDescription('string', 'Set a number of penalties for comments containing one or multiple SQL keywords.'), required: false, cliName: '-injPenKw' },
  { name: 'injPenOr', type: 'string', description: enhanceParameterDescription('string', 'Set a number of penalties for OR SQL statement.'), required: false, cliName: '-injPenOr' },
  { name: 'injPenUnion', type: 'string', description: enhanceParameterDescription('string', 'Set a number of penalties for UNION SQL statement.'), required: false, cliName: '-injPenUnion' },
  { name: 'injSuspicCondit', type: 'string', description: enhanceParameterDescription('string', 'Suspicious condition to check for Boolean Blind Attack.'), required: false, cliName: '-injSuspicCondit' },
  { name: 'injSuspicConv', type: 'string', description: enhanceParameterDescription('string', 'Suspicious convertion: Blind Error Attack.'), required: false, cliName: '-injSuspicConv' },
  { name: 'injSuspicFunc', type: 'string', description: enhanceParameterDescription('string', 'Suspicious function call.'), required: false, cliName: '-injSuspicFunc' },
];

const sessionFilteringParams: CliCommand['params'] = [
  { name: 'sessionsType', type: 'string', description: enhanceParameterDescription('string', 'Type of Audited sessions: (disabled | unsuccessful | all success | not auth)'), required: false, cliName: '-sessionsType' },
  { name: 'filterSessionsFile', type: 'string', description: enhanceParameterDescription('string', 'Filter session rules JSON file path. Only applicable if filterType is "session".'), required: false, cliName: '-filterSessionsFile' },
  { name: 'sessionAlertsEnable', type: 'string', description: enhanceParameterDescription('string', 'enable Audit Operation Errors filtering'), required: false, cliName: '-sessionAlertsEnable' },
  { name: 'sessionLimitNum', type: 'string', description: enhanceParameterDescription('string', 'allowed number of sessions per time period'), required: false, cliName: '-sessionLimitNum' },
  { name: 'sessionPeriodLimit', type: 'string', description: enhanceParameterDescription('string', 'allowed time period (minutes) for a certain number of sessions'), required: false, cliName: '-sessionPeriodLimit' },
];

const generalRuleSettingsParams: CliCommand['params'] = [
  { name: 'affectedRows', type: 'string', description: enhanceParameterDescription('string', 'Trigger the rule only if the number of affected rows is not less that a specified number.'), required: false, cliName: '-affectedRows' },
  { name: 'queryLength', type: 'string', description: enhanceParameterDescription('string', 'Maximum length of a query to be filtered.'), required: false, cliName: '-queryLength' },
  { name: 'queryLengthEnable', type: 'string', description: enhanceParameterDescription('string', 'Enable filtering by maximum query length (true | false).'), required: false, cliName: '-queryLengthEnable' },
  { name: 'queryIncludesSelect', type: 'string', description: enhanceParameterDescription('string', 'Query includes "SELECT *" expression (true | false).'), required: false, cliName: '-queryIncludesSelect' },
  { name: 'proxy', type: 'string', description: enhanceParameterDescription('string', 'Proxy filter ((host:port) | any).'), required: false, cliName: '-proxy' },
  { name: 'sniffer', type: 'string', description: enhanceParameterDescription('string', 'Sniffer filter (host | any).'), required: false, cliName: '-sniffer' },
  { name: 'blockSeparator', type: 'string', description: enhanceParameterDescription('string', 'Assign a character as a separator between blocks of database elements (\';\' is assigned by default).'), required: false, cliName: '-blockSeparator' },
  { name: 'listSeparator', type: 'string', description: enhanceParameterDescription('string', 'Separator for a list of values. Default is ",".'), required: false, cliName: '-listSeparator' },
  { name: 'nameSeparator', type: 'string', description: enhanceParameterDescription('string', 'Assign a character as a separator between database elements (\'.\' is assigned by default).'), required: false, cliName: '-nameSeparator' },
];


export const ruleCommands: CliCommand[] = [
  {
    toolName: 'rule_add_audit',
    description: 'Adds a new Audit Rule. If called without parameters, the CLI may prompt for necessary details or create a default rule. Otherwise, it configures the rule to log or skip specified database activities based on the provided criteria.',
    baseCommand: 'addAuditRule',
    // If allowEmptyToolArguments is true, an empty arguments object in use_mcp_tool 
    // will result in the baseCommand being run without any CLI parameters.
    allowEmptyToolArguments: true,
    params: [
      ...commonRuleParams,
      { name: 'action', type: 'string', description: enhanceParameterDescription('string', 'Action for the audit rule (audit or skip).', 'ENUM'), required: false, cliName: '-action' },
      { name: 'filterType', type: 'string', description: enhanceParameterDescription('string', 'Primary filtering mechanism (object, group, ddl, inject, session).', 'ENUM'), required: false, cliName: '-filterType' },
      { name: 'depersQueries', type: 'string', description: enhanceParameterDescription('string', 'Mask/anonymize sensitive data in SQL queries in audit logs (true | false).'), required: false, cliName: '-depersQueries' },
      { name: 'logBindVariables', type: 'string', description: enhanceParameterDescription('string', 'Log values of bind variables used in SQL statements (true | false).'), required: false, cliName: '-logBindVariables' },
      { name: 'logData', type: 'string', description: enhanceParameterDescription('string', 'Log the result set of queries (true | false).'), required: false, cliName: '-logData' },
      { name: 'logMaxRowCount', type: 'string', description: enhanceParameterDescription('string', 'Max rows from result set to log (number, default, unlimited).'), required: false, cliName: '-logMaxRowCount' },
      { name: 'auditErrEnable', type: 'string', description: enhanceParameterDescription('string', 'Enable Audit Operation Errors filtering (true | false).'), required: false, cliName: '-auditErrEnable' },
      { name: 'auditErrLimitNum', type: 'string', description: enhanceParameterDescription('string', 'Limit of Audit Operation Errors occurred during the -auditErrPeriod period.'), required: false, cliName: '-auditErrLimitNum' },
      { name: 'auditErrPeriod', type: 'string', description: enhanceParameterDescription('string', 'Time period (minutes) to use in conjunction with -auditErrLimitNum.'), required: false, cliName: '-auditErrPeriod' },
      { name: 'fileName', type: 'string', description: enhanceParameterDescription('string', 'Absolute file names within S3 bucket, that should be audited or masked. Example: /bucket/folder/file.csv'), required: false, cliName: '-fileName' },
      { name: 'freqConnEnable', type: 'string', description: enhanceParameterDescription('string', 'Enable auditing of frequent connections (true | false).'), required: false, cliName: '-freqConnEnable' },
      { name: 'freqConnLimit', type: 'string', description: enhanceParameterDescription('string', 'Limit of allowed connections per time period.'), required: false, cliName: '-freqConnLimit' },
      { name: 'freqConnPeriod', type: 'string', description: enhanceParameterDescription('string', 'Allowed time period (minutes) for a certain number of connections.'), required: false, cliName: '-freqConnPeriod' },
      { name: 'freqConnSrc', type: 'string', description: enhanceParameterDescription('string', 'Type of frequent connections: USERNAME_AND_HOST, HOST_ONLY.'), required: false, cliName: '-freqConnSrc' },
      { name: 'log1Event', type: 'string', description: enhanceParameterDescription('string', 'Log first event only (true | false).'), required: false, cliName: '-log1Event' },
      { name: 'queryExecTime', type: 'string', description: enhanceParameterDescription('string', 'Audited query execution time (seconds).'), required: false, cliName: '-queryExecTime' },
      { name: 'queryExecTimeEnable', type: 'string', description: enhanceParameterDescription('string', 'Enable filtering by query execution time (true | false).'), required: false, cliName: '-queryExecTimeEnable' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'Database User Login'), required: false, cliName: '-login' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'Database User Password'), required: false, cliName: '-password' },
      { name: 'delHostGroups', type: 'string', description: enhanceParameterDescription('string', 'comma-separated list of host groups for deleting'), required: false, cliName: '-delHostGroups' },
      { name: 'delHosts', type: 'string', description: enhanceParameterDescription('string', 'comma-separated list of hosts for deleting'), required: false, cliName: '-delHosts' },
      { name: 'delOsUserGroups', type: 'string', description: enhanceParameterDescription('string', 'comma-separated list of OS user groups for deleting'), required: false, cliName: '-delOsUserGroups' },
      { name: 'delOsUsers', type: 'string', description: enhanceParameterDescription('string', 'comma-separated list of OS users or {regexp name} for deleting'), required: false, cliName: '-delOsUsers' },
      { name: 'delSubscribers', type: 'string', description: enhanceParameterDescription('string', 'delete subscribers (comma-separated list of email addresses)'), required: false, cliName: '-delSubscribers' },
      { name: 'delUserGroups', type: 'string', description: enhanceParameterDescription('string', 'comma-separated list of database user groups for deleting'), required: false, cliName: '-delUserGroups' },
      { name: 'delUsers', type: 'string', description: enhanceParameterDescription('string', 'comma-separated list of database users for deleting or {regexp name}'), required: false, cliName: '-delUsers' },
      ...sqlFilteringParams,
      ...ddlFilteringParams,
      ...injectFilteringParams,
      ...sessionFilteringParams,
      ...generalRuleSettingsParams,
    ],
    category: 'Rule',
  },
  {
    toolName: 'rule_add_masking',
    description: 'Adds a new Masking Rule to dynamically mask data in query results.',
    baseCommand: 'addMaskRule', // From context
    params: [
      { name: 'action', type: 'string', description: enhanceParameterDescription('string', 'Action for the masking rule (mask or skip).', 'ENUM'), required: false, cliName: '-action' },
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Unique name for the rule.'), required: false, cliName: '-name' },
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Instance name where masking applies.'), required: true, cliName: '-instance' },
      ...commonRuleParams.filter(p => p.name !== 'name' && p.name !== 'instance'), // Spread common params, excluding name and instance
      // Masking specific params from PDF section 6.5
      { name: 'maskColumns', type: 'string', description: enhanceParameterDescription('string', 'Semicolon-separated columns to mask (e.g., db.schema.table.column;db.schema.table.column2).'), required: true, cliName: '-maskColumns' },
      { name: 'maskType', type: 'string', description: enhanceParameterDescription('string', 'Type of masking to apply. Allowed values: bankCard | default | emailDefault | emailLogin | emailFull | empty | fixedNum | fixedStr | function | maskFirst | maskLast | maskFirstLast | showFirst | showLast | showFirstLast | random | intervalRandom | regexpReplace | rndTime | rndDate | rndDateTime | fixTime | fixDate | rnd2Date | rndDateTimeConstYear | fixDateTime | timeDisp | dateDisp | dateTimeDisp | bankCardFpt | bankCardFpeFf3 | emailFpt | emailFpeFf3 | ssnFpt | ssnFpeFf3 | numFpt | numFpeFf3 | stringFpt | stringFpeFf3 | hideRows | hideAllRows | luaScript.', 'ENUM_EXTENSIVE'), required: false, cliName: '-maskType' },
      { name: 'maskSelectOnly', type: 'string', description: enhanceParameterDescription('string', 'Apply masking only to SELECT statements (true | false). Default is false.'), required: false, cliName: '-maskSelectOnly' },
      { name: 'keepRowCount', type: 'string', description: enhanceParameterDescription('string', 'Preserve original row count when masking (true | false). Default is false.'), required: false, cliName: '-keepRowCount' },
      // File-based masking params
      { name: 'fileName', type: 'string', description: enhanceParameterDescription('string', 'Path to the file that should be masked.'), required: false, cliName: '-fileName' },
      { name: 'fileType', type: 'string', description: enhanceParameterDescription('string', 'Type of the file which should be masked (CSV | JSON | XML | UNSTRUCTURED). Default is CSV.', 'ENUM'), required: false, cliName: '-fileType' },
      // CSV specific
      { name: 'columnDelimiter', type: 'string', description: enhanceParameterDescription('string', 'Column delimiter for CSV files. Default is "\\t".'), required: false, cliName: '-columnDelimiter' },
      { name: 'columns', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated names or numbers of columns to mask for CSV, or text inside tags for XML.'), required: false, cliName: '-columns' }, // For CSV/XML
      { name: 'quote', type: 'string', description: enhanceParameterDescription('string', 'Quote character for CSV files. Default is "\\".'), required: false, cliName: '-quote' },
      { name: 'rowDelimiter', type: 'string', description: enhanceParameterDescription('string', 'Row delimiter for CSV files. Default is "\\n".'), required: false, cliName: '-rowDelimiter' },
      { name: 'withHeader', type: 'string', description: enhanceParameterDescription('string', 'Applicable to CSV only. Whether a CSV file has headers or not (true | false).'), required: false, cliName: '-withHeader' },
      // JSON/XML specific
      { name: 'jsonPath', type: 'string', description: enhanceParameterDescription('string', 'Keys\' values of a JSON file to be masked, comma-separated.', 'LIST'), required: false, cliName: '-jsonPath' },
      { name: 'xmlPath', type: 'string', description: enhanceParameterDescription('string', 'Keys\' values of an XML file to be masked, comma-separated.', 'LIST'), required: false, cliName: '-xmlPath' },
      // Params for specific maskTypes
      { name: 'date', type: 'string', description: enhanceParameterDescription('string', 'Replace date value with a fixed value if -maskType is fixDate.'), required: false, cliName: '-date' },
      { name: 'dateTime', type: 'string', description: enhanceParameterDescription('string', 'Replace date and time value with a fixed value if -maskType is fixDateTime.'), required: false, cliName: '-dateTime' },
      { name: 'days', type: 'string', description: enhanceParameterDescription('string', 'Replace date values with random values from a predefined range if -maskType is dateDisp or dateTimeDisp.'), required: false, cliName: '-days' },
      { name: 'endDate', type: 'string', description: enhanceParameterDescription('string', 'Minimum value of the random date value interval if -maskType is rndDate.'), required: false, cliName: '-endDate' },
      { name: 'endDateTime', type: 'string', description: enhanceParameterDescription('string', 'Minimum value of the random time and value interval if -maskType is rndDateTime.'), required: false, cliName: '-endDateTime' },
      { name: 'endTime', type: 'string', description: enhanceParameterDescription('string', 'Minimum value of the random time value interval if -maskType is rndTime.'), required: false, cliName: '-endTime' },
      { name: 'filler', type: 'string', description: enhanceParameterDescription('string', 'A placeholder to replace the masked values with. Note that it should be one character. Default is "*".'), required: false, cliName: '-filler' },
      { name: 'fixedVal', type: 'string', description: enhanceParameterDescription('string', 'Replace masked value with a fixed value if -maskType is fixedNum or fixedStr.'), required: false, cliName: '-fixedVal' },
      { name: 'functionName', type: 'string', description: enhanceParameterDescription('string', 'Call a custom function for masking if -maskType is function.'), required: false, cliName: '-functionName' },
      { name: 'functionParams', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated input parameters for -functionName.', 'LIST'), required: false, cliName: '-functionParams' },
      { name: 'hideRowsCondition', type: 'string', description: enhanceParameterDescription('string', 'Show table rows that match the condition if -maskType is hideRows.'), required: false, cliName: '-hideRowsCondition' },
      { name: 'hours', type: 'string', description: enhanceParameterDescription('string', 'Replace date or date/time value with a value from the end of available range if -maskType is timeDisp or dateTimeDisp.'), required: false, cliName: '-hours' },
      { name: 'maskCount', type: 'string', description: enhanceParameterDescription('string', 'Number of masked characters if -maskType is (maskFirst | maskLast | maskFirstLast | showFirst | showLast | showFirstLast).'), required: false, cliName: '-maskCount' },
      { name: 'maskMax', type: 'string', description: enhanceParameterDescription('string', 'Maximum value of the range if -maskType is intervalRandom. Default value is 100.'), required: false, cliName: '-maskMax' },
      { name: 'maskMin', type: 'string', description: enhanceParameterDescription('string', 'Minimum value of the range if -maskType is intervalRandom. Default value is 0.'), required: false, cliName: '-maskMin' },
      { name: 'maskPattern', type: 'string', description: enhanceParameterDescription('string', 'A pattern that should be found and replaced with the text specified by -replaceBy option if -maskType is regexpReplace.'), required: false, cliName: '-maskPattern' },
      { name: 'minutes', type: 'string', description: enhanceParameterDescription('string', 'Replace date or date/time value with a value from the end of available range if -maskType is timeDisp or dateTimeDisp.'), required: false, cliName: '-minutes' },
      { name: 'paddingText', type: 'string', description: enhanceParameterDescription('string', 'Replace masked characters with a predefined character if -maskType is: maskFirst | maskLast | maskFirstLast | showFirst | showLast | showFirstLast. Default character is *.'), required: false, cliName: '-paddingText' },
      { name: 'replaceBy', type: 'string', description: enhanceParameterDescription('string', 'The text used instead of the pattern specified by -maskPattern if -maskType is regexpReplace.'), required: false, cliName: '-replaceBy' },
      { name: 'seconds', type: 'string', description: enhanceParameterDescription('string', 'Replace date or date/time value with a value from the end of available range if -maskType is timeDisp or dateTimeDisp.'), required: false, cliName: '-seconds' },
      { name: 'startDate', type: 'string', description: enhanceParameterDescription('string', 'Maximum value of the random date value interval if -maskType is rndDate.'), required: false, cliName: '-startDate' },
      { name: 'startDateTime', type: 'string', description: enhanceParameterDescription('string', 'Maximum value of the random time and date value interval if -maskType is rndDateTime.'), required: false, cliName: '-startDateTime' },
      { name: 'startTime', type: 'string', description: enhanceParameterDescription('string', 'Maximum value of the random time value interval if -maskType is rndTime.'), required: false, cliName: '-startTime' },
      { name: 'time', type: 'string', description: enhanceParameterDescription('string', 'Replace time value with a fixed value if -maskType is fixTime.'), required: false, cliName: '-time' },
      ...generalRuleSettingsParams,
    ],
    category: 'Rule',
  },
  {
    toolName: 'rule_add_security',
    description: 'Adds a new Security Rule. If called without parameters, the CLI may prompt for necessary details or create a default rule. Otherwise, it configures the rule to block or alert on prohibited database activities based on the provided criteria.',
    baseCommand: 'addSecurityRule',
    allowEmptyToolArguments: true,
    params: [
      ...commonRuleParams,
      { name: 'action', type: 'string', description: enhanceParameterDescription('string', 'Security action (block | allow).', 'ENUM'), required: false, cliName: '-action' },
      { name: 'filterType', type: 'string', description: enhanceParameterDescription('string', 'Primary filtering mechanism (object, group, ddl, inject, session).', 'ENUM'), required: false, cliName: '-filterType' },
      { name: 'blockType', type: 'string', description: enhanceParameterDescription('string', 'If action is Block: type of block (SQLError, Disconnect).', 'ENUM'), required: false, cliName: '-blockType' },
      { name: 'blockMsg', type: 'string', description: enhanceParameterDescription('string', 'Custom message for SQL Error block type.'), required: false, cliName: '-blockMsg' },
      { name: 'blockAttacks', type: 'string', description: enhanceParameterDescription('string', 'Blocking types for attacks (disable | temp | perm).'), required: false, cliName: '-blockAttacks' },
      { name: 'blockingPeriod', type: 'string', description: enhanceParameterDescription('string', 'Block for, minutes.'), required: false, cliName: '-blockingPeriod' },
      { name: 'freqConnLimit', type: 'string', description: enhanceParameterDescription('string', 'Maximum number of sessions to be allowed for -blockAttacks: temp.'), required: false, cliName: '-freqConnLimit' },
      { name: 'freqConnPeriod', type: 'string', description: enhanceParameterDescription('string', 'Time period to allow sessions at -freqConnLimit.'), required: false, cliName: '-freqConnPeriod' },
      { name: 'freqConnSrc', type: 'string', description: enhanceParameterDescription('string', 'Block by: USERNAME_AND_HOST, HOST_ONLY.'), required: false, cliName: '-freqConnSrc' },
      ...sqlFilteringParams,
      ...ddlFilteringParams,
      ...injectFilteringParams,
      ...sessionFilteringParams,
      ...generalRuleSettingsParams,
    ],
    category: 'Rule',
  },
  {
    toolName: 'rule_add_learning',
    description: 'Adds a new Learning Rule to profile database activity and suggest policies.',
    baseCommand: 'addLearnRule',
    allowEmptyToolArguments: true,
    params: [
      ...commonLearnRuleParams,
      { name: 'action', type: 'string', description: enhanceParameterDescription('string', 'Learning action (learn | skip).', 'ENUM'), required: false, cliName: '-action' },
      // Learning specific params from PDF section 6.4
      { name: 'learnDelete', type: 'string', description: enhanceParameterDescription('string', 'Learning based on DELETE operations (true | false).'), required: false, cliName: '-learnDelete' },
      { name: 'learnFuncCall', type: 'string', description: enhanceParameterDescription('string', 'Learning based on Function CALL operations (true | false).'), required: false, cliName: '-learnFuncCall' },
      { name: 'learnInsert', type: 'string', description: enhanceParameterDescription('string', 'Learning based on INSERT operation (true | false).'), required: false, cliName: '-learnInsert' },
      { name: 'learnObjectGroup', type: 'string', description: enhanceParameterDescription('string', 'Save names of databases, schemas, tables, columns to the Object Group for the Learning Rule ( false | <group name>).'), required: false, cliName: '-learnObjectGroup' },
      { name: 'learnSelect', type: 'string', description: enhanceParameterDescription('string', 'Learning based on SELECT operation (true | false).'), required: false, cliName: '-learnSelect' },
      { name: 'learnSqlGroup', type: 'string', description: enhanceParameterDescription('string', 'Save SQL Statements to the Group for the Learning Rule ( false | <group name>).'), required: false, cliName: '-learnSqlGroup' },
      { name: 'learnUpdate', type: 'string', description: enhanceParameterDescription('string', 'Learning based on UPDATE operation (true | false).'), required: false, cliName: '-learnUpdate' },
      { name: 'learnUserGroup', type: 'string', description: enhanceParameterDescription('string', 'Save Users in the Learning Rule Group (true | false | <group name>).'), required: false, cliName: '-learnUserGroup' },
      { name: 'learnAppSave', type: 'string', description: enhanceParameterDescription('string', 'Save applications for the Learning Rule (true | false).'), required: false, cliName: '-learnAppSave' },
      { name: 'delHostGroups', type: 'string', description: enhanceParameterDescription('string', 'comma-separated list of host groups for deleting'), required: false, cliName: '-delHostGroups' },
      { name: 'delHosts', type: 'string', description: enhanceParameterDescription('string', 'comma-separated list of hosts for deleting'), required: false, cliName: '-delHosts' },
      { name: 'delOsUserGroups', type: 'string', description: enhanceParameterDescription('string', 'comma-separated list of OS user groups for deleting'), required: false, cliName: '-delOsUserGroups' },
      { name: 'delOsUsers', type: 'string', description: enhanceParameterDescription('string', 'comma-separated list of OS users or {regexp name} for deleting'), required: false, cliName: '-delOsUsers' },
      { name: 'delUserGroups', type: 'string', description: enhanceParameterDescription('string', 'comma-separated list of database user groups for deleting'), required: false, cliName: '-delUserGroups' },
      { name: 'delUsers', type: 'string', description: enhanceParameterDescription('string', 'comma-separated list of database users for deleting or {regexp name}'), required: false, cliName: '-delUsers' },
      { name: 'filterSessionsFile', type: 'string', description: enhanceParameterDescription('string', 'filter session rules JSON file'), required: false, cliName: '-filterSessionsFile' },
      { name: 'login', type: 'string', description: enhanceParameterDescription('string', 'Database User Login'), required: false, cliName: '-login' },
      { name: 'password', type: 'string', description: enhanceParameterDescription('string', 'Database User Password'), required: false, cliName: '-password' },
      { name: 'proxy', type: 'string', description: enhanceParameterDescription('string', '(<host1:port1-server1;host2:port2-server2> | any)'), required: false, cliName: '-proxy' },
      { name: 'sniffer', type: 'string', description: enhanceParameterDescription('string', '(<host1-server1;host2-server2>| any)'), required: false, cliName: '-sniffer' },
    ],
    category: 'Rule',
  },
  {
    toolName: 'rule_update_audit',
    description: 'Updates an existing Audit Rule.',
    baseCommand: 'updateAuditRule',
    params: [ 
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the audit rule to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'New unique name for the rule.'), required: false, cliName: '-newName' },
      ...commonRuleParams.filter(p => p.name !== 'name').map(p => ({ ...p, required: false })), // All common params optional, except 'name'
      { name: 'action', type: 'string', description: enhanceParameterDescription('string', 'New action (audit or skip).', 'ENUM'), required: false, cliName: '-action'},
      { name: 'filterType', type: 'string', description: enhanceParameterDescription('string', 'Primary filtering mechanism (object, group, ddl, inject, session).', 'ENUM'), required: false, cliName: '-filterType' },
      { name: 'depersQueries', type: 'string', description: enhanceParameterDescription('string', 'Mask/anonymize sensitive data in SQL queries in audit logs (true | false).'), required: false, cliName: '-depersQueries' },
      { name: 'logBindVariables', type: 'string', description: enhanceParameterDescription('string', 'Log values of bind variables used in SQL statements (true | false).'), required: false, cliName: '-logBindVariables' },
      { name: 'logData', type: 'string', description: enhanceParameterDescription('string', 'Log the result set of queries (true | false).'), required: false, cliName: '-logData' },
      { name: 'logMaxRowCount', type: 'string', description: enhanceParameterDescription('string', 'Max rows from result set to log (number, default, unlimited).'), required: false, cliName: '-logMaxRowCount' },
      { name: 'auditErrEnable', type: 'string', description: enhanceParameterDescription('string', 'Enable Audit Operation Errors filtering (true | false).'), required: false, cliName: '-auditErrEnable' },
      { name: 'auditErrLimitNum', type: 'string', description: enhanceParameterDescription('string', 'Limit of Audit Operation Errors occurred during the -auditErrPeriod period.'), required: false, cliName: '-auditErrLimitNum' },
      { name: 'auditErrPeriod', type: 'string', description: enhanceParameterDescription('string', 'Time period (minutes) to use in conjunction with -auditErrLimitNum.'), required: false, cliName: '-auditErrPeriod' },
      { name: 'fileName', type: 'string', description: enhanceParameterDescription('string', 'Absolute file names within S3 bucket, that should be audited or masked. Example: /bucket/folder/file.csv'), required: false, cliName: '-fileName' },
      { name: 'freqConnEnable', type: 'string', description: enhanceParameterDescription('string', 'Enable auditing of frequent connections (true | false).'), required: false, cliName: '-freqConnEnable' },
      { name: 'freqConnLimit', type: 'string', description: enhanceParameterDescription('string', 'Limit of allowed connections per time period.'), required: false, cliName: '-freqConnLimit' },
      { name: 'freqConnPeriod', type: 'string', description: enhanceParameterDescription('string', 'Allowed time period (minutes) for a certain number of connections.'), required: false, cliName: '-freqConnPeriod' },
      { name: 'freqConnSrc', type: 'string', description: enhanceParameterDescription('string', 'Type of frequent connections: USERNAME_AND_HOST, HOST_ONLY.'), required: false, cliName: '-freqConnSrc' },
      { name: 'log1Event', type: 'string', description: enhanceParameterDescription('string', 'Log first event only (true | false).'), required: false, cliName: '-log1Event' },
      { name: 'queryExecTime', type: 'string', description: enhanceParameterDescription('string', 'Audited query execution time (seconds).'), required: false, cliName: '-queryExecTime' },
      { name: 'queryExecTimeEnable', type: 'string', description: enhanceParameterDescription('string', 'Enable filtering by query execution time (true | false).'), required: false, cliName: '-queryExecTimeEnable' },
      ...sqlFilteringParams.map(p => ({ ...p, required: false })),
      ...ddlFilteringParams.map(p => ({ ...p, required: false })),
      ...injectFilteringParams.map(p => ({ ...p, required: false })),
      ...sessionFilteringParams.map(p => ({ ...p, required: false })),
      ...generalRuleSettingsParams.map(p => ({ ...p, required: false })),
    ],
    category: 'Rule',
  },
  {
    toolName: 'rule_update_security',
    description: 'Updates an existing Security Rule.',
    baseCommand: 'updateSecurityRule',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the security rule to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'New unique name for the rule.'), required: false, cliName: '-newName' },
      ...commonRuleParams.filter(p => p.name !== 'name').map(p => ({ ...p, required: false })),
      { name: 'action', type: 'string', description: enhanceParameterDescription('string', 'New security action (block | allow).', 'ENUM'), required: false, cliName: '-action' },
      { name: 'filterType', type: 'string', description: enhanceParameterDescription('string', 'Primary filtering mechanism (object, group, ddl, inject, session).', 'ENUM'), required: false, cliName: '-filterType' },
      { name: 'blockType', type: 'string', description: enhanceParameterDescription('string', 'If action is Block: new type of block (SQLError, Disconnect).', 'ENUM'), required: false, cliName: '-blockType' },
      { name: 'blockMsg', type: 'string', description: enhanceParameterDescription('string', 'New custom message for SQL Error block type.'), required: false, cliName: '-blockMsg' },
      { name: 'blockAttacks', type: 'string', description: enhanceParameterDescription('string', 'New blocking types for attacks (disable | temp | perm).'), required: false, cliName: '-blockAttacks' },
      { name: 'blockingPeriod', type: 'string', description: enhanceParameterDescription('string', 'New block for, minutes.'), required: false, cliName: '-blockingPeriod' },
      { name: 'freqConnLimit', type: 'string', description: enhanceParameterDescription('string', 'New maximum number of sessions to be allowed for -blockAttacks: temp.'), required: false, cliName: '-freqConnLimit' },
      { name: 'freqConnPeriod', type: 'string', description: enhanceParameterDescription('string', 'New time period to allow sessions at -freqConnLimit.'), required: false, cliName: '-freqConnPeriod' },
      { name: 'freqConnSrc', type: 'string', description: enhanceParameterDescription('string', 'New block by: USERNAME_AND_HOST, HOST_ONLY.'), required: false, cliName: '-freqConnSrc' },
      ...sqlFilteringParams.map(p => ({ ...p, required: false })),
      ...ddlFilteringParams.map(p => ({ ...p, required: false })),
      ...injectFilteringParams.map(p => ({ ...p, required: false })),
      ...sessionFilteringParams.map(p => ({ ...p, required: false })),
      ...generalRuleSettingsParams.map(p => ({ ...p, required: false })),
    ],
    category: 'Rule',
  },
  {
    toolName: 'rule_update_learning',
    description: 'Updates an existing Learning Rule.',
    baseCommand: 'updateLearnRule',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the learning rule to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'New unique name for the rule.'), required: false, cliName: '-newName' },
      ...commonLearnRuleParams.filter(p => p.name !== 'name').map(p => ({ ...p, required: false })),
      { name: 'action', type: 'string', description: enhanceParameterDescription('string', 'New learning action (learn | skip).', 'ENUM'), required: false, cliName: '-action' },
      { name: 'learnDelete', type: 'string', description: enhanceParameterDescription('string', 'Learning based on DELETE operations (true | false).'), required: false, cliName: '-learnDelete' },
      { name: 'learnFuncCall', type: 'string', description: enhanceParameterDescription('string', 'Learning based on Function CALL operations (true | false).'), required: false, cliName: '-learnFuncCall' },
      { name: 'learnInsert', type: 'string', description: enhanceParameterDescription('string', 'Learning based on INSERT operation (true | false).'), required: false, cliName: '-learnInsert' },
      { name: 'learnObjectGroup', type: 'string', description: enhanceParameterDescription('string', 'Save names of databases, schemas, tables, columns to the Object Group for the Learning Rule ( false | <group name>).'), required: false, cliName: '-learnObjectGroup' },
      { name: 'learnSelect', type: 'string', description: enhanceParameterDescription('string', 'Learning based on SELECT operation (true | false).'), required: false, cliName: '-learnSelect' },
      { name: 'learnSqlGroup', type: 'string', description: enhanceParameterDescription('string', 'Save SQL Statements to the Group for the Learning Rule ( false | <group name>).'), required: false, cliName: '-learnSqlGroup' },
      { name: 'learnUpdate', type: 'string', description: enhanceParameterDescription('string', 'Learning based on UPDATE operation (true | false).'), required: false, cliName: '-learnUpdate' },
      { name: 'learnUserGroup', type: 'string', description: enhanceParameterDescription('string', 'Save Users in the Learning Rule Group (true | false | <group name>).'), required: false, cliName: '-learnUserGroup' },
      { name: 'learnAppSave', type: 'string', description: enhanceParameterDescription('string', 'Save applications for the Learning Rule (true | false).'), required: false, cliName: '-learnAppSave' },
      ...generalRuleSettingsParams.map(p => ({ ...p, required: false })),
    ],
    category: 'Rule',
  },
  {
    toolName: 'rule_update_masking',
    description: 'Updates an existing Masking Rule.',
    baseCommand: 'updateMaskRule',
    params: [
      { name: 'action', type: 'string', description: enhanceParameterDescription('string', 'Action for the masking rule (mask or skip).', 'ENUM'), required: false, cliName: '-action' },
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Current name of the masking rule to update.'), required: true, cliName: '-name' },
      { name: 'newName', type: 'string', description: enhanceParameterDescription('string', 'New unique name for the rule.'), required: false, cliName: '-newName' },
      ...commonRuleParams.filter(p => p.name !== 'name').map(p => ({ ...p, required: false })), // All common params optional
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'New instance name where masking applies.'), required: false, cliName: '-instance' },
      { name: 'maskColumns', type: 'string', description: enhanceParameterDescription('string', 'New semicolon-separated columns to mask (e.g., db.schema.table.column;db.schema.table.column2).'), required: false, cliName: '-maskColumns' },
      { name: 'maskType', type: 'string', description: enhanceParameterDescription('string', 'New type of masking to apply (e.g., empty, maskFirst, regex).'), required: false, cliName: '-maskType' },
      { name: 'maskSelectOnly', type: 'string', description: enhanceParameterDescription('string', 'Apply masking only to SELECT statements (true | false). Default is false.'), required: false, cliName: '-maskSelectOnly' },
      { name: 'keepRowCount', type: 'string', description: enhanceParameterDescription('string', 'Preserve original row count when masking (true | false). Default is false.'), required: false, cliName: '-keepRowCount' },
       { name: 'columnDelimiter', type: 'string', description: enhanceParameterDescription('string', 'Column delimiter for CSV files.'), required: false, cliName: '-columnDelimiter' },
       { name: 'columns', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated names or numbers of columns to mask for CSV, or text inside tags for XML.'), required: false, cliName: '-columns' },
       { name: 'date', type: 'string', description: enhanceParameterDescription('string', 'Replace date value with a fixed value if -maskType is fixDate.'), required: false, cliName: '-date' },
       { name: 'dateTime', type: 'string', description: enhanceParameterDescription('string', 'Replace date and time value with a fixed value if -maskType is fixDateTime.'), required: false, cliName: '-dateTime' },
       { name: 'days', type: 'string', description: enhanceParameterDescription('string', 'Replace date values with random values from a predefined range if -maskType is dateDisp or dateTimeDisp.'), required: false, cliName: '-days' },
       { name: 'endDate', type: 'string', description: enhanceParameterDescription('string', 'Minimum value of the random date value interval if -maskType is rndDate.'), required: false, cliName: '-endDate' },
       { name: 'endDateTime', type: 'string', description: enhanceParameterDescription('string', 'Minimum value of the random time and value interval if -maskType is rndDateTime.'), required: false, cliName: '-endDateTime' },
       { name: 'endTime', type: 'string', description: enhanceParameterDescription('string', 'Minimum value of the random time value interval if -maskType is rndTime.'), required: false, cliName: '-endTime' },
       { name: 'fileName', type: 'string', description: enhanceParameterDescription('string', 'Path to the file that should be masked.'), required: false, cliName: '-fileName' },
       { name: 'fileType', type: 'string', description: enhanceParameterDescription('string', 'Type of the file which should be masked (CSV | JSON | XML | UNSTRUCTURED). Default is CSV.', 'ENUM'), required: false, cliName: '-fileType' },
       { name: 'filler', type: 'string', description: enhanceParameterDescription('string', 'A placeholder to replace the masked values with. Default is "*".'), required: false, cliName: '-filler' },
       { name: 'fixedVal', type: 'string', description: enhanceParameterDescription('string', 'Replace masked value with a fixed value if -maskType is fixedNum or fixedStr.'), required: false, cliName: '-fixedVal' },
       { name: 'functionName', type: 'string', description: enhanceParameterDescription('string', 'Call a custom function for masking if -maskType is function.'), required: false, cliName: '-functionName' },
       { name: 'functionParams', type: 'string', description: enhanceParameterDescription('string', 'Comma-separated input parameters for -functionName.', 'LIST'), required: false, cliName: '-functionParams' },
       { name: 'hideRowsCondition', type: 'string', description: enhanceParameterDescription('string', 'Show table rows that match the condition if -maskType is hideRows.'), required: false, cliName: '-hideRowsCondition' },
       { name: 'hours', type: 'string', description: enhanceParameterDescription('string', 'Replace date or date/time value with a value from the end of available range if -maskType is timeDisp or dateTimeDisp.'), required: false, cliName: '-hours' },
       { name: 'jsonPath', type: 'string', description: enhanceParameterDescription('string', 'Keys\' values of a JSON file to be masked, comma-separated.', 'LIST'), required: false, cliName: '-jsonPath' },
       { name: 'maskCount', type: 'string', description: enhanceParameterDescription('string', 'Number of masked characters if -maskType is (maskFirst | maskLast | maskFirstLast | showFirst | showLast | showFirstLast).'), required: false, cliName: '-maskCount' },
       { name: 'maskMax', type: 'string', description: enhanceParameterDescription('string', 'Maximum value of the range if -maskType is intervalRandom. Default value is 100.'), required: false, cliName: '-maskMax' },
       { name: 'maskMin', type: 'string', description: enhanceParameterDescription('string', 'Minimum value of the range if -maskType is intervalRandom. Default value is 0.'), required: false, cliName: '-maskMin' },
       { name: 'maskPattern', type: 'string', description: enhanceParameterDescription('string', 'A pattern that should be found and replaced with the text specified by -replaceBy option if -maskType is regexpReplace.'), required: false, cliName: '-maskPattern' },
       { name: 'minutes', type: 'string', description: enhanceParameterDescription('string', 'Replace date or date/time value with a value from the end of available range if -maskType is timeDisp or dateTimeDisp.'), required: false, cliName: '-minutes' },
       { name: 'paddingText', type: 'string', description: enhanceParameterDescription('string', 'Replace masked characters with a predefined character if -maskType is: maskFirst | maskLast | maskFirstLast | showFirst | showLast | showFirstLast. Default character is *.'), required: false, cliName: '-paddingText' },
       { name: 'quote', type: 'string', description: enhanceParameterDescription('string', 'Quote character for CSV files. Default is "\\".'), required: false, cliName: '-quote' },
       { name: 'replaceBy', type: 'string', description: enhanceParameterDescription('string', 'The text used instead of the pattern specified by -maskPattern if -maskType is regexpReplace.'), required: false, cliName: '-replaceBy' },
       { name: 'rowDelimiter', type: 'string', description: enhanceParameterDescription('string', 'Row delimiter for CSV files. Default is "\\n".'), required: false, cliName: '-rowDelimiter' },
       { name: 'seconds', type: 'string', description: enhanceParameterDescription('string', 'Replace date or date/time value with a value from the end of available range if -maskType is timeDisp or dateTimeDisp.'), required: false, cliName: '-seconds' },
       { name: 'startDate', type: 'string', description: enhanceParameterDescription('string', 'Maximum value of the random date value interval if -maskType is rndDate.'), required: false, cliName: '-startDate' },
       { name: 'startDateTime', type: 'string', description: enhanceParameterDescription('string', 'Maximum value of the random time and date value interval if -maskType is rndDateTime.'), required: false, cliName: '-startDateTime' },
       { name: 'startTime', type: 'string', description: enhanceParameterDescription('string', 'Maximum value of the random time value interval if -maskType is rndTime.'), required: false, cliName: '-startTime' },
       { name: 'time', type: 'string', description: enhanceParameterDescription('string', 'Replace time value with a fixed value if -maskType is fixTime.'), required: false, cliName: '-time' },
       { name: 'withHeader', type: 'string', description: enhanceParameterDescription('string', 'Applicable to CSV only. Whether a CSV file has headers or not (true | false).'), required: false, cliName: '-withHeader' },
       { name: 'xmlPath', type: 'string', description: enhanceParameterDescription('string', 'Keys\' values of an XML file to be masked, comma-separated.', 'LIST'), required: false, cliName: '-xmlPath' },
      ...generalRuleSettingsParams.map(p => ({ ...p, required: false })),
    ],
    category: 'Rule',
  },
  {
    toolName: 'rule_show_all', // Existing
    description: 'Displays a list of all configured rules.',
    baseCommand: 'showRules',
    params: [
      { name: 'action', type: 'string', description: enhanceParameterDescription('string', 'Type of a Rule to display (audit | security | mask | learn).', 'ENUM'), required: false, cliName: '-action' },
      { name: 'instance', type: 'string', description: enhanceParameterDescription('string', 'Show Rules for specified Instance only.'), required: false, cliName: '-instance' },
    ],
    category: 'Rule',
  },
  {
    toolName: 'rule_show_one',
    description: 'Shows detailed information for a specific rule.',
    baseCommand: 'showRule',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Name of the rule to display.'), required: true, cliName: '-name' },
    ],
    category: 'Rule',
  },
  // DELETE command
  {
    toolName: 'rule_delete',
    description: 'Deletes a specified rule.',
    baseCommand: 'delRule',
    params: [
      { name: 'name', type: 'string', description: enhanceParameterDescription('string', 'Name of the rule to delete.'), required: true, cliName: '-name' },
    ],
    category: 'Rule',
  },
];
