import { registerCommandDescription } from '../description_registry.js';
import { createCommandDescription, enhanceParameterDescription, createParameterHelp } from '../description_helpers.js';

// reports_show
registerCommandDescription('reports_show', {
  description: createCommandDescription(
    'Displays',
    'reports based on report type (application, host, user, IP) and event type (audit, masking, security)',
    'from DataSunrise. This command is likely for viewing summarized or pre-generated report data, not for configuring report generation.',
    'none'
  ),
  detailedDescription: `
This command is used to view existing report data that has been aggregated or generated by DataSunrise. 
It allows filtering by the subject of the report (application, host, user, IP) and the type of events 
(audit, masking, security). This is distinct from commands that *configure* report generation tasks 
(like those in the 'report_gen_*' group).
  `,
  examples: [
    {
      description: 'Show audit reports related to applications',
      command: 'reports_show -reportType app -eventType a'
    },
    {
      description: 'Show security reports related to specific users',
      command: 'reports_show -reportType user -eventType s'
    }
  ],
  relatedCommands: ['report_gen_add_audit', 'report_gen_add_security', 'report_gen_add_masking'],
  commonIssues: ['This command shows existing report data, not for configuring new report generation tasks.'],
  contextualHelp: {
    reportType: createParameterHelp(
      'Type of report to show (app, host, user, ip).',
      { suggestion: 'Choose "app" for application-centric reports, "host" for host-based, etc.' }
    ),
    eventType: createParameterHelp(
      'Type of event to filter by (a for audit, m for masking, s for security).',
      { suggestion: '"a" for audit logs, "m" for masking events, "s" for security incidents.' }
    )
  }
});
